### ISSUE TITLE
FileField display in detailed view doesn't provide any easy way to download the file

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#104]
<img width="1096" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/7ccd30f4-11f6-446f-8cf0-193989a0ed5a">

The ideal flow here is that if you click on the image, it'll take you to the full sized version. That's currently not possible - you have to triple click, right click, and then hit "go to"

**Comment by lukasvinclav** [comment]
Thanks, I just added a support for linked pictures. It will be available in the next release.

**Comment by omargawdat** [comment]
> <img alt="image" width="1096" src="https://private-user-images.githubusercontent.com/24847059/255157261-7ccd30f4-11f6-446f-8cf0-193989a0ed5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDQ5NjIsIm5iZiI6MTcxOTg0NDY2MiwicGF0aCI6Ii8yNDg0NzA1OS8yNTUxNTcyNjEtN2NjZDMwZjQtMTFmNi00NDZmLThjZjAtMTkzOTg5YTBlZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE0Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MDgzMWJmM2MzOGMyOWUyOWJjZjczZWNiNTI5MmEyNzI2NTY4MDgyNDhhZTBjNTQwZGNjMDQ3NjFmNzRhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JoMjDdcqpWNx5sATqzMkL2jzTf9Jr0L1ozohK1ZgeRA">
> The ideal flow here is that if you click on the image, it'll take you to the full sized version. That's currently not possible - you have to triple click, right click, and then hit "go to"

that is working for the images but what about the files how can i download them from the admin?
