### ISSUE TITLE
Multiple dashboard pages

### ISSUE THREAD

**Issue by Ladet02** [unfoldadmin/django-unfold#105]
Thank you for this project.

How do I go by having multiple dashboard pages as tabs, as shown in the demo.

Also any chance we can get the demo repo? It will serve as a good reference point for projects s

thank you

**Comment by lukasvinclav** [comment]
Hi, in the demo page it is just hardcoded HTML template without any business logic. If you want you can add there little bit of alpinejs code and display particular content based on which link is clicked in tab navigation. This is not going to require any further changes in Python code. If you are looking how to setup custom dashboard, here is the link pointing at the documentation:

https://github.com/unfoldadmin/django-unfold#custom-admin-dashboard

Regarding the demo repo, that is something what is already considered but there is no estimate.

**Comment by Flexonze** [comment]
+1 for the demo repo! It would be a nice reference.

I love this project btw, I actively use it in my Django projects!

**Comment by eamigo86** [comment]
+1 for the demo repo!

**Comment by boysugi20** [comment]
I have successfully identified a method to incorporate new tabs into the side navigation bar. If you're interested, I can share the steps I took:

1. Add a new HTML file named navigation.html within your templates folder. You can find this path at templates/unfold/helpers/navigation.html.
2. Insert the provided HTML code into the navigation.html file. I sourced this from django-unfold/src/unfold/templates/unfold/helpers/navigation.html:

```
{% load i18n %}

<div class="relative z-30 min-w-sidebar transition-width w-sidebar">
    <nav id="nav-sidebar" class="fixed flex flex-col max-h-screen min-h-screen border-r border-gray-200 bg-gray-50 min-w-sidebar transition-width w-sidebar dark:bg-gray-900 dark:border-gray-800">
        <div class="py-3 mb-5 border-b border-gray-200 dark:border-gray-800">
            <div class="flex items-center h-10 px-6 font-medium text-gray-700 dark:text-gray-200">
                {% if logo %}
                    <img src="{{ logo }}" alt="{% trans "Home" %}"/>
                {% elif branding %}
                    {% include "unfold/helpers/site_icon.html" %}

                    {{ branding }}
                {% endif %}
            </div>
        </div>

        {% include "unfold/helpers/search.html" %}

        <!-- Title -->
        <h3 class="px-6 my-3 text-sm font-medium text-gray-900 first:mt-0 dark:text-gray-200">
            Custom Menu
        </h3>

        <!-- Items -->
        <ol class="px-6">
            <li>
                <a href="/" class="border border-transparent flex h-11 items-center -mx-3 px-3 py-2 rounded-md {% if item.active %}bg-gray-100 font-semibold text-primary-600 dark:border dark:border-gray-800 dark:bg-white/[.02] dark:text-primary-500{% else %}text-gray-500 hover:text-gray-700 dark:text-gray-400 hover:dark:text-gray-200{% endif %}">
                    <span class="text-sm">
                        Dashboard
                    </span>
                </a>
            </li>
        </ol>

        <hr class="mx-6 my-2 border-t border-gray-200 dark:border-gray-800" />

        {% if sidebar_navigation|length > 0 %}
            {% include "unfold/helpers/app_list.html" with app_list=available_apps %}
        {% else %}
            {% include "admin/app_list.html" with app_list=available_apps show_changelinks=False %}
        {% endif %}
    </nav>
</div>
```

Once these changes are implemented, a new navigation item should become visible. Feel free to personalize the title and items sections according to your preferences.

**Comment by lukasvinclav** [comment]
To add a custom link into sidebar navigation pointing at the dashboard you can check the documentation here https://github.com/unfoldadmin/django-unfold#available-settingspy-options

I'm not sure if I helped you or you are looking for something else.

PS: demo repository is already in progress with multiple examples. I will let you know here when it is done.

**Comment by lukasvinclav** [comment]
Hey,

there are two new repositories containing some code examples below. In case of some feedback, please open issues in specific repositories.

[Formula](https://github.com/unfoldadmin/formula) - Example demo repository
[Turbo](https://github.com/unfoldadmin/turbo) - Django & Next.js boilerplate which implements Unfold
