### ISSUE TITLE
Request for Code Examples to Enhance Understanding and Implementation

### ISSUE THREAD

**Issue by eamigo86** [unfoldadmin/django-unfold#106]
Hello,

I recently discovered your library and I'm absolutely fascinated by the demo. First and foremost, I wanted to express my admiration for the excellent work you've done in integrating cutting-edge technologies to enhance the Django admin user experience.
After thoroughly reading the documentation, I believe that it might be challenging for a backend developer to achieve similar results without having access to some example code. It would be greatly appreciated if you could kindly consider sharing some code snippets from the demo, or perhaps provide a reference to a similar project that showcases the full capabilities of this library. Having practical examples would undoubtedly enhance the learning experience and complement the existing documentation.
Thank you very much for your attention and for creating such a remarkable library. I look forward to exploring more of its possibilities.

Best regards

**Comment by vade** [comment]
Hey, I second everything that @eamigo86 said. Having some sample code to look at would be helpful. For those of us not as versed in some of the tooling (say, tailwind) it's tricky to even understand how to change colors!

**Comment by lukasvinclav** [comment]
Hey, demo repository is already in progress. I will update you here once it is live.

**Comment by vade** [comment]
That's exciting. Thank you!

**Comment by lukasvinclav** [comment]
Hey,

so there are two new repositories containing some code examples below. In case of some feedback, please open issues in specific repositories.

[Formula](https://github.com/unfoldadmin/formula) - Example demo repository
[Turbo](https://github.com/unfoldadmin/turbo) - Django & Next.js boilerplate which implements Unfold

**Comment by vade** [comment]
Hey that's awesome! Thank you @lukasvinclav - where would you prefer feedback/questions (if there are any?)
