### ISSUE TITLE
Object based actions

### ISSUE THREAD

**Issue by justinqian42** [unfoldadmin/django-unfold#107]
Thanks for the great work!

This is regarding the customized action feature.
As for "Detail" and "Submit line" actions, the existing get_actions_detail and get_actions_submit_line methods are just simply derived from the global view based get_actions method which cannot change the action lists based on the target object/instance's attributes.

One reference could be https://github.com/crccheck/django-object-actions.

The desired change would be that the methods also take "object_id" as inputs.

**Comment by justinqian42** [comment]
Forget about this......
I mixed up the detail action and global action.

**Comment by dfg-98** [comment]
Is there a way to archive this?
I have a use case with a Book model that have a field `published` indicating if the Book had been published. I want to have a submit line action that Save and Publish when `published=False` and hide the action when it's published.
