### ISSUE TITLE
Compatibility with third party packages

### ISSUE THREAD

**Issue by samucancld** [unfoldadmin/django-unfold#109]
Hey guys, the project is amazing!

But I'm having some troubles integrating it with some 3rd party packages, like django-fsm-admin or django-celery-beat (being this the most important)

The errors I get on the admin with these packages are like this one:
```
'PeriodicTaskAdmin' object has no attribute 'readonly_preprocess_fields'
```

Do you have any idea why? Do you know any way to solve it?

**Comment by samucancld** [comment]
I could work around the problem with django-celery-beat this way:

```python
# this fixes the admins of django-celery-beat
# to use the unfold model admin as a base class
PeriodicTaskAdmin.__bases__ = (ModelAdmin,)  # noqa
CrontabScheduleAdmin.__bases__ = (ModelAdmin,)  # noqa
ClockedScheduleAdmin.__bases__ = (ModelAdmin,)  # noqa

admin.site.unregister(PeriodicTask)
admin.site.unregister(IntervalSchedule)
admin.site.unregister(CrontabSchedule)
admin.site.unregister(SolarSchedule)
admin.site.unregister(ClockedSchedule)

admin.site.register(PeriodicTask, PeriodicTaskAdmin)
admin.site.register(IntervalSchedule, ModelAdmin)
admin.site.register(CrontabSchedule, CrontabScheduleAdmin)
admin.site.register(SolarSchedule, ModelAdmin)
admin.site.register(ClockedSchedule, ClockedScheduleAdmin)
```

**Comment by lukasvinclav** [comment]
hey, I just checked django-celery-beat  and you are right about `readonly_preprocess_fields`. I will try to take a look and address this issue. 

Regarding the site unregister and register, this seems to be a right approach to me. It is needed to add custom ModelAdmin from Unfold to get proper behavior and visual.

**Comment by samucancld** [comment]
This seems to be fixed now by #110 (tag 0.8.0), so I'm closing it, thanks @lukasvinclav!

**Comment by samamorgan** [comment]
I ran across this issue with [`dj-stripe`](https://github.com/dj-stripe/dj-stripe) and had to solve it in a similar way. Below should work for just about any app that doesn't immediately work with `unfold`, and doesn't make you monkey around with `__bases__`:
```python
from django.contrib import admin
from djstripe.admin import StripeModelAdmin
from unfold.admin import ModelAdmin


class StripeModelAdminOverride(ModelAdmin, StripeModelAdmin):
    pass


for model, _model_admin in dict(admin.site._registry).items():
    if model._meta.app_label != "djstripe":
        continue

    admin.site.unregister(model)
    admin.site.register(model, StripeModelAdminOverride)

```

I just stuck this in a utility app's `admin.py`

**Comment by mukundshah** [comment]
```py
from django.contrib import admin
from unfold.admin import ModelAdmin

for model, model_admin in dict(admin.site._registry).items():
    if model._meta.app_label not in [
        "djstripe",
        "knox",
        "socialaccount",
        "usersession",
    ]:
        continue

    admin.site.unregister(model)

    new_admin_class = type(
        f"{model.__name__}AdminOverride",
        (model_admin.__class__, ModelAdmin),
        {},
    )

    admin.site.register(model, new_admin_class)
```
I improved upon @samamorgan's solution. This one preserves the attributes of admin class and works for any package.
