### ISSUE TITLE
BUG? Input styles missing

### ISSUE THREAD

**Issue by nikolaimoiseev01** [unfoldadmin/django-unfold#112]
Installed absolutely fresh django, then django-unfold. Everything's great except any input fields (textarea, datepicker etc.). Looks like It doesn't catch right classes. Do I have to write somewhere how inputs should look like?
![image](https://github.com/unfoldadmin/django-unfold/assets/89159295/a83c378a-7b43-458c-9d4a-d66ba5f1b212)

**Comment by nikolaimoiseev01** [comment]
Sorry for creating this issue. Just needed to register my class in admin.py from unfold.admin.

**Comment by nikolaimoiseev01** [comment]
Sorry for creating this issue. Just needed to register my class in admin.py from unfold.admin.

**Comment by hernansaa** [comment]
@nikolaimoiseev01 hey! i am having the same problem. For example the date picker is still like the django admin. How did you register the class?
