### ISSUE TITLE
Add support for MoneyField from django-money

### ISSUE THREAD

**Issue by heckad** [unfoldadmin/django-unfold#114]
Now in admin this field loks like 
![image](https://github.com/unfoldadmin/django-unfold/assets/45011689/90999f85-e6f2-451c-9309-9f13a5274f2c)
but in default django admin it's looks like
![image](https://github.com/unfoldadmin/django-unfold/assets/45011689/b0908dd1-6514-4e2a-b441-b299c370ffae)
How to make that currency shows too?

Thank you so much for such a great admin!

**Comment by mcosti** [comment]
What a beautiful project, I can't wait to use it!
But indeed, django-money is not supported unfortunately, the currency field is completely missing

**Comment by lukasvinclav** [comment]
Thanks for kind words. Django-money integration is already prepared and will be shipped in few days.

**Comment by lukasvinclav** [comment]
New feature has been released.
