### ISSUE TITLE
Select elements on actions looks weird

### ISSUE THREAD

**Issue by nanocatdemen** [unfoldadmin/django-unfold#115]
Thanks for the awesome project. Im using firefox for ubuntu 117.0

In the action section in a normal admin page:

![image](https://github.com/unfoldadmin/django-unfold/assets/2347656/30b33a6e-c1d6-42a1-a5ad-7bd6f5a1cf79)

Looks like this

![image](https://github.com/unfoldadmin/django-unfold/assets/2347656/a72cc303-fe81-4b41-8014-52a6c443109e)

**Comment by lukasvinclav** [comment]
Duplicate issue #112
