### ISSUE TITLE
Can't find credentials for demo website

### ISSUE THREAD

**Issue by Flexonze** [unfoldadmin/django-unfold#123]
Hey. Love this project, you're doing amazing work!

I've been looking for the last couple minutes to find the credentials to access the demo at https://demo.unfoldadmin.com/admin/login/?next=/admin/. I know I managed to access it in the past, but I can't find it anymore.

If they are still there somewhere, they probably need to be more obvious (maybe even in the help_texts of the username and password field).

Thanks

**Comment by lukasvinclav** [comment]
Hey, tomorrow I will redeploy demo website with proper settings. Thanks for pointing at this issue.

If you want you can try demo site locally:

https://github.com/unfoldadmin/formula

**Comment by lukasvinclav** [comment]
Fixed.
