### ISSUE TITLE
Many-to-many autocomplete fields overflow multi-column fieldsets when long stringified values are selected

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#124]
<img width="1144" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/7bb561f3-a088-45bb-8849-b8bf800adf0b">

To reproduce:

1. Create a model with at least two fields, of which one is many to many. In this example I use a field called `multiselect_field`.
2. Override the `__str__` property of the model to output a suitably long string.
3. Make the many to many field auto-complete in the admin class, and put the autocomplete M2M field as the first field in a two-column fieldset.

```
autocomplete = ("multiselect_field",)
fieldsets = (
        (
            "Fieldset title",
            {
                "fields": (
                    ("multiselect__field", "any_field"),
                )
            },
        ),
)
```

**Comment by lukasvinclav** [comment]
Fixed.
