### ISSUE TITLE
Add support for django-modeltranslation

### ISSUE THREAD

**Issue by heckad** [unfoldadmin/django-unfold#125]
Now if you have 2 languages in the admin area you see a 

![image](https://github.com/unfoldadmin/django-unfold/assets/45011689/139d0bd0-8b77-439e-8ec5-7245a1c12901)

The first name field did nothing. If you change them then nothing happens. How to remove them?

**Comment by heckad** [comment]
Yes, I can change the first field through the second. That makes the first field useless. How to remove them?

**Comment by lukasvinclav** [comment]
I think, this behavior is coming from django-modeltranslation and has nothing to do with Unfold.

**Comment by heckad** [comment]
But modeltransaltion provides a widget which solves the problem.  Can we adopt them in the `unfold`?
