### ISSUE TITLE
Add support for django-modeltranslation

### ISSUE THREAD

**Issue by Macktireh** [unfoldadmin/django-unfold#133]
Hi,
I hope you're doing well. This project is really cool, and I appreciate your work on it. I wanted to ask if you would consider adding integration for django-modeltranslation to handle translation fields? Thank you in advance.

Observed Behavior:

![Capture d'écran 2023-09-25 002619](https://github.com/unfoldadmin/django-unfold/assets/49348001/e338c450-fff4-4023-8bf3-871b27b9c41f)

Expected Behavior:

![Add-Category-_-Medine-Database-Administration-Google-Chrome-2023-09-25-00-16-37](https://github.com/unfoldadmin/django-unfold/assets/49348001/8e8a04b1-7f1a-4455-a291-8bb4b5bceee6)

Thank you.

Best regards,

**Comment by lukasvinclav** [comment]
Thanks for report. This one looks more complex to implement. Right now I can recommend you to use default supporter behavior (no tabs) in Unfold.

**Comment by InzGIBA** [comment]
@Macktireh, Try using django-parler for translations

<details>
  <summary>template path: **admin/parler/language_tabs.html**</summary>
  ```
{% load i18n %}

{% if language_tabs %}
<div class="flex items-start flex-col mb-2 text-gray-500 text-sm w-full md:border-b dark:md:border-gray-800 md:border-l-0 md:flex-row md:items-center md:justify-end dark:text-gray-400">
    <ul class="border rounded-md flex flex-col w-full md:flex-row md:border-b-0 md:border-t-0 md:border-l-0 md:border-r-0 dark:border-gray-800">
	{% for url,name,code,status in language_tabs %}
        {% if status == 'current' %}
        <li class="border-b last:border-b-0 md:border-b-0 md:mr-8 dark:border-gray-800">
            <a href="{{ url }}" class="block px-3 py-2 md:py-4 md:px-0 dark:border-gray-800 border-b md:border-primary-500 dark:md:border-primary-600 font-medium -mb-px text-primary-600 hover:text-primary-600 dark:text-primary-500">
                {{ name }}
            </a>
        </li>
        {% else %}
        <li class="border-b last:border-b-0 md:border-b-0 md:mr-8 dark:border-gray-800">
            <a href="{{ url }}" class="block px-3 py-2 md:py-4 md:px-0 dark:border-gray-800 hover:text-gray-700 dark:hover:text-gray-200">
                {{ name }}
            </a>
        </li>
        {% endif %}
    {% endfor %}
    </ul>
</div>
{% endif %}

{% comment %}
    <div class="parler-language-tabs{% if language_tabs.css_class %} {{ language_tabs.css_class }}{% endif %}">
        {% for url,name,code,status in language_tabs %}
        {% if status == 'current' %}
        <input type="hidden" class="language_button selected" name="{{ code }}" />
        <span class="current">{{ name }}{% if language_tabs.current_is_translated and language_tabs.allow_deletion %}<a class="deletelink" href="./delete-translation/{{ code }}/" title="{% trans 'Delete Translation' %}">&nbsp;</a>{% endif %}</span>
        {% else %}
        <span class="{{ status }}"><a href="{{ url }}">{{ name }}</a> {% if status == 'available' and language_tabs.allow_deletion %}<a class="deletelink" href="./delete-translation/{{ code }}/" title="{% trans 'Delete Translation' %}">&nbsp;</a>{% endif %}</span>
        {% endif %}
    {% endfor %}
    </div>
{% endcomment %}

  ```
</details>

**Comment by Macktireh** [comment]
@InzGIBA Thank you for your suggestion. I have previously tried django-parler, and it integrates well. However, I prefer not to use django-parler's method of storing translations in the database, as it creates a separate translation table for each model, which could potentially impact performance.

**Comment by Flexonze** [comment]
+1 on this. When working with many different languages and with multiple translated field, having to tabs makes the page almost ususable. 

For example, let's say my application supports 10 different languages and my model has 4 fields that can be translated. This makes 40 text fields appear in the admin instead of just 4 + a language switcher.

![image](https://github.com/unfoldadmin/django-unfold/assets/39711582/b07ee2ba-f72c-49ef-941d-29a360146c23)

django-modeltranslation is a package that is used by a lot of projects (and is still actively maintained), and it not being supported by unfold could be a dealbreaker for many people. I am facing this exact issue right now on the current project I am working on. Although I very much enjoy django-unfold and I am very grateful for the effort you put into it, I might have to revert to using the default django admin theme, since translating model fields is a priority in the project.

**Comment by Biftor** [comment]
+1 on this.
this is really missing
translation in this way messes up the admin ui
really looking forward for it.

**Comment by lukasvinclav** [comment]
@Biftor @Flexonze @Macktireh support for tabs added #244
