### ISSUE TITLE
TextInputWidget doesn't show a text preview when the type is set to "color"

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#135]
Using the following worked example, this is how text fields render when the input type is set to color:

<img width="696" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/0a397dcb-d86d-4019-9b31-3e1b2cda2f6c">

```python
class ExampleAdmin(ModelAdmin):
    def get_form(self, request, obj=None, change=False, **kwargs):
        form = super().get_form(request, obj, change, **kwargs)

        form.base_fields["color_field"].widget = UnfoldAdminTextInputWidget(attrs={"type": "color"})

        return form
```

The functionality as a field actually works fine including the color selection dropdown in chromium browsers.

**Comment by lukasvinclav** [comment]
I just merged new implementation for color widget which will be available in next release. Below you can see, how you can implement it. You don't have to pass type in attrs.

`    
from unfold.widgets import UnfoldAdminColorInputWidget

def get_form(self, request, obj=None, change=False, **kwargs):
        form = super().get_form(request, obj, change, **kwargs)
        form.base_fields["color"].widget = UnfoldAdminColorInputWidget()
        return form
`

**Comment by Daspy11** [comment]
Amazing, thanks Lukas
