### ISSUE TITLE
Badge callback is stale due to LRU cache and side effects 

### ISSUE THREAD

**Issue by sixthgear** [unfoldadmin/django-unfold#136]
Hi there,

I noticed that when using the "badge" entry in the navigation config as a callback (in my case trying to provide a dynamic count of certain records) that the callback is called once and then cached indefinitely. 

I traced this back to the following sequence of events:

1. In `get_sidebar_list`, we start of by calling `get_config(self.settings_name)["SIDEBAR"].get("navigation", [])`
2. Initially, this returns the config dictionary (default + user config) wrapped in a `@lru_cache` decorator.
3. We iterate the navigation items, but in some places, we mutate the contents of the cached dictionary. Due to the way @lru_cache works, this actually modifies (pollutes) the cached record, meaning that the next call to the decorated get_config function returns the modified dict.
4. Continuing down the function, we iterate each item and examine its badge entry. If it's a string, we try to import it as a module path using Django's `import_string` function. If successful, we execute the imported function and assign it's return value to `item['badge']`. This not only returns the badge callback result for the current request, but as a side effect also modifies the cached record as noted above.
5. On the next request, `item['badge']` has been replaced with the callback result from the last step, so it will never** call the badge function again unless the process is restarted or the LRU cache is somehow otherwise evicted. 

_** unless the return value happens to be a string, in which case we'll continue to try to import it even if its not a module path!_

To me, this behavior seems unintentional, but I thought I'd open to discuss and double check. Is it desirable to use badge callbacks to report dynamic values? If so I have some ideas on how to improve this function, but let me know!

**Comment by lukasvinclav** [comment]
Thanks for report. I just merged a fix for this.
