### ISSUE TITLE
Fieldset descriptions are not spaced from the fields underneath

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#140]
<img width="1232" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/2b464fbd-e2a5-4469-8d5a-23a4329cebd9">

The content here is too close, and the font size of the description being larger than the title of the queryset doesn't seem right. 

With the addition of a humble `mb-4 text-sm pl-3` to the description element, the content looks like this instead:

<img width="1232" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/4f86fed5-cd37-4109-ac17-2acc64279055">

**Comment by lukasvinclav** [comment]
Hey, I just merged the fix. It will be available in the next release.

PS: I noticed you are regularly providing valuable feedback for which I'm really thankful.
