### ISSUE TITLE
django-json-widget's PrettyJSONWidget stopped working with django-unfold

### ISSUE THREAD

**Issue by rburhum** [unfoldadmin/django-unfold#143]
Hello!

I started using Django unfold and I love it. Previously, I was using `PrettyJSONWidget` from https://kevinmickey.github.io/django-prettyjson/ to render the json nicely in the admin and it worked perfectly, but when I added Django Unfold, it just renders like a Textbox. I managed to adjust all my other Django Admin customizations except for this one. 

I noticed from https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/widgets.py#L296 that most of the widget optimizations rely on `django.contrib.admin.widgets' and assign them the styling classes, but the particulars of PrettyJSONWidget require the use of formfield_overrides like so:

```python
@register(WalletInquiry)
class WalletInquiryAdmin(admin.ModelAdmin):

    formfield_overrides = {
        JSONField: {
            "widget": PrettyJSONWidget(
                attrs={"initial": "parsed", "disabled": True}
            )
        }
    }
```

Any plans on supporting a json admin widget? Or perhaps any directions on how I can go about fixing this?

**Comment by lukasvinclav** [comment]
Hey, are you looking just for a widget which properly indent json in JSONField?

**Comment by rburhum** [comment]
@lukasvinclav yes :-)

**Comment by rburhum** [comment]
I see that the way the file gets serialized and written in the database has changed (it has new lines now), but the textbox widget ignores that. 
![image](https://github.com/unfoldadmin/django-unfold/assets/138918/6fa8b52a-11f5-44d9-a2aa-c8d48d60034e)

**Comment by lukasvinclav** [comment]
This is a different request. Before we wanted to have formatting inside the textarea, now we are looking for formatting when JSONField is displayed as readonly field. Anyway, I just merged an improvement which is checking if the readonly field is JSONField and then enables additional formatting.

**Comment by qengine13** [comment]
how do you make unfold implement the Json field correctly?
