### ISSUE TITLE
django-import-export actions styling not working

### ISSUE THREAD

**Issue by FadingFog** [unfoldadmin/django-unfold#145]
![image](https://github.com/unfoldadmin/django-unfold/assets/10418075/464aaf70-11be-4e5b-86ae-92d4b6347296)
![image](https://github.com/unfoldadmin/django-unfold/assets/10418075/2a8f05bd-e519-46be-8dc2-cb6521ddb28c)
After inheriting from `ImportExportActionModelAdmin` action styling doesn't work. The same issue with any model with import/export action.
`unfold.contrib.import_export` added at the beggining of the `INSTALLED_APPS`
Django 3.2.20, django-import-export 3.3.1 (latest), django-unfold 0.11.0 (latest)

**Comment by FadingFog** [comment]
> Hey, could you try to put "ImportExportActionModelAdmin" after "ModelAdmin"?

Yep, still the same

**Comment by rburhum** [comment]
I actually had to write a workaround last week to make it (partially) work. The issue has to do with how the Choices control gets added (which has a different inheritance tree). There is still something with the labels, hence why I set it to " ". Have not had time to look into it, but at least this unblocked me. I hope it helps.

```python
from django.utils.translation import gettext_lazy as _
from unfold.forms import ActionForm
from unfold.widgets import SELECT_CLASSES

########################################################################################################
#
# Below we have workarounds to make the export *action* functionality work with
# the unfold admin. The original implementation of the import/export functionality
# is in the django-import-export package with the following problems:
#
# 1) django.forms.ActionForm needs to be changed to unfold.ActionForm. There is a
#    export_action_form_factory function that has been copied from the original
#    import_export module as is, and just modified to use unfold.ActionForm
#
# 2) ExportActionModelAdmin needs to inherit from unfold.ModelAdmin instead of
#    django's ModelAdmin. We create a new class CanariaExportActionModelAdmin to
#    reduce confusion.
#
# 3) CanariaExportActionMixin's __init__ method is an exact copy of the original
#    parent class import_export_admin.ExportActionMixin, but we leave the rest of
#    the class as is. Since we only want to override the __init__method which creates
#    the ActionForm (i.e. our unfold ActionForm, not Django's) we just copy the
#    whole class ****and skip the __init__ method of the parent class****. This is the
#    trick to make it work.


def export_action_form_factory(formats):
    """
    Returns an ActionForm subclass containing a ChoiceField populated with
    the given formats.
    """

    class _ExportActionForm(ActionForm):
        """
        Action form with export format ChoiceField.
        """

        # label=_("Format") - it is not rendering correctly because of styling
        # will submit an issue to unfold
        file_format = forms.ChoiceField(
            label=_(" "),
            choices=formats,
            required=False,
            widget=forms.Select({"class": " ".join([*SELECT_CLASSES, "w-72"])}),
        )

    _ExportActionForm.__name__ = str("ExportActionForm")

    return _ExportActionForm


class CanariaExportActionMixin(import_export_admin.ExportActionMixin):

    def __init__(self, *args, **kwargs):
        """
        Adds a custom action form initialized with the available export
        formats.
        """
        choices = []
        formats = self.get_export_formats()
        if formats:
            for i, f in enumerate(formats):
                choices.append((str(i), f().get_title()))

        if len(formats) > 1:
            choices.insert(0, ("", "---"))

        self.action_form = export_action_form_factory(choices)
        # skip the direct super class constructor of the mixin and
        # chain it up to the next class in line
        super(import_export_admin.ExportMixin, self).__init__(*args, **kwargs)


class CanariaExportActionModelAdmin(CanariaExportActionMixin,
                                    unfold_admin.ModelAdmin):
    """
    Subclass of Unfold ModelAdmin with export functionality implemented as an
    admin action. We use unfold admin to change the default look of the admin.
    """
    pass
```

**Comment by lukasvinclav** [comment]
@rburhum are you specifying import_form and export_form? Docs here:

https://github.com/unfoldadmin/django-unfold#django-import-export

**Comment by lukasvinclav** [comment]
@FadingFog I just tested the application on User model and it was working as expected. I recommend to check an example implementation of UserAdmin in Formula project and especially how UserAdmin inherited from BaseUserAdmin:

https://github.com/unfoldadmin/formula/blob/main/src/formula/admin.py#L3

**Comment by FadingFog** [comment]
This is optional since I am overriding the model. And as I said, it makes no difference if I use UserAdmin or just another model - the result is the same on all models

**Comment by lukasvinclav** [comment]
Please create for me an example repository where I can reproduce this behavior.

**Comment by rburhum** [comment]
> @rburhum are you specifying import_form and export_form? Docs here:
> 
![test](https://github.com/unfoldadmin/django-unfold/assets/138918/ae233ee0-0089-4481-bbdb-49ce2e69d0f6)

> https://github.com/unfoldadmin/django-unfold#django-import-export

@lukasvinclav I only needed to do export - don't want import because it doesn't make sense in my application and I have special logic. With my overrides, it works.

**Comment by FadingFog** [comment]
Interesting... I created new django project with same versions of packages, but behavior is completely changed. So, there're now buttons for import and export, instead of actions (so its applied to all of the elements in changelist) and styling works well. Here is comparison:
Existing project
![image](https://github.com/unfoldadmin/django-unfold/assets/10418075/72a3f11d-2852-49db-a35b-1c7e81972623)

New project
![image](https://github.com/unfoldadmin/django-unfold/assets/10418075/e3cb9f21-3bf1-4f26-b4e4-e740550144e5)

**Comment by lukasvinclav** [comment]
Based on the picture, I guess issue was solved. For other people, please be aware that `unfold.contrib.import_export` has to be in `INSTALLED_APPS` before `import_export`.

**Comment by pedrorodriguesar** [comment]
i put unfold.contrib.import_export in settings and get "ModuleNotFoundError: No module named 'unfold.contrib.import_export'"
