### ISSUE TITLE
select dom had duplicate "down arrow" 

### ISSUE THREAD

**Issue by zicokuo** [unfoldadmin/django-unfold#15]
![image](https://user-images.githubusercontent.com/4969958/196365532-23ffcf63-436c-4d36-95ff-0b8a333cdb01.png)

When I use unfold, I find that there are duplicate first arrows in the drop-down selection box, like the snapshot.

I add a same className to fix by myself.

```style
<style>
  select:not([class*=bg-none]):not([multiple]) {
      -webkit-appearance: none; 
      -moz-appearance: none;
      appearance: none;
  }
</style>
```

**Comment by lukasvinclav** [comment]
You admin class must inherit from `unfold.admin.ModelAdmin`
