### ISSUE TITLE
Add support for django-autocomplete-light

### ISSUE THREAD

**Issue by Biftor** [unfoldadmin/django-unfold#157]
Hi there,

I hope you're doing well. this project is really great, I wanted to suggest adding support for django-autocomplete-light. It would be a fantastic addition to an already amazing project.

Thanks in advance!

**Comment by lukasvinclav** [comment]
To be honest I don't have an experience with this application. Can you tell me how exactly it is used in the admin? Because Django admin has own implementation of autocomplete.
