### ISSUE TITLE
Confusion about list filters

### ISSUE THREAD

**Issue by mcosti** [unfoldadmin/django-unfold#160]
Hey there! A quick question, how are filters supposed to work without adding this to the ModelAdmin class?

```python
    list_filter_submit = True  # Submit button at the bottom of the filter
```

I couldn't figure out what the UX is otherwise

Thanks

**Comment by lukasvinclav** [comment]
Do you mean custom filters coming from Unfold? These filters are regular input types so they need a submit button.

**Comment by mcosti** [comment]
Yes, but why is that not the default behavior? How can you apply the filters without adding list_filter_submit to the modeladmin?

**Comment by lukasvinclav** [comment]
By default Django provides filters that are regular links so there is no reason to have a submit button and thus it is not needed to have it by default enabled. Filters coming from Unfold, are input fields so the submit button is mandatory to submit the form then you have to enable `list_filter_submit` flag.
