### ISSUE TITLE
Simple history styling

### ISSUE THREAD

**Issue by mcosti** [unfoldadmin/django-unfold#161]
Hi, one more question:

Is the styling of the history page supposed to look like this?

![image](https://github.com/unfoldadmin/django-unfold/assets/16706410/2fa7d795-4583-40bd-92ab-70730360465d)

I've tried it both 

```python
class ObjectAdmin(SimpleHistoryAdmin, unfold.admin.ModelAdmin):
class ObjectAdmin(unfold.admin.ModelAdmin, SimpleHistoryAdmin):
```

**Comment by lukasvinclav** [comment]
Did you added `unfold.contrib.simple_history` into `INSTALLED_APPS`?

**Comment by mcosti** [comment]
I did, yes. It's added after the simple history package itself

**Comment by lukasvinclav** [comment]
Please check proper order here:

https://github.com/unfoldadmin/formula/blob/main/src/formula/settings.py#L38
