### ISSUE TITLE
Readonly fields in multi-column fieldsets are not styled correctly

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#165]
<img width="1038" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/47964c63-a1f3-4b28-bd00-49188d7d3759">

Edge case for sure, but the label style uses that of the fieldset description if it's readonly in a multi-column fieldset. This is likely related, but the vertical spacing is also NotQuiteRight

**Comment by lukasvinclav** [comment]
Thanks for report. I just merged a fix. It will be available in the next release.
