### ISSUE TITLE
django-simple-history integration missing "History" link on object admin page

### ISSUE THREAD

**Issue by nathanglover** [unfoldadmin/django-unfold#173]
Hey there! I think this project is awesome! I was implementing it with django-simple-history into my Django application and noticed that the object page does not link to the history page like it would if using the default Django Admin. This can be seen on the demo site:

**Object Page:** https://demo.unfoldadmin.com/admin/formula/driver/56/change/

**History Page:** https://demo.unfoldadmin.com/admin/formula/driver/56/history/

There is no link between the two (unless I'm blind). 

When using the default admin a small "history" button would show up that would link users to /history:

![image](https://github.com/unfoldadmin/django-unfold/assets/15344788/5e001647-3b3e-4dd3-828d-740f045a551b)

Is there something I need to configure to get this button to show up?

**Comment by xblzbjs** [comment]
Here.
![history_2023-10-31 10 30 28](https://github.com/unfoldadmin/django-unfold/assets/30518110/95afab08-4c95-4da4-b916-5fb262e831a3)
You can also use custom row actions or detail actions

**Comment by cortadocodes** [comment]
@lukasvinclav I'm on version `0.14.0` and also finding this. On version `0.13.0`, the link showed up where @xblzbjs is showing above. Additionally I'm getting the same issue with the `django-guardian` object permissions button. I've added the required `unfold` apps in the `INSTALLED_APPS` setting as described in the readme and collected static but to no avail.

**Comment by lukasvinclav** [comment]
The fix #174 was already released so you can update. Regarding links, user related links are staying in the user dropdown but global links are in the new release available right above the main changelist table. You can find example here in the demo:

https://demo.unfoldadmin.com/admin/formula/driver/56/change/

**Comment by cortadocodes** [comment]
Thanks!

**Comment by nathanglover** [comment]
Thanks for fixing this! @lukasvinclav
