### ISSUE TITLE
Add support for django-nested-admin

### ISSUE THREAD

**Issue by cinarizasyon** [unfoldadmin/django-unfold#177]
Hello,

When using django-nested-admin's nested inlines, unfoldadmin does not show inputs/forms correctly.

<img width="489" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53943169/7da8253a-2bce-45f9-8a64-17997d1e3534">

Is there any plan to fix these issues? 
I think it deserves to be supported as well as django-guardian and django-simple-history because django-nested-admin is a popular extension for django-admin.

**Comment by mcosti** [comment]
@cinarizasyon are you extending the admin classes with the relevant UnfoldAdmin models?

**Comment by cinarizasyon** [comment]
@mcosti yeah, my admin classes seem like:


``` python
class BusinessAdmin(ExtraButtonsMixin, CustomModelAdmin, NestedModelAdmin):
   ....
```

**Comment by lukasvinclav** [comment]
This requires custom styling and integration.

**Comment by dwasyl** [comment]
Just wanted to add a +1 here for this package. The apps I run that could most use `unfold` all depend on `django-nested-admin` for some data entry.  It would be great to see the package supported, or another solution for nested inlines.

**Comment by RovshenTagangylyjov** [comment]
Will django-nested-inline support be added in near future? Or are there any workarounds?

**Comment by intp1** [comment]
With django-nested-admin,  I managed to fix the field style in unfold way,  by adding extension like :
```python
from unfold.contrib.inlines.admin import TabularInline as UnfoldTabularInline

class ShopSPUAtlasInline(UnfoldTabularInline, nested_admin.NestedTabularInline):
    pass
```
However, switching to mobile display,  the css width is not compliant with the mobile screen:
![image](https://github.com/unfoldadmin/django-unfold/assets/59410471/a476f7d5-020f-429b-ba17-260ae7b64dd2)

Does anyone know how to fix the css width in this situation ? Thanks a lot.

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/
