### ISSUE TITLE
FieldSetsType in unfold/typing.py is too narrow

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#179]
The following line of code from `unfold/typing.py` is too restrictive:

`FieldsetsType = List[Tuple[Union[str, None], Dict[str, Any]]]`

The top-level type for a fieldset can be either a list or a tuple. For example:

```
fieldsets = (
    (
        None,
        {
            "fields": ("example", "example2)
        }
    ),
)
```

**Comment by lukasvinclav** [comment]
@Daspy11 would you mind to create a PR?

**Comment by lukasvinclav** [comment]
@Daspy11 I created PR #195. May you check if it is okay?
