### ISSUE TITLE
Actions bar doesn’t go full width when side-nav is collapsed

### ISSUE THREAD

**Issue by yardensachs** [unfoldadmin/django-unfold#186]
## Reproduce:

- Go to a change model view
- Collapse side-nav
- Observe the action/submit bar not expand to 100%

![Screenshot 2023-11-08 at 08 06 10](https://github.com/unfoldadmin/django-unfold/assets/2768400/451f666d-8387-48f3-8004-8b3beae2680e)

## Screencast
https://github.com/unfoldadmin/django-unfold/assets/2768400/966018b9-8e59-45f6-b534-fb3bf4266398

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #193
