### ISSUE TITLE
add fav icon via unfold settings

### ISSUE THREAD

**Issue by wiktorcie** [unfoldadmin/django-unfold#206]
Not available now, should be easy to implement and adds a nice touch.

**Comment by wiktorcie** [comment]
is extrahead of any use to me? Or I need to override default skeleton template?

**Comment by vic-developer** [comment]
no idea, that's what i did.

![image](https://github.com/unfoldadmin/django-unfold/assets/11517372/15586a9a-3be4-432e-a930-a7fdb3daa798)


![image](https://github.com/unfoldadmin/django-unfold/assets/11517372/7cd6476f-d202-4e25-bedb-9c35034cea26)
