### ISSUE TITLE
Add button/HTML on list

### ISSUE THREAD

**Issue by Mte90** [unfoldadmin/django-unfold#207]
So I have the model admin list and I want to add a button to the frontend version with a link.

```
    @display(description=_("Frontend Link"))
    def display_link(self, instance: User):  # noqa
        return '<a href="' + reverse('model_show', args=[instance.id]) + '">Show</a>'
```

I have this code but of course the HTML is sanitized, there is a way on the admin to generate a button or a link in the admin from python?

**Comment by lukasvinclav** [comment]
@Mte90 https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.safestring.mark_safe

**Comment by lukasvinclav** [comment]
Yes, this is the right way. I think this is necessary to do in default django admin as well.
