### ISSUE TITLE
Sort changelist

### ISSUE THREAD

**Issue by Mte90** [unfoldadmin/django-unfold#215]
It would be nice that in the changelist a button to change the order on how are displayed the items in the admin.

**Comment by lukasvinclav** [comment]
Do you want to change an order of columns in changelist table or an order of rows?

**Comment by Mte90** [comment]
Order of rows based on the column, as example order by date column etc

**Comment by lukasvinclav** [comment]
But this is already by default in Django admin. You can click on column heading and it will sort the rows.

**Comment by Mte90** [comment]
As I can see is missing in unfold that feature

**Comment by lukasvinclav** [comment]
Yes, this functionality is supported in Unfold. In case you are still having the issue, please create minimal repository where it is going to be possible to reproduce the issue.

**Comment by Mte90** [comment]
As I can see in the django doc it should be enough on the model to add:
```
admin_order_field = ('field', 'another_field',)
```

Just in case someone else will look for that (I didn't have time to test it now).

**Comment by Mte90** [comment]
So after digging a bit I understood my error in explaining the issue.
I have the changelist with and I want to click on the 3rd column and get the changelist ordered by those values.

In my case I have some of those columns using various custom `display_*` methods.
