### ISSUE TITLE
"Select record" string not wrapped in gettext_lazy

### ISSUE THREAD

**Issue by shmulvad** [unfoldadmin/django-unfold#242]
Hi,

Most of the strings in this library support i18n (which is great)! But the "Select record"-string in `unfold_list.py` has not been wrapped in `gettext_lazy`. Any chance this could get fixed? I would be happy to send in a PR if needed.

https://github.com/unfoldadmin/django-unfold/blob/a01242b5f28f25bd6dcee22ed27d44f69e06cd95/src/unfold/templatetags/unfold_list.py#L307-L312

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #243
