### ISSUE TITLE
RangeDateTimeFilter templete not show date picker 

### ISSUE THREAD

**Issue by vahidtwo** [unfoldadmin/django-unfold#247]
Hi 
i use the unfould  RangeDateTimeFilter for filtering datetime field 
when i use RangeDateFilter the date picker work fine but when i use RangeDateTimeFilter the datepicker not work 
```
@admin.register(models.Fooo)
class FoooAdmin(BaseAdminModelClass):

    list_filter = [
    ...
        ("created_at", RangeDateTimeFilter),
    ]

```
screanshot
![image](https://github.com/unfoldadmin/django-unfold/assets/26719514/b95a5421-f84f-4bf5-93de-b1ba7f4f3b26)

![image](https://github.com/unfoldadmin/django-unfold/assets/26719514/04d26e8d-0d14-4d07-9c15-54e3f05591d9)

as you see in screenshots when i click on edit, the time filter show up
## versions

```bash
Django==3.2.20
djangorestframework==3.13.1
django-extensions==3.1.5
django-admin-rangefilter==0.12.0
django-admin-autocomplete-filter==0.7.1
django-cors-headers==3.13.0
django-import-export==3.2.0
django-unfold==0.17.1

```

**Comment by jrobichaud** [comment]
I never used unfold but i used ˋrangefilter`. I was checking the issues to see if it would compatible with my project. Your issue stood out to me.

Is there a reason you use `rangefilter` instead of `unfold`'s?

From unfold's readme:
```python
# admin.py

from django.contrib import admin
from django.contrib.auth.models import User

from unfold.admin import ModelAdmin
from unfold.contrib.filters.admin import (
    RangeDateFilter,
    RangeDateTimeFilter,
)


@admin.register(User)
class YourModelAdmin(ModelAdmin):
    list_filter_submit = True  # Submit button at the bottom of the filter
    list_filter = (
        ("field_E", RangeDateFilter),  # Date filter
        ("field_F", RangeDateTimeFilter),  # Datetime filter
    )
```

**Comment by vahidtwo** [comment]
the unfold datetime filter utility is not my expected result for filtering data

**Comment by jrobichaud** [comment]
Oh, I understand the point. Maybe you could rename your issue for something like:

> "django-admin-rangefilter" compatibility

**Comment by jrobichaud** [comment]
out of curiosity, what is not expected?

**Comment by lukasvinclav** [comment]
@vahidtwo Unfold has its own range filter. Please check docs for more info.

**Comment by jtzgyw** [comment]
> @lukasvinclav Hi, I am experiencing this issue as well. I have double checked for any conflicting filter libraries and can confirm there are none.
> 
> RangeDateFilter works fine, but RangeDateTimeFilter does not allow a date selection:
> 
> ![image](https://private-user-images.githubusercontent.com/1520135/336110257-3a9346a6-c7ac-48ae-8762-3edd43321b9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Mjg3OTIsIm5iZiI6MTcyMTcyODQ5MiwicGF0aCI6Ii8xNTIwMTM1LzMzNjExMDI1Ny0zYTkzNDZhNi1jN2FjLTQ4YWUtODc2Mi0zZWRkNDMzMjFiOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDk1NDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODc3ZDkyZGJkNjg1Y2FjNzFiYjA1MDIxZjQ0ZjE3NTdhMmZhOTY5YzdhNjY5ZDIyZWNhNzY5MGY1ZWMxOTk2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9kAug-bLH9Q-Rke79m4yP5e6qnclSZ3R_9YXivgsBzQ)
> 
> When clicking the first icon on the left, I get this:
> 
> ![image](https://private-user-images.githubusercontent.com/1520135/336110456-002d471b-652d-4da0-ae51-bbda329c0a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Mjg3OTIsIm5iZiI6MTcyMTcyODQ5MiwicGF0aCI6Ii8xNTIwMTM1LzMzNjExMDQ1Ni0wMDJkNDcxYi02NTJkLTRkYTAtYWU1MS1iYmRhMzI5YzBhNWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDk1NDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZjZTRkYzg4YjFjNzkxMzgwZjg5MjU4NDZmMzViMDg3NTdmNjE3NDY4MzRlYWYyYTQ5MmRmMDY5ZDM2MWM1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pnBFcN0eHmCaDa6nBM7gEn-oY9wiEXv3h5VAtBSc0Rs)
> 
> And when clicking the stopwatch icon, it sets the time only, not the date:
> 
> ![image](https://private-user-images.githubusercontent.com/1520135/336110759-666cb446-d356-46ad-8252-d05c7879df47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Mjg3OTIsIm5iZiI6MTcyMTcyODQ5MiwicGF0aCI6Ii8xNTIwMTM1LzMzNjExMDc1OS02NjZjYjQ0Ni1kMzU2LTQ2YWQtODI1Mi1kMDVjNzg3OWRmNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDk1NDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFjMDFjMDJjMzRmYTJiMWY5ODI4MmI4NDEwYzNkNTc5MmFhNjUxY2EzNjQwMjc0ZWFlMjIzNjY4YjEzMzg1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ItS7AUDYzqLzP5vdgNGy-bcggWLlbJzwJDaAcWpc_H4)
> 
> EDIT: Adding django and related lib info below:
> 
> ```
> root@607cf12ec1c2:/app# pip freeze | grep -i django
> Django==4.1.13
> django-crum==0.7.9
> django-dry-rest-permissions==1.2.0
> django-extensions==3.2.3
> django-rq==2.7.0
> django-storages==1.13.2
> django-unfold==0.26.0
> djangorestframework==3.15.1
> pytest-django==4.5.2
> ```

me too，I also encountered this problem。

**Comment by dimmoon69** [comment]
me too，I also encountered this problem。

**Comment by lukasvinclav** [comment]
This issue is already closed. If you want to report a problem please create new issue.
