### ISSUE TITLE
Permissions and UI improvements.

### ISSUE THREAD

**Issue by Muhammadali-Akbarov** [unfoldadmin/django-unfold#252]
If user has no permissions, app title does not describe in admin panel. 

for example I don't have a permission for Roles, Billing, Pharmacy. That's why only title has exist.

<img width="1280" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/79622590/f40b8933-dd7c-47cb-a503-815740b10e0c">

**Comment by Muhammadali-Akbarov** [comment]
https://github.com/unfoldadmin/django-unfold/pull/253

plz merge it, it has already fixed.

**Comment by lukasvinclav** [comment]
Fixed in #258
