### ISSUE TITLE
Style sidebar scroll bar for dark mode

### ISSUE THREAD

**Issue by anorthall** [unfoldadmin/django-unfold#259]
Thanks for the fantastic project. I've been using it heavily and hope to contribute some code when I have time.

For now, the scroll bar could look a lot better when using dark mode. I've attached a screenshot to illustrate the issue.

Screenshot was taken in Google Chrome.

![CleanShot 2024-01-16 at 01 01 22](https://github.com/unfoldadmin/django-unfold/assets/3952223/4a678d25-3f7a-488f-b216-6e01039edc3c)

**Comment by lukasvinclav** [comment]
Fixed #433

**Comment by anorthall** [comment]
> Fixed #433

Thanks so much!
