### ISSUE TITLE
Auto_complete styling works incorrectly for ForeignKey field when more than one field on one line

### ISSUE THREAD

**Issue by justinqian42** [unfoldadmin/django-unfold#267]
<img width="720" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/49712643/ad30308c-cb90-4ab5-ab3b-0dae021bad4c">

As the picture shows, the selection bar's width is longer than the drop-down menu.

**Comment by justinqian42** [comment]
<img width="1140" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/49712643/304e65b9-801e-4434-925d-1d1a864f4f08">

Seems fixable by adding in `style="width: 100%;"`.

**Comment by afsangujarati93** [comment]
I have having similar issue with inline foreign keys. 

Unrelated to your post, how did you implement this? 
<img width="378" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/32711400/801bff0c-5e39-4387-bca1-af22b343bd5b">

**Comment by lukasvinclav** [comment]
@justinqian42 fixed #364

**Comment by justinqian42** [comment]
> @justinqian42 fixed #364

Thanks Luka! You're the best!

**Comment by justinqian42** [comment]
> I have having similar issue with inline foreign keys.
> 
> @justinqian42 Unrelated to your post, how did you implement this? <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/32711400/323342083-801bff0c-5e39-4387-bca1-af22b343bd5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MDc2NDMsIm5iZiI6MTcxNDkwNzM0MywicGF0aCI6Ii8zMjcxMTQwMC8zMjMzNDIwODMtODAxYmZmMGMtNWUzOS00Mzg3LWJjYTEtYWYyMmIzNDNiZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDExMDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDZmNzlhOWY3MDdlYzYyYjFmMjQ5NWQ1NjMxZDEzMTVkYjI3MzA1NTQ2MDJkYTI1NmEzYTFmNzYzMjA0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.POMTmY5QD6_cHn8lKKBWIRZ3Vy0i3KHNDOrCw4tAEnM">

@afsangujarati93 just enable auto_complete for the field.
