### ISSUE TITLE
Filter not working correctly

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#272]
1. the filters aren't working when they have empty fields and get a server error. 
2. You can't create separate filters for the same model as all of them combined.

**Comment by Daspy11** [comment]
You will need to elaborate

**Comment by omargawdat** [comment]
sure in the demo imagine if i want to filter some orders based on the date only, if i set the correct dates i will get an error because the other fields are empty, and i can't for example remove the other fields because maybe i need sometimes to use them. 
<img width="387" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/d3c98bc5-57e9-4633-98f2-4e56c9cf3fdb">
<img width="1023" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/afe3b5f0-0383-4f03-be42-ecd818993309">

**Comment by lukasvinclav** [comment]
Fixed in #293
