### ISSUE TITLE
Object History Issue on Admin Site

### ISSUE THREAD

**Issue by makemypro** [unfoldadmin/django-unfold#273]
Getting this issue when goto history. ⬇️ 

<img width="1134" alt="Screenshot 2024-01-31 at 15 42 34" src="https://github.com/unfoldadmin/django-unfold/assets/86561828/015f8b98-3e6b-4041-b598-be96327eec02">

**Comment by lukasvinclav** [comment]
I'm not able to reproduce the issue. Would you mind to create a repository with the minimal example?
