### ISSUE TITLE
Badge problem

### ISSUE THREAD

**Issue by cloudyaaron** [unfoldadmin/django-unfold#283]
Issue #274 is now fixed but similar issue on sidebar badge still exists, it will not show different badge to different user

**Comment by juozasal** [comment]
Confirming: sidebar badge shows previously logged-in user context, not current connection. 
After restart of server issue temporary disappears - until another user connects to website.

**Comment by lukasvinclav** [comment]
Which version of django-unfold are you using?

**Comment by juozasal** [comment]
Django==4.2.7
django-unfold==0.20.3

**Comment by lukasvinclav** [comment]
When you look at our demo page you can see a badge in sidebar with a dynamic value. It is changing on each refresh. Here what I can recommend to you is to create a demo repository where I it is possible to reproduce the issue.
