### ISSUE TITLE
django-modeltranslation bug not support custom field

### ISSUE THREAD

**Issue by Biftor** [unfoldadmin/django-unfold#285]
Hi,
First of all appreciated to adding support for this package ([from here](https://github.com/unfoldadmin/django-unfold/issues/133)) with great UI.
There are couple of issues/bugs may need to mention to figure it out somehow,
it seems you have added support this style 
![Screen Shot 2024-02-09 at 3 37 04 AM](https://github.com/unfoldadmin/django-unfold/assets/7228469/71bb6c48-901a-49c3-8047-8b41fc52b70a)
for some specific fields like charField or textfields, not for every cases which a field is translatable.
for example if i extend textfields to some other classes name(in my case MaxLengthTextField), the style not working as you see in screen shot
![Screen Shot 2024-02-09 at 3 42 17 AM](https://github.com/unfoldadmin/django-unfold/assets/7228469/674c6f7c-14e6-4392-ac32-c805b6992590)

also not support **image fields** or **file fields**, in case you have them translatable

Thank you for your great work.
Regards,

**Comment by lukasvinclav** [comment]
Thanks for report . File field and WYSWIG fixed #545
