### ISSUE TITLE
Is their any option for displaying the inline admins as horizontal tabs like jazzmin? 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#290]
in jazzmin i could display the inline admin in seperate hotizontal tabs instead of vertical using the below line: 
 "changeform_format": "horizontal_tabs",

<img width="759" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/9f3c594d-bf09-4a43-b96a-06fb2a3297cf">

**Comment by lukasvinclav** [comment]
This is the only way how to add tabs:

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#change-form-tabs

**Comment by omargawdat** [comment]
> This is the only way how to add tabs:
> 
> https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#change-form-tabs

first thanks for your amazing work, but this way I am showing the fields in horizontal tabs can I do the same for the TabularInline for example to display it in horizontal tabs instead of vertically?
