### ISSUE TITLE
[Bug] ManyToMany field

### ISSUE THREAD

**Issue by pjhr23** [unfoldadmin/django-unfold#296]
ManyToMany fields don't work properly, you can never save the object when a ManyToMany is set on `raw_id_fields`

- These fields should be optional.

![image](https://github.com/unfoldadmin/django-unfold/assets/64214538/fb9f7c33-3d45-461e-8537-a6604d7a28fc)

- When you type some data, it always says the input is not valid.

![image](https://github.com/unfoldadmin/django-unfold/assets/64214538/d4943702-99a9-4fe6-a613-312ad69c3086)

It would also be nice to add the possibility of searching for an object on `raw_id_fields` (like default Django admin)

**Comment by lukasvinclav** [comment]
Fixed #424
