### ISSUE TITLE
if model name with dash, the list and edit page's css will be error.

### ISSUE THREAD

**Issue by changwu** [unfoldadmin/django-unfold#309]
I report an error, if my model name with dash, something like ths_post, the list page and edit page will display with error css, could u test it? Or tell me how to handle it with dash in model.

**Comment by lukasvinclav** [comment]
Would you mind to provide detailed information about this error? How it is possible to replicate it?

**Comment by changwu** [comment]
hi, if the model name "ranking", the pages display well, as below:
![1](https://github.com/unfoldadmin/django-unfold/assets/57764/3ecef112-4931-48c2-a5d6-b5a37fe6a44b)
while, the model name is "ths_post", the display will be not tidy, I think its css maybe not works. as below:
![2](https://github.com/unfoldadmin/django-unfold/assets/57764/3c158b51-aaca-4d7e-9ecc-db017def338d)
![3](https://github.com/unfoldadmin/django-unfold/assets/57764/bbe2b55f-6095-4cfa-9091-65ee039bcebd)

**Comment by changwu** [comment]
I guess it be caused by the model name's underline（sorry, I make mistake with dash and underline).

**Comment by lukasvinclav** [comment]
Please make sure that all your registed admin models are inheriting from `unfold.admin.ModelAdmin`
