### ISSUE TITLE
raw_id_fields is not work correct

### ISSUE THREAD

**Issue by artel1992** [unfoldadmin/django-unfold#313]
How I can create this [widget](https://drive.google.com/file/d/1dmBJT0AiVBHeDXZ31-eS7QbXH28wmzW2/view)?

I need to get relation through window. But not <select>

**Comment by lukasvinclav** [comment]
Fixed #424

**Comment by krs23** [comment]
This did not work 100% properly, when opening a popup and searching in the search field the query parameters defining it as a selector popup is lost and you cannot pick any of the search results.
