### ISSUE TITLE
Support for responsive layout

### ISSUE THREAD

**Issue by paulocoutinhox** [unfoldadmin/django-unfold#315]
Hi,

Can you add support for responsive layout?

It don't work for tablet/smartphone, because while you make the browser smaller it is not responsive:

https://github.com/unfoldadmin/django-unfold/assets/395096/eaa5b7a7-1727-4b9d-837c-a8579a31878a

**Comment by lukasvinclav** [comment]
@paulocoutinhox I already saw this problem in the past and I was not able to fix it. In general, when you refresh the page, charts are okay. But when you make the window width smaller, charts are not scaling accordingly. Vise versa, when enlarging window width, it behaves okay. Maybe you can help me debugging this problem and submitting PR?

**Comment by summerthe** [comment]
@paulocoutinhox @lukasvinclav this issue is from chart.js, check below comment, there is jfiddle provided with problem and solution. 

[https://github.com/chartjs/Chart.js/issues/4156#issuecomment-295180128](https://github.com/chartjs/Chart.js/issues/4156#issuecomment-295180128)

**Comment by lukasvinclav** [comment]
@summerthe thanks for pointing me at the right direction. I had to put min-w-0 class on flex container #363
