### ISSUE TITLE
How to add captcha for unfoldadmin?

### ISSUE THREAD

**Issue by intp1** [unfoldadmin/django-unfold#317]
Is there an easy way to integrate captcha such as 'django-simple-captcha'、‘django-multi-captcha-admin’ into unfold?
or, is there a native captcha implement comes with unfold?

**Comment by summerthe** [comment]
@intp1 django-multi-captcha-admin should work with unfold without explicit integration, [recaptcha2](https://github.com/kbytesys/django-recaptcha2) and [recaptcha](https://github.com/praekelt/django-recaptcha) might work, but for [simple captcha](https://github.com/mbi/django-simple-captcha) there might need some work for input only.
