### ISSUE TITLE
Sidebar issue Mobile (RTL Structure)

### ISSUE THREAD

**Issue by fadi-rezek-salloum** [unfoldadmin/django-unfold#324]
Hello. There is a problem with the design responsiveness with the new IPhone 15. The sidebar is showing in the middle of the screen like shown in the images. Can you please fix it

![1](https://github.com/unfoldadmin/django-unfold/assets/78537399/5efb79ce-3f6c-4510-8d66-aa45351166e3)
![2](https://github.com/unfoldadmin/django-unfold/assets/78537399/edef035d-d6b9-42c8-940b-1c9e6cc03b41)
![3](https://github.com/unfoldadmin/django-unfold/assets/78537399/db832720-65c1-4a3d-8c41-bf7654a2ed6b)

**Comment by fadi-rezek-salloum** [comment]
When the mobile's language is Arabic (the website is not translated -- only in Engilsh) , this issue is happening in the entire design

**Comment by lukasvinclav** [comment]
We have a ticket #78 for RTL integration.
