### ISSUE TITLE
Don't works fields (style)

### ISSUE THREAD

**Issue by alechries** [unfoldadmin/django-unfold#325]
<img width="420" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/51765464/972a2c83-6c7f-4551-92f2-784a54049bf0">

I've updated the cache, whatever I've done, but I still get broken fields like this. The same goes for the date selection, there is also a broken field there

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
]

**Comment by rextea** [comment]
You need to declare your admin models in admins.py to make it work, e.g:
`from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import User

from unfold.admin import ModelAdmin

admin.site.unregister(User)


@admin.register(User)
class UserAdmin(BaseUserAdmin, ModelAdmin):
    pass`

**Comment by lukasvinclav** [comment]
Each model has to inherit from `unfold.admin.ModelAdmin`

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#installation
