### ISSUE TITLE
Adjust Auto Complete width in TabularInline

### ISSUE THREAD

**Issue by afsangujarati93** [unfoldadmin/django-unfold#327]
I have a Tabular inline and when I add autocomplete on one of the field (location), it reduces the size of the field and the search box overflows out of the dropdown 

SS with autocomplete on the location field 

<img width="1072" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/32711400/502aa070-57a9-418e-b02a-cb5c035bda63">

SS without autocomplete on the location field (normal select)
<img width="1071" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/32711400/6e20f395-c6cb-4d31-b9dc-fa79df4e0d74">

Is there a way to fix this using the code or it needs to be fixed in unfold itself?

**Comment by justinqian42** [comment]
This is the same to https://github.com/unfoldadmin/django-unfold/issues/267
