### ISSUE TITLE
Customize widget accross the admin

### ISSUE THREAD

**Issue by eliu-fracta** [unfoldadmin/django-unfold#330]
![image](https://github.com/unfoldadmin/django-unfold/assets/109644973/707a4eb8-86fe-44c6-a954-b2fff4378211)

As the screenshot indicates, the default input widget lacks a border. How can I customize the default input across the admin interface?

**Comment by lukasvinclav** [comment]
Please provide minimal example how to replicate this issue. I need to see widget class.

**Comment by eliu-fracta** [comment]
so it turns out that I can just customize the style by adding a style.css as the documentation described.

```
input[type="text"],
input[type="number"],
input[type="tel"],
input[type="date"],
input[type="email"] {
  border-width: 0.1em;
  padding: 0.5em;
  border-radius: 0.5em;
}
```
