### ISSUE TITLE
ManytoManyfield Widget Bug

### ISSUE THREAD

**Issue by lamchun1110** [unfoldadmin/django-unfold#332]
I'm new to django unfold and I'm doing some research that unfold seems to have default autocomplete but I don't know how to implement it.
Since the default seems to bug with unfold.
![image](https://github.com/unfoldadmin/django-unfold/assets/20940758/2b928ce5-6d84-457d-bf29-256be9f1d1eb)
There is no scrollbar and no autocomplete.

I need to integrate the widget from django-select2 to come over this problem.
![image](https://github.com/unfoldadmin/django-unfold/assets/20940758/08b0479f-3c5b-401b-b4ef-c4ac0c5d180e)

**Comment by justinqian42** [comment]
@admin.register(YourModel)
class YourModelAdmin(ModelAdmin):

    autocomplete_fields = [
        "your_field",
    ]
