### ISSUE TITLE
Using Select field in changelist filters

### ISSUE THREAD

**Issue by jdenisTLM** [unfoldadmin/django-unfold#344]
It could be a very good improvement to re-use the select form widget, already in admin forms.

I've tried several things to achieve this goal, but it is not satisfying enough for now. If somone has already done this, or have somes clues to let us make it the more clever way to implement it with unfold ... 

Thanx !

**Comment by lamchun1110** [comment]
Is it possible to use the dropdown menu to select as the filter like Jazzmin?

![image](https://github.com/unfoldadmin/django-unfold/assets/20940758/ffea2eba-cf45-48cf-b84b-4b027d7d48e3)

**Comment by PavelPancocha** [comment]
This: https://github.com/francoborrelli/django-unfold-admin-list-filter-dropdown/tree/master by @francoborrelli goes one step.

**Comment by PavelPancocha** [comment]
The abilitity to filter by typing would be great

**Comment by jdenisTLM** [comment]
@PavelPancocha this is a good beginning. The use of autocomplete field would be an amazing feature, to get filter for large relations !

**Comment by PavelPancocha** [comment]
> @PavelPancocha this is a good beginning. The use of autocomplete field would be an amazing feature, to get filter for large relations !

I tried quickly integrate it, but failed. I will need to solve this in coming weeks.

**Comment by lukasvinclav** [comment]
Already implemented in Unfold. Check the docs for more info.

**Comment by PavelPancocha** [comment]
@lukasvinclav sorry, I wanted something like this:

![image](https://github.com/unfoldadmin/django-unfold/assets/30392053/172024ef-a3a2-4173-974a-8ac3e06f524f)

"Type to filter"

What I found in Unfold is just simple "dropdown":
![Snímek obrazovky pořízený 2024-05-29 13-28-01](https://github.com/unfoldadmin/django-unfold/assets/30392053/2ec9bb28-b456-4258-bade-2d310109aba7)


Or do I miss something?

Thanks!

@jdenisTLM You are talking about the same thing as me, right?

**Comment by jdenisTLM** [comment]
Yes, exactly ! This is a common situation to have large lists, and, for performance and comfort reason, this would be a great improvment to have an autocomplete filter :+1:

**Comment by lukasvinclav** [comment]
do you have any examples of dropdown filter with autocomplete?

**Comment by PavelPancocha** [comment]
Its pretty simple in the end, based on metioned package above:

filter template:

```
{% load i18n %}
<div class="mb-6 relative">
  <script type="text/javascript">
    var go_from_select = function(opt) { window.location = window.location.pathname + opt };
    $(document).ready(function() {
      console.log('select2-enable');
      $('.select2-enable').select2({
        minimumResultsForSearch: 3,     });
    });
  </script>
  <h3 class="font-medium mb-2 text-gray-700 text-sm dark:text-gray-200">
    {% blocktrans with title as filter_title %} By {{ filter_title }} {% endblocktrans %}
  </h3>
  <label>
    <select class="select2-enable border bg-gray-800 text-white rounded-md shadow-sm text-sm focus:ring focus:ring-primary-500 focus:border-primary-500 w-full max-w-xs dark:bg-gray-800 dark:border-gray-600 dark:focus:border-primary-500"
            onchange="go_from_select(this.options[this.selectedIndex].value)" style="width: 100%; appearance: none;">
      {% for choice in choices %}
        <option value="{{ choice.query_string|iriencode }}" {% if choice.selected %} selected="selected" {% endif %}>
          {{ choice.display }}
        </option>
      {% endfor %}
    </select>
  </label>

</div>

```

**Comment by PavelPancocha** [comment]
@jdenisTLM Would you welcome some package for this? If this gets at least 2 likes, I will do it :)
