### ISSUE TITLE
input, text area css not working

### ISSUE THREAD

**Issue by mundo88** [unfoldadmin/django-unfold#345]
![image](https://github.com/unfoldadmin/django-unfold/assets/65348951/366a3121-0bee-4dd5-9741-7ed925d003de)
![image](https://github.com/unfoldadmin/django-unfold/assets/65348951/eef8af6f-a186-49a1-ac80-676167b0709f)

**Comment by lukasvinclav** [comment]
Plase make sure your admin classes are inheriting from `unfold.admin.ModelAdmin`.
