### ISSUE TITLE
Change Form Label's Font Size

### ISSUE THREAD

**Issue by eliu-fracta** [unfoldadmin/django-unfold#347]
In the admin change form, is there a way to customize the font size of a field's label? For example, how can I increase the font size of the "name" label shown in the image below?

![image](https://github.com/unfoldadmin/django-unfold/assets/109644973/d7487545-a5ca-4d33-8446-e1951965e412)

**Comment by lukasvinclav** [comment]
You can add your own CSS styles:

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#adding-custom-styles-and-scripts

**Comment by eliu-fracta** [comment]
I end up overwrite the label_tag here
https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/admin.py#L141
