### ISSUE TITLE
Problem with Unfold sidebar permissions

### ISSUE THREAD

**Issue by jverdasca** [unfoldadmin/django-unfold#350]
When logging in with a user with fewer permissions, the sidebar items disappear and when logging in with a user with more permissions, these items are not reset, that is, the items shown in the sidebar to the user with more permissions remain the same as those shown to the user with fewer permissions.

The problem is that the way unfold handles permissions changes the settings dictionary defined in the Django settings in the UNFOLD variable.

The problem occurs [here](https://github.com/unfoldadmin/django-unfold/blob/97c2e32bb2982058f7c581801056bf8eb58d82d3/src/unfold/sites.py#L220) and the Django settings are changed [here](https://github.com/unfoldadmin/django-unfold/blob/97c2e32bb2982058f7c581801056bf8eb58d82d3/src/unfold/sites.py#L275), thus changing the UNFOLD settings variable due to the reference in navigation variable. A solution to this problem is to use deepcopy from Python's copy module (documentation [here](https://docs.python.org/3/library/copy.html#copy.deepcopy)), which ensures that settings.UNFOLD remains in its original state and navigation variable contains a copy of UNFOLD setting.

Using deepcopy as I demonstrate below solves the problem described

![imagem](https://github.com/unfoldadmin/django-unfold/assets/73713137/073e92bc-d88c-498f-b210-51a0dcccbb1c)

Edit:
I am using the SIDEBAR settings the same way as described in [here](https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#available-settingspy-options)

**Comment by summerthe** [comment]
@jverdasca you are probably using old unfold version. This issue has been fixed in some of the recent release

**Comment by lukasvinclav** [comment]
Yes, this one is supposed to be fixed. I'm closing this issue.
