### ISSUE TITLE
Searchbox overflow issue in Tabular Inline Form

### ISSUE THREAD

**Issue by afsangujarati93** [unfoldadmin/django-unfold#353]
I have an inline form with an autocomplete field. However, I have noticed that due to the number of fields in the tabular inline form, the autocomplete search box does not fit into the width of the dropdown. 
<img width="935" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/32711400/5a772875-0a62-4ad1-8138-e8b23d6fc991">

is there an option to 
1. Fix this so that the width of the search box is same as the width of the dropdown
2. Adjust the width of the individual columns/fields in the inline form so that the autocomplete filed has more room

**Comment by lukasvinclav** [comment]
Fixed #364
