### ISSUE TITLE
unfold.contrib.import_export stopped working.

### ISSUE THREAD

**Issue by lahuindai** [unfoldadmin/django-unfold#372]
> File "/home/ggreyling/projects/digichemplus-server/.venv/lib/python3.12/site-packages/import_export/admin.py", line 876, in export_admin_action
>     form = form_type(
>            ^^^^^^^^^^
>   File "/home/ggreyling/projects/digichemplus-server/.venv/lib/python3.12/site-packages/unfold/contrib/import_export/forms.py", line 16, in __init__
>     self.fields["file_format"].widget.attrs["class"] = " ".join(SELECT_CLASSES)
>     ~~~~~~~~~~~^^^^^^^^^^^^^^^
> KeyError: 'file_format'

**Comment by lukasvinclav** [comment]
I just tested export functionality and it seems it works. Do you have any additional information how it is possible to reproduce the issue?

**Comment by ZairMahmood** [comment]
Looking at the latest release docs, input_format was moved thus causing a break:
https://django-import-export.readthedocs.io/en/stable/release_notes.html#import-export-forms-importexportformbase

**Comment by TheAbhijeet** [comment]
A temporary solution for now will be downgrading import-export to [3.3.9](https://github.com/django-import-export/django-import-export/releases/tag/3.3.9)

**Comment by lukasvinclav** [comment]
Fixed in #398
