### ISSUE TITLE
ManyToMany form field is not scrollable

### ISSUE THREAD

**Issue by Ashinsk** [unfoldadmin/django-unfold#376]
The manytomany form in the admin panel is not scrollable particularly in the case of permission field in the Group model of django auth app.

**Comment by lukasvinclav** [comment]
Fixed #421

**Comment by SandyRogers** [comment]
I believe this issue has reappeared due to a regression change in https://github.com/unfoldadmin/django-unfold/pull/1328/files#diff-fd0386494b845f20f3ac55040d54586924c7920cf097c8036c924008fc62bb31

**Comment by lukasvinclav** [comment]
@SandyRogers please create new ticket and fill out all questions. PS: I did quick test and demo site work (see "Permissions").

https://demo.unfoldadmin.com/en/admin/formula/user/1/change/
