### ISSUE TITLE
Django authorisation accounts/password_change working, but accounts/password_reset not.

### ISSUE THREAD

**Issue by William-Wildridge** [unfoldadmin/django-unfold#384]
I note that: 

accounts/password_change has the expected unfold style:
![image](https://github.com/unfoldadmin/django-unfold/assets/8853591/39cebe46-fae1-4423-bbdc-910206b14c23)

But accounts/password_reset doesn't, looking into the html it seems that no tailwind styling is added like the reset view:
![image](https://github.com/unfoldadmin/django-unfold/assets/8853591/a768c0b0-0484-4ab4-8705-ffae1d7209d5)

Just the basic reset password form is included, but it renders with limited usability:
```
<html>
<body>
<!--StartFragment-->
<form method="post"><input type="hidden" name="csrfmiddlewaretoken" value="SECRET">
--
  | <fieldset class="module aligned">
  | <div class="form-row field-email">
  |  
  | <label for="id_email">Email address:</label>
  | <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
  | </div>
  | <input type="submit" value="Reset my password">
  | </fieldset>
  | </form>

<!--EndFragment-->
</body>
</html>
```

On a white themed background (the default non-l;ogged in experience), this has almost no usability.

**Comment by andrew-gardener** [comment]
To add to this, it would be nice if this by default override the `registration/password_reset_form`, `registration/password_reset_confirm`, `registration/password_reset_confirm`, and `registration/password_change_form` templates used by `django.contrib.auth.views`'s `PasswordResetView`, `PasswordResetDoneView`, `PasswordResetConfirmView`, and `PasswordResetCompleteView` views

**Comment by lukasvinclav** [comment]
These are two different problems:

1. The change password form needs to be overriden by the form provided in Unfold where all CSS classes are overridden. In README you can find docs: https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#user-admin-form

2. The second problem is password reset form. This form is class based view which lives outside of admin thus does not have an access to the Unfold's admin site which holds for example admin colors so I can not style it properly. Here the recommendation is to style these pages in your own project so they will match your FE visual. In #541 I fixed the button on the login form.

Regarding the password reset form and proper styles, new view mixin would be required which will expose some UNFOLD settings like color combination and overriden form with proper classes. But this is out the scope right now and not in roadmap.
