### ISSUE TITLE
Import/Export field not displaying well.

### ISSUE THREAD

**Issue by edmundrotimi** [unfoldadmin/django-unfold#385]
Thanks for this amazing admin template theme. I encountered an issue with the display of my import/export field. The drop-down menu is not formatted well. I am using Django 4.2 and have added a snapshot of my admin.py below. I will appreciate a pointer on what I am doing wrong.

    from import_export import resources
    from import_export.admin import ImportExportModelAdmin
    from unfold.admin import ModelAdmin
    

    class CustomResource(resources.ModelResource):
    
        class Meta:
            model = MyModel
            skip_unchanged = True
            report_skipped = True
            exclude = [...]
            import_id_fields = [...]
            export_id_fields = [...]
    
    
    class TestAdmin(ModelAdmin, ImportExportModelAdmin):
        resource_class = CustomResource
        ...
        ...

![Screenshot 2024-05-14 111241](https://github.com/unfoldadmin/django-unfold/assets/48602906/1879e1cb-0c1c-4033-bbed-158169771c8a)

**Comment by lukasvinclav** [comment]
You are missing second step from the link below (`import_form_class` and `export_form_class`)

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#django-import-export

**Comment by mcfriend99** [comment]
I do have the classes and it still doesn't work. Any help??
