### ISSUE TITLE
Custom User Change Password Form Issue

### ISSUE THREAD

**Issue by workshop22** [unfoldadmin/django-unfold#392]
I've created a basic project to test the possibility of using Unfold. All I've done is create an app called Users and set up a CustomUser model but I'm getting 302 errors when trying to navigate to the change password form:

[18/May/2024 10:01:33] "GET /admin/users/customuser/1/password/ HTTP/1.1" 302 0
[18/May/2024 10:01:33] "GET /admin/users/customuser/1/password/change/ HTTP/1.1" 302 0

The change password form works fine if I'm not using a custom user model or if I'm not using Unfold. I'm not sure how to go about fixing the problem.

The object being passed seems to be incorrect attaching /password to it

>>> print(resolve('/admin/users/customuser/1/password/'))
ResolverMatch(func=django.views.generic.base.RedirectView, args=(), kwargs={'object_id': '1/password'}, url_name=None, app_names=['admin'], namespaces=['admin'], route='admin/users/customuser/<path:object_id>/', captured_kwargs={'object_id': '1/password'})

>>> print(resolve('/admin/users/customuser/1/password/change/'))
ResolverMatch(func=django.contrib.admin.options.change_view, args=(), kwargs={'object_id': '1/password'}, url_name='users_customuser_change', app_names=['admin'], namespaces=['admin'], route='admin/users/customuser/<path:object_id>/change/', captured_kwargs={'object_id': '1/password'})

As far as I know, I am properly importing from Unfold as stated in the documentation.

Any help would be much appreciated.

**Comment by dacodekid** [comment]
> Raw passwords are not stored, so there is no way to see this user’s password, but you can change the password using [this form]).

I actually came here open a new issue, as I don't see the above help message in the admin (tested on both 0.22 & 0.23 ). Let me try recreate a sample project and see if it is an issue on my end.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/115b50d6-2ae0-4c61-896e-00dd1be59df3)

**Comment by workshop22** [comment]
I finally found a fix. I solved the problem by doing this:

class CustomUserAdmin(UserAdmin, ModelAdmin):

Adding UserAdmin fixed the issue.

**Comment by workshop22** [comment]
I finally found a fix. I solved the problem by doing this:

class CustomUserAdmin(UserAdmin, ModelAdmin):

Adding UserAdmin fixed the issue.
