### ISSUE TITLE
Multiple Admin Error

### ISSUE THREAD

**Issue by edmundrotimi** [unfoldadmin/django-unfold#394]
I encountered a 'Reverse for 'toggle_sidebar' not found. 'toggle_sidebar' is not a valid view function or pattern name.' after creating multiple admins.

      from django.contrib.admin import AdminSite
      
      class StaffAdminSite(AdminSite):
          site_header = 'admin'
      
      staffadmin = StaffAdminSite(name='staffadmin')

      urlpatterns = [
          path('admin/', admin.site.urls),
          path('staff/', staffadmin.urls),
      ]

**Comment by lukasvinclav** [comment]
Do you have `unfold.apps.BasicAppConfig` in installed apps?

**Comment by edmundrotimi** [comment]
Thanks for the reply.  Adding _unfold.apps.BasicAppConfig_ in installed apps gives an error.

**Comment by lukasvinclav** [comment]
Which version of Unfold are you using? If you are on the most recent version and still having the issue please create a repo where it is possible to reproduce the issue.

**Comment by edmundrotimi** [comment]
@lukasvinclav  I upgraded from 0.22 to 0.23. Adding _unfold.apps.BasicAppConfig_  gives _Application labels aren't unique, duplicates: unfold_.

**Comment by edmundrotimi** [comment]
@lukasvinclav thanks again for the response. I have replicated it here: https://github.com/edmundrotimi/replica. The error should show when you login via the staff.

**Comment by lukasvinclav** [comment]
Here is the guide how to integrate this feature: https://unfoldadmin.com/blog/migrating-django-admin-unfold/

I noticed, that you have wrong first line in INSTALLED_APPS. It has to be `unfold.apps.BasicAppConfig`, not only `unfold`. Everything is explained in article.

**Comment by edmundrotimi** [comment]
@lukasvinclav Thanks for the response and help. The error has been fixed.
