### ISSUE TITLE
autocomplete based on another field

### ISSUE THREAD

**Issue by nicokant** [unfoldadmin/django-unfold#400]
Is it possible to filter the autocomplete based on another field?

**Comment by lukasvinclav** [comment]
Sorry but I'm not sure what you want to autocomplete.

**Comment by nicokant** [comment]
My description was too short, let me add some context:

I have a model with two foreign keys. Based on the choice of the first foreign key, the second one should be filtered. Typical example: Nation / Region / City.

Thank you for your very fast answer :)

**Comment by lukasvinclav** [comment]
Unfortunately, this is not supported.
