### ISSUE TITLE
Project level Tailwind stylesheet override causing dark coloring issues on mac. 

### ISSUE THREAD

**Issue by Ajaysainisd** [unfoldadmin/django-unfold#406]
i am trying to add custom pages with custom styling. but when i use custom stylesheet few elements are become dark when theme is set to light. 
<img width="1440" alt="Screenshot 2024-05-24 at 1 04 23 PM" src="https://github.com/unfoldadmin/django-unfold/assets/36501961/905810d9-d052-48ed-9296-4c4bb2643040">

But this issue is not arising in ubuntu, i am only experiencing this in macOS. 
I have the tailwind version 3.4.0

**Comment by lukasvinclav** [comment]
Do you have an example repository where I can reproduce the issue?
