### ISSUE TITLE
How to donate?

### ISSUE THREAD

**Issue by xtwist** [unfoldadmin/django-unfold#407]
I've been waiting for this template for years. I'd really like to say thank you in a more concrete way. 
Please add your Paypal and crypto to README as I hope I'm not alone. 

Cheers!

**Comment by lukasvinclav** [comment]
Hey, thank you very much for kind words. It means a lot for me that there are people who are willing to financially support Unfold. To be honest, the only way right now how to support Unfold is using the contact form on the unfoldadmin.com and ordering a custom work.
