### ISSUE TITLE
Fixed filter in UI

### ISSUE THREAD

**Issue by aasimmk** [unfoldadmin/django-unfold#413]
First of all, many thanks for making this theme. This is so far the best theme I have seen for Django admin.

Issue:
Is there a way to make filter on sidebar fixed in UI instead "click and reveal" behaviour? 

I use it frequently, and clicking and selecting multiple filters can be annoying. It becomes useful when you have more fields to display on the admin list page. You can move boolean fields to the sidebar for quick filtering instead of displaying them in the list.

**Comment by lukasvinclav** [comment]
I know what you mean, I was already thinking about it. This task would require big template (UI & code) overhaul and introduction of new flag in `ModelAdmin` to switch between different layouts.

**Comment by tanmay031** [comment]
I am wondering if there any flag has been added to show fixed filter sidebar??

**Comment by lukasvinclav** [comment]
@tanmay031 https://unfoldadmin.com/docs/configuration/modeladmin/ check `list_filter_sheet`

**Comment by tanmay031** [comment]
Thank you very much i just found it 
list_filter_sheet = False 
works for me
