### ISSUE TITLE
Export Data isn't working anymore

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#418]
after last update when i try to export the data I am getting this error 
<img width="1140" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/f153b2d3-160b-46b5-8ed8-f5c28985a160">

code:
from unfold.contrib.import_export.admin import ExportActionModelAdmin
class CustomerAdmin(ModelAdmin, ExportActionModelAdmin):
pass

**Comment by lukasvinclav** [comment]
Fixed in #420
