### ISSUE TITLE
FilteredSelectMultiple Error

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#426]
double clicks on the FilteredSelectMultiple item stopped working I have to use the arrow instead.
<img width="734" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/d52bb5bc-4075-4110-b1a3-b60ade0e64d8">

**Comment by lukasvinclav** [comment]
Tested on demo site and it works. Would you mind to create a minimal repo where I can reproduce the issue?

https://demo.unfoldadmin.com/admin/formula/user/1/change/

**Comment by omargawdat** [comment]
It still doesn't work i think the issue in chrome itself because I tried it in safari it works fine. 
https://github.com/unfoldadmin/django-unfold/assets/53629777/0cabe853-fa34-4bd3-9749-66709c7353f0
