### ISSUE TITLE
Add support for django-admin-sortable2

### ISSUE THREAD

**Issue by twFroggen** [unfoldadmin/django-unfold#427]
First and foremost, I would like to extend my gratitude for developing such an impressive admin panel—it has significantly enhanced our administrative capabilities.

I am writing to report a compatibility issue I encountered with the Django Admin Sortable2 when integrated with the Unfold admin interface. It seems that the styles and action buttons from Sortable2 do not align well with the Unfold design.

I am not sure if this has been highlighted by others, but it would be incredibly beneficial for our operations if these components could be made fully compatible.

![SCR-20240531-pcwh](https://github.com/unfoldadmin/django-unfold/assets/138838525/510f6d3e-6d6c-4e19-a803-7725d7b2bb35)

Could you please consider enhancing the compatibility between these tools in your future updates? Any assistance or guidance in this matter would be greatly appreciated.

Thank you for your attention to this matter. Looking forward to your favorable response.

Best regards,
Froggen

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/

**Comment by twFroggen** [comment]
@lukasvinclav  Do I have the opportunity to contribute as a developer to assist with integration?

**Comment by lukasvinclav** [comment]
Nobody can forbid you doing that. I suggest you creating third party app integrating this support so you can have full control.
