### ISSUE TITLE
FileField Support

### ISSUE THREAD

**Issue by workshop22** [unfoldadmin/django-unfold#429]
Awesome work with this! Would you happen to have any plans to support models.FileField?

It'd be great if FileField would look the same as ImageField.

**Comment by workshop22** [comment]
> ```
> class UnfoldAdminFileFieldWidget(FileFieldMixin, AdminFileWidget):
>     template_name = "unfold/widgets/clearable_file_input_small.html"
> ```
> 
> =>
> 
> ```
> class UnfoldAdminFileFieldWidget(FileFieldMixin, AdminFileWidget):
>     template_name = "unfold/widgets/clearable_file_input.html"
> ```

I still have much to learn in Django, but this helped me a lot, thanks so much!

**Comment by omargawdat** [comment]
can you help me how can i access the uploaded folder as I can only see his path without being able to see the doc itself 
<img width="779" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/9a89e396-beb8-4886-8235-c2c253fe3ad5">
