### ISSUE TITLE
File upload Style broken?

### ISSUE THREAD

**Issue by PaulleDemon** [unfoldadmin/django-unfold#430]
Hi, I recently upgraded from 0.22.0 to 0.25.0 I noticed that the file upload was quite different from the previous version. The previous version matched the theme more. Was this done on purpose or accidentally broken?

0.22.0 (previous version)
![latest2](https://github.com/unfoldadmin/django-unfold/assets/64060109/2a28cabb-cfca-4f1f-af41-13b786793ba6)

0.25.0 (current version)
![latest](https://github.com/unfoldadmin/django-unfold/assets/64060109/2baea806-c74b-47b8-bb80-fc2224b83431)

**Comment by lukasvinclav** [comment]
I just tested locally and it worked. It works on demo site as well. Would you mind to create a minimal repo where I can reproduce the issue?

https://demo.unfoldadmin.com/admin/formula/driver/56/change/

**Comment by PaulleDemon** [comment]
@lukasvinclav I think it works fine for ImageField, but Filefield doesn't work. Maybe the FileField was removed from here? https://github.com/unfoldadmin/django-unfold/blob/e482ae135e7a578b8ea14da7c52218e976dcf576/src/unfold/admin.py#L94


The file field works perfectly for versions 0.21.0 and 0.22.0, but doesn't work for 0.23.0 and above. Let me know if this is the issue, or I'll try to dig deeper.

**Comment by lukasvinclav** [comment]
You are right. Would you mind to test #432?

**Comment by PaulleDemon** [comment]
@lukasvinclav It works!

![image](https://github.com/unfoldadmin/django-unfold/assets/64060109/1102cc68-daeb-453c-80e0-53a7c553b58e)

**Comment by omargawdat** [comment]
> @lukasvinclav It works, thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/64060109/335855340-1102cc68-daeb-453c-80e0-53a7c553b58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDQ5NjUsIm5iZiI6MTcxOTg0NDY2NSwicGF0aCI6Ii82NDA2MDEwOS8zMzU4NTUzNDAtMTEwMmNjNjgtZGFlYi00NTNjLTgwZTAtNTNhN2M1NTNiNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE0Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MzRlOTdjMjZlMTJkYTgyZDYyMjk2YjViYTU3MWZiOWI4YzE3YjkyMThhMzBkMzkzOTdhYWQyNzM2ODIzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.crB1dRTd7XgTPJIyEuzSpPwm3KUOZIxZpLLIdaWfY5E)

how can you download the file from the admin?

**Comment by PaulleDemon** [comment]
@omargawdat 

You can't directly click on the file menu, so I created another link field and added it to admin, Now if I click on this I am able to view the file in a different tab.

```py

 # in admin.py
def file_link(self, obj):
    if obj.file:
        return mark_safe(f"<a href='{obj.file.url}' style='color: #3884ff;' target='_blank' rel='noopener'>{obj.resume.url.split('/')[-1]}</a>")
    else:
        return "No attachment"
```

**Comment by omargawdat** [comment]
The Problem that I am facing is that I have a model for documentation which contains 9 files so it will be impractical to do extra 9 fields for showing the links it would be great if there is an option for making the field clickable or something
