### ISSUE TITLE
Import Form is not selecting the `format type` based on file extension

### ISSUE THREAD

**Issue by dacodekid** [unfoldadmin/django-unfold#435]
The `django-import-export` form would [automatically select](https://github.com/django-import-export/django-import-export/blob/main/import_export/static/import_export/guess_format.js) the `Format` dropdown [based on the file type](https://github.com/django-import-export/django-import-export/blob/796deb8c2c11e75c1922215b8d97ad60ec308f9d/import_export/forms.py#L79) (in this case,  it would select CSV), but using `unfold`, I have to manually select it.

<img width="732" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/10047844/1ef5348c-76d4-4e23-bedd-cee035550268">

**Comment by lukasvinclav** [comment]
Fixed #466
