### ISSUE TITLE
Unfold filters not playing nice with standard django ones

### ISSUE THREAD

**Issue by muhammedabad** [unfoldadmin/django-unfold#438]
In my admin class definition:

```python
  list_filter_submit = True  # Submit button at the bottom of the filter
  list_filter = (
      ("date_created", RangeDateFilter), 
      "event_code",
      "event_name",
  )
```

So there are 2 "link" filters - `event_code` and `event_name`. These work fine together as well as individually until you combine them with the unfold date filter. Once the submit button is hit, the values for the event code and event name filters are changes to the first character of their actual values, which ends up returning no results.

For example:

`auditlog/?event_code=WEB_001` - Works fine
`auditlog?event_code=WEB_001&event_name=Service+Activated` - Works fine

But when I specify a date from value, the event_code and event_name values are reduced to their first character only.

`auditlog/?date_created_from=2024-06-01&date_created_to=&event_code=W&event_name=S`

**Comment by lukasvinclav** [comment]
I tested this functionality multiple times and it worked without any issues. Would you mind to try to replicate the issue with the most recent version of Unfold? Here is the the demo site with the date filters and it works:

https://demo.unfoldadmin.com/admin/formula/race/
