### ISSUE TITLE
Fieldsets as tabs

### ISSUE THREAD

**Issue by minholi** [unfoldadmin/django-unfold#44]
Is there any way to show fieldsets as tabs? Actually I'm using django-suit and looking for alternatives.

**Comment by lukasvinclav** [comment]
Good point. Added into TODO.

**Comment by vade** [comment]
Thanks for this theme, it's awesome. FWIW, I second this!

**Comment by lukasvinclav** [comment]
@vade @minholi tab support implemented in #249

**Comment by juanfcocontreras** [comment]
I see that the issue is closed, but the Pull request is not integrated in the project and does not appear in the release that came out yesterday, right?

Wouldn't it be better to leave it open until the pull request is accepted?

**Comment by vage-mel** [comment]
how stacked inline add to tab?
