### ISSUE TITLE
"length_is" template filter has been deprecated

### ISSUE THREAD

**Issue by raminf** [unfoldadmin/django-unfold#440]
https://docs.djangoproject.com/en/dev/releases/5.1/#:~:text=The%20length_is%20template%20filter%20is%20removed

The `length_is` template filter was deprecated in Django 4.2 and removed in 5.1.

Installing django-unfold with Django 5.1 and Python 3.12 breaks admin and drilling down into individual items:

```
TemplateSyntaxError at /admin/accounts/customuser/e3c6be05-6020-4155-9ce5-35eb000a5b8b/change/
Invalid filter: 'length_is'
...
lib/python3.12/site-packages/unfold/templates/admin/includes/fieldset.html, error at line 18

```

**Comment by lukasvinclav** [comment]
Fixed #442
