### ISSUE TITLE
Howto resize input and date fields in django-admin - make them shorter

### ISSUE THREAD

**Issue by pborut** [unfoldadmin/django-unfold#449]
I like django-unfold very much, but I need also control of widgets size on admin forms. Existing widgets are taking lot of space on form. What is correct way to make TextInput widget smaller - shorter. Same question is for DateInput widget.  
Can you please suggest me?

**Comment by lukasvinclav** [comment]
You can write your own CSS to change the styles. In docs you can find an example how to load custom CSS files.
