### ISSUE TITLE
StackedInline no space between records

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#452]
the separation between the inlines was better now when they were so close to each other it was hard to distinguish between them
<img width="1080" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/f95d3a9b-2860-49f9-a66b-00042ad23bb5">

**Comment by lukasvinclav** [comment]
Thanks for feedback but that was long standing UI issue (double boxed layout) which is fixed right now. If you want, you can always apply your own CSS styles to change the visual.
