### ISSUE TITLE
WysiwygWidget Headers Not working 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#454]
in the widget when I try to make headers for the test it doesn't work as expected. 

https://github.com/unfoldadmin/django-unfold/assets/53629777/9315dc47-242d-48fd-9d14-f6d50be0846f

**Comment by dacodekid** [comment]
<img width="992" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/10047844/f74de106-71c9-4b17-854f-f884f5ebf546">

It works for me.  May be something to do with RTL?

**Comment by omargawdat** [comment]
oh thanks i got the reason for the error it was using wrong tags using the fixtures, but I have noticed that even clearing all the text keep some tags saved which could lead for saving empty field while its required in addition it didn't removed the wrong tags. 
<img width="266" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/446238d9-3f42-42d9-8c6b-944a46707318">
<img width="934" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/765b865a-882b-44b2-a230-7074226289eb">
