### ISSUE TITLE
Recent actions icons are missing/not showing

### ISSUE THREAD

**Issue by MuhammedNihad** [unfoldadmin/django-unfold#455]
No icons are rendered in the `Recent Actions` section. Is this by design?
Default admin renders icons for add, edit, and delete.

_Unfold version = 0.26.0_

**Unfold recent actions:**

![Screenshot 2024-06-07 154319](https://github.com/unfoldadmin/django-unfold/assets/33249669/6413d110-82b8-41c0-9cc3-b84fa7d1a184)

**Django default icons of recent actions:**

![image](https://github.com/unfoldadmin/django-unfold/assets/33249669/d633beb4-1225-4744-8ada-7437492602e9)

**Comment by lukasvinclav** [comment]
Yes, this is by design.

**Comment by MuhammedNihad** [comment]
Can we add something to distinguish which CRUD operation was done? I'm happy to help with this.
