### ISSUE TITLE
Incomplete display of actions_row in Django Admin when there's only one record

### ISSUE THREAD

**Issue by etherfurnace** [unfoldadmin/django-unfold#459]
![image](https://github.com/unfoldadmin/django-unfold/assets/81210463/5a080ed3-a95a-484a-8a4f-66718aa4b03e)

I am using the actions_row attribute in Django Unfold Admin to add specific actions to each row. However, when there's only one record, the actions_row is not fully displayed.

Here's my code snippet:

@admin.register(KnowledgeBaseFolder)
class KnowledgeBaseFolderAdmin(ModelAdmin):

    list_display = ['name', 'description', 'embed_model_link',
                    'enable_text_search', 'enable_vector_search',
                    'train_status', 'train_progress']
    search_fields = ['name']
    list_display_links = ['name']
    ordering = ['id']
    filter_horizontal = []
    actions_row = ['train_embed']
    inlines = [KnowledgeStackedInline]
    readonly_fields = ['train_status']
    save_as = True

    fieldsets = (
        ('Basic Information', {
            'fields': ('name', 'description')
        }),
        ('Embedding Model', {
            'fields': ('embed_model',)
        }),
        ('Chunk Parsing', {
            'fields': ('enable_general_parse', ('general_parse_chunk_size', 'general_parse_chunk_overlap'))
        }),

        ('Text Search', {
            'fields': ('enable_text_search', 'text_search_weight')
        }),

        ('Vector Search', {
            'fields': ('enable_vector_search', 'vector_search_weight', 'rag_k', 'rag_num_candidates')
        }),
        ('Result Re-ranking', {
            'fields': ('enable_rerank', 'rerank_model', 'rerank_top_k')
        }),

    )

    @action(description='Train', url_path="train_embed_model")
    def train_embed(self, request: HttpRequest, object_id: int):
        general_parse_embed.delay(object_id)
        messages.success(request, 'Training started')
        return redirect(reverse('admin:knowledge_mgmt_knowledgebasefolder_changelist'))

    def embed_model_link(self, obj):
        link = reverse("admin:model_provider_mgmt_embedprovider_change", args=[obj.embed_model.id])
        return format_html('<a href="{}">{}</a>', link, obj.embed_model)

    embed_model_link.short_description = 'Embedding Model'

I am trying to view this action in a list with only one record but it is not fully displayed. Is this a possible issue with Django Admin, or have I made a mistake in using actions_row?

Can anyone provide some assistance? Thank you.

**Comment by lukasvinclav** [comment]
Duplicate #448

**Comment by etherfurnace** [comment]
thanks, i down grade to 0.22.0 it work 😄
