### ISSUE TITLE
unexpected sizes for headers image in the list display

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#461]
<img width="1091" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/f923dfc6-2e99-48b6-b312-02c429c58324">

Only the headers with image width and height are applied. 
<img width="1074" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/830c90ed-ff76-420d-8af9-e8ff0e2f47e3">

you can see here even when the width should be fixed they are not displayed correctly the size change based on the image:
<img width="1077" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/c65142a9-108f-454a-a5ac-6bf5b6bad83e">

**Comment by lukasvinclav** [comment]
What is wrong here?

**Comment by omargawdat** [comment]
as you can see in the code the height and the width should be fixed values with 50 but in the below image it doesn't keep it consistent so I got different heights based on the default image height. 

<img width="485" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/1676e3ef-bacc-4ff8-8256-265b8bb2932a">

<img width="825" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/e9161c8f-bc99-4cfe-b03e-31e477ef10b4">

**Comment by omargawdat** [comment]
> What is wrong here?

could you check why the height constraint isn't applied?

**Comment by omargawdat** [comment]
it's fine that this is not a plan but can you explain to me how I can use height correctly, whatever number I put in the height, it doesn't work so am I doing something wrong or it has no use?
