### ISSUE TITLE
UnfoldAdminSingleDateWidget calendar picking up wrong year if used different `format`

### ISSUE THREAD

**Issue by dacodekid** [unfoldadmin/django-unfold#470]
```py
class BaseUnfoldMixin:
    formfield_overrides = {
        models.TextField: {
            "widget": WysiwygWidget,
        },
        models.DateField: {
            "widget": UnfoldAdminSingleDateWidget(
                format="%m-%d-%Y",
                attrs={
                    "placeholder": "MM-DD-YYYY",
                },
            ),
            "input_formats": ["%m-%d-%Y"],
        },
    }
```

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/611f620f-6a87-4b5c-8f24-5ee7db5d7ca6)

For the above code, it displays the date in 'mm-dd-yyyy`.  But the calendar widget shows year 1910.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/2232e2b6-24df-4e47-9e51-58bf58be91f6)

But commenting the `format="%m-%d-%Y"` and the date format back to `yyyy-mm-dd` shows the correct year.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/3506dd28-9083-44f3-8c70-08cf1fbd1070)

**Comment by dacodekid** [comment]
Just noticed that setting the date format might bring more issues.  With current `dd-mm-yyyy` format, selecting a date from the Calendar widget or `Today` button, would input the date in `yyyy-mm-dd` format.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/2c47c182-fc42-4038-8da5-32a603ed5254)

Also, the calendar widget highlights `today`'s date in circle and not the input value's.

**Comment by lukasvinclav** [comment]
Did you updated DATE_INPUT_FORMATS in settings.py? Please create a minimal repo where I can reproduce the issue because right now I'm not able to see all the settings and dependencies.
