### ISSUE TITLE
Sidebar Search drop-down not closing on click outside

### ISSUE THREAD

**Issue by PaulleDemon** [unfoldadmin/django-unfold#475]
Hi 
The side-menu search bar in its current form is a bit hard to close, the default close x in the search bar doesn't really clear the search. 
Currently, you'll have to manually backspace or clear the search for the dropdown to disappear, which is less intuitive. Closing the dropdown on click outside or having a clear button in would greatly improve user experience.

Thx

https://github.com/unfoldadmin/django-unfold/assets/64060109/bd00661a-88a9-4719-b18b-cb7d5d7873a1

**Comment by lukasvinclav** [comment]
Fixed #548
