### ISSUE TITLE
Simple history always empty inside Admin

### ISSUE THREAD

**Issue by frobert** [unfoldadmin/django-unfold#479]
Hi there, not sure if I'm missing something, but no matter the changes I make in records, the record history is always empty... Did ayone have the same issues?

I checked the simple history signals and they are triggered as expected. I also see records in database, but not in django admin...
It also works in python shell..

Thanks.

<img width="1583" alt="Screenshot 2024-06-13 at 13 18 20" src="https://github.com/unfoldadmin/django-unfold/assets/858426/010c2fca-fb1a-4f3d-ba7f-b64f17848d45">
<img width="272" alt="Screenshot 2024-06-13 at 13 19 00" src="https://github.com/unfoldadmin/django-unfold/assets/858426/1f89fafe-9f86-490d-9c6b-826522f2e92e">
<img width="414" alt="Screenshot 2024-06-13 at 13 19 10" src="https://github.com/unfoldadmin/django-unfold/assets/858426/6ab9651b-6166-4722-a269-72aae1a657d9">

<img width="1412" alt="Screenshot 2024-06-13 at 13 24 06" src="https://github.com/unfoldadmin/django-unfold/assets/858426/9eb0e387-c2d5-4af0-808d-e33f47293623">

**Comment by frobert** [comment]
Made some more tests:

- If I disable Unfold it works
- Unfold enabled and "unfold.contrib.simple_history" removed from installed apps, it works bit no styling
- if I add "unfold.contrib.simple_history" to installed apps, it is not working anymore.

<img width="738" alt="Screenshot 2024-06-13 at 18 05 19" src="https://github.com/unfoldadmin/django-unfold/assets/858426/f6232ec6-f65d-422a-aad6-77fd18bd475d">

**Comment by lukasvinclav** [comment]
They refactored templates. Fixed in #482

**Comment by frobert** [comment]
That is awesome. Thanks a lot!
