### ISSUE TITLE
Not selectable periodic tasks

### ISSUE THREAD

**Issue by mgmka** [unfoldadmin/django-unfold#480]
The periodic task selection field does not contain a selection function, so the task name must be entered manually?

![image](https://github.com/unfoldadmin/django-unfold/assets/19649601/fdbfa4ce-3853-45a7-9328-7ab14c8bacc1)

when I comment 

```
# @admin.register(PeriodicTask)
# class PeriodicTaskAdmin(ModelAdmin):
#     pass
```

a combobox appears in the task addition field

![image](https://github.com/unfoldadmin/django-unfold/assets/19649601/6acb5197-2e43-497f-a5b1-bac9fb936f33)

**Comment by lukasvinclav** [comment]
Yes, you are right. In #483 I updated documentation to actually inherit from existing admins.
