### ISSUE TITLE
Set up continuous deployment on merge to `main`

### ISSUE THREAD

**Issue by nvn-nil** [unfoldadmin/django-unfold#485]
### Content

I had the ArrayWidget decompress method issue and opened issue #484 for it.

However, It was super confusing when I came to report this bug but the permalink off of `main` had the fix and my latest version didn't. I went back to my code, poetry, and PyPi, and triple-checked to make sure I had the latest version of Unfold installed (yes, 0.28.0). The fix and other code were in `main` without a release.

A suggestion is to implement a `dev` branch -> `main` branch CI/CD setup. You can merge all the PRs for a release into dev and merge it when you're ready.

**Comment by lukasvinclav** [comment]
I thought, the current flow is more or less industry standard for open source packages.

**Comment by nvn-nil** [comment]
You're right, I checked and this flow is common for open-source libraries.

One improvement you could consider is to merge contributions to a tagged branch, like `0.29.0-beta`. Commits to this branch could be used as a release candidate, canarying, etc and merged to main for release. It might just be a personal thing where I expect main to be well tested and stable.
