### ISSUE TITLE
[Feature Request]  Let ArrayWidget respect choices parameter

### ISSUE THREAD

**Issue by VaZark** [unfoldadmin/django-unfold#486]
When the ArrayField has a CharField with a `choices` parameter to store select values, it would be great to have a widget that lists the options directly from the available choices.

At the moment, I override an ArrayField with a `forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=..)`. This data is then directly stored as an array.

**Comment by lukasvinclav** [comment]
Added #547
