### ISSUE TITLE
GenericTabularInline doesn't work properly

### ISSUE THREAD

**Issue by stepankhodyrev** [unfoldadmin/django-unfold#488]
Styles support does not work when adding GenericTabularInline class to inlines variable of Admin class. When adding other TabularInline classes they work natively, it is GenericTabularInline that has the problem

**Comment by lukasvinclav** [comment]
Try to inherit from `unfold.admin.TabularInline` as well.

**Comment by lukasvinclav** [comment]
I just tested an example below and it works without any problems

```python
from django.contrib.contenttypes.admin import GenericTabularInline
from unfold.admin import TabularInline

class TagGenericTabularInline(TabularInline, GenericTabularInline):
    model = Tag
```
