### ISSUE TITLE
Run selected action missing

### ISSUE THREAD

**Issue by a1eksb** [unfoldadmin/django-unfold#489]
Hi, first of all thank you for the amazing admin theme! 

Now to the issue: The run selected action button is missing from the admin panel in 0.28.1. So for example running a delete action on one of my model entries is no longer possible. As soon as I downgrade the action reappears.

**Comment by rense** [comment]
The "Run" button should appear when you select an action in the "Select action"-dropdown.

**Comment by a1eksb** [comment]
Hi @rense thanks for the tip. However, that's not the case currently. Selecting an action does not result in a visible "run button".

**Comment by lukasvinclav** [comment]
Please create a minimal repository how to reproduce the issue. I tested this functionality already multiple times without success.

**Comment by a1eksb** [comment]
Hi @lukasvinclav sorry for the late reply. I identified the issue. I was not defining my admin classes with `ModelAdmin` from unfold and that caused the "run" button to not appear. 

The reason for avoiding the ModelAdmin was that I have to use the `django-jsonform` package which does not currently play well with unfold at the moment.
