### ISSUE TITLE
problem with changing  pagination and filter design 

### ISSUE THREAD

**Issue by dragonscraper** [unfoldadmin/django-unfold#496]
hello , first I'd like to thank you for this amazing project 
i have some issues with the pagination and filter design 
I'm trying to edit it , but now working 
any tips will be helpful 

i have tried  to edit pagination.html file but change does not work only show total objects , but not navigation urls

**Comment by lukasvinclav** [comment]
Would you mind to describe what exactly is not working? Do you have same issue in the demo project? Could you set up example repository where it is possible to reproduce the issue?

**Comment by dragonscraper** [comment]
I'm trying to override? change pagination  design but when i do it doesn't show pagination links
