### ISSUE TITLE
unfold admin theme and mdeditor

### ISSUE THREAD

**Issue by ankarastrix** [unfoldadmin/django-unfold#497]
Hello,

I'm currently working on a Django project and I'm trying to integrate the Unfold Admin theme with django-mdeditor for Markdown editing within the Django admin interface. I've installed both packages (unfold-admin and django-mdeditor), but I'm encountering issues in getting them to work together seamlessly.

Could you please provide guidance or steps on how to properly integrate the Unfold Admin theme with django-mdeditor in the Django admin panel? Specifically, I need to configure the Markdown editor (MDTextField) provided by django-mdeditor to work correctly within the Unfold Admin theme.

Any help or examples would be greatly appreciated.

**Comment by lukasvinclav** [comment]
Unfortunately, I don't have any experience with this plugin. Most of the time when I'm working with markdown (blog posts), I'm including them as md files in project.

**Comment by dragonscraper** [comment]
did u find any solution bro  ?
