### ISSUE TITLE
Problems with transparent in `nav-sidebar` on mobile devices (dark theme).

### ISSUE THREAD

**Issue by vasylkyselytsia** [unfoldadmin/django-unfold#499]
Hello, first I'd like to thank you for this Amazing Project.
I found some issues with the nav-sidebar (Only for dark theme).
Added screenshots from `https://demo.unfoldadmin.com/admin/`

![image](https://github.com/unfoldadmin/django-unfold/assets/19221789/00a67271-c834-491a-b4b7-0afdf510d4a3)
<img width="1015" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/19221789/6dbdef4e-566f-4cca-ad77-f8d3dd01be6c">

**Comment by lukasvinclav** [comment]
Thanks. Fixed #501
