### ISSUE TITLE
Bug report: SidebarMobile background get transparent unexpectedly in version 0.28.1

### ISSUE THREAD

**Issue by intp1** [unfoldadmin/django-unfold#507]
In Admin mobile view ( django-unfold==0.28.1), sidebarMobile overlays the main body with a transparent background, which messes up the views of both two layers.
After noticing this issue, I tried to re-install previous versions, such as 0.26.0、0.27.0、0.28.0， those seem work fine.
![bug_sidebarMobile](https://github.com/unfoldadmin/django-unfold/assets/59410471/621b25c4-b651-4703-b094-33be4691f733)

**Comment by vasylkyselytsia** [comment]
https://github.com/unfoldadmin/django-unfold/issues/499
