### ISSUE TITLE
Text in Card component interrupts dropdown menu from  mouse seletion

### ISSUE THREAD

**Issue by pixelplayer001** [unfoldadmin/django-unfold#516]
This happens in custom admin index, while constructing unfold components,  looks like kind of z-index conflict, not only messing up views, but also interrupting mouse selection with the dropdown menu. 

![Custom admin index will interrupt dropdown menu](https://github.com/unfoldadmin/django-unfold/assets/167219385/81d8782e-1ff4-4a57-90b9-dbdf7b2508fe)

**Comment by lukasvinclav** [comment]
This was already fixed. Please update Unfold.
