### ISSUE TITLE
Vertical Scrollbar missing in Sidebar [0.29.1]

### ISSUE THREAD

**Issue by dacodekid** [unfoldadmin/django-unfold#521]
Reverting back to 0.28.1 brings it back.

**Comment by lukasvinclav** [comment]
Unfortunately, I'm not able to reproduce the issue.

**Comment by dacodekid** [comment]
My apologies. The issue was on my part.  I've overridden `helpers/app_list.html` file to hide `empty` app labels (when a user doesn't have permissions for any models) which caused the issue from `0.29.1` onwards.
