### ISSUE TITLE
Change password link is escaped/doesn't work with Custom User

### ISSUE THREAD

**Issue by TobeTek** [unfoldadmin/django-unfold#524]
Django version: `5.0.4`
Django-Unfold version: `0.29.1`

Great project!
In the django-admin, the link meant to redirect to change password view/form doesn't work, and appears to be escaped.
![chrome_yuq5hN4hK4](https://github.com/unfoldadmin/django-unfold/assets/82294671/bbc2604a-fd23-4fbc-aa33-ff7b377a5826)

By modifying the UserChangeForm, and explicitly calling `mark_safe`, the link begins to work.
![chrome_51XrzYWhPA](https://github.com/unfoldadmin/django-unfold/assets/82294671/cbe938ca-9e77-4bd4-8730-e50421cd86e5)

Here's the full code snippet

```py

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm as BaseUserCreationForm,
    ReadOnlyPasswordHashField,
)
from django.utils.safestring import mark_safe


class UserForm(BaseUserChangeForm):
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=mark_safe(
            _(
                "Raw passwords are not stored, so there is no way to see this "
                "user’s password, but you can change the password using "
                '<a class="font-medium text-blue-500 dark:text-blue-500 hover:underline" href="{}">this form</a>.'
            )
        ),
    )

    class Meta:
        model = get_user_model()
        fields = [
            "email_address",
            "password",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if password:
            password.help_text = mark_safe(
                password.help_text.format(f"../../{self.instance.pk}/password/")
            )


```

**Comment by lukasvinclav** [comment]
Please check out the docs for more information:

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#user-admin-form

**Comment by TobeTek** [comment]
My bad!
Just missed that in the docs. Thanks 👍

**Comment by Zerotask** [comment]
> Please check out the docs for more information:
> 
> https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#user-admin-form

The Link does not work anymore. What's the solution for this issue?

We also use a custom user model and the link is not interpreted as HTML. We followed the docs here: https://unfoldadmin.com/docs/installation/auth/
except we can't use `admin.site.unregister(User)` because it raises an error (django.contrib.admin.exceptions.NotRegistered: The model User is not registered)

Do we miss anything? The rest of the UserAdmin looks like a regular unfold page.

**Comment by TobeTek** [comment]
Hi @Zerotask , I would make sure to check you're using the  UserCreate, UserEdit and PasswordChange forms provided by `unfold`.
You can find an example in https://github.com/unfoldadmin/django-unfold/blob/3f463d2c4a3e2506255b0381162a97609241a340/tests/server/example/admin.py#L15
