### ISSUE TITLE
How can i download the uploaded file like pdf from the admin

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#528]
in admin unlike the image fields i can't download or access the file it only display the URL so how can I being able to access or download the file like pdf file is there anyway for doing that? 
<img width="744" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/67590805-a263-417c-9c45-f8379488aba3">

code:
class WorkingDocumentation(BaseModel):
    business_license = models.FileField(
        upload_to="company_docs/",
        null=True,
    )

class UnfoldAdminFileFieldWidget(FileFieldMixin, AdminFileWidget):
    template_name = "unfold/widgets/clearable_file_input.html"

class WorkingDocumentationForm(forms.ModelForm):
    class Meta:
        model = WorkingDocumentation
        fields = '__all__'
        widgets = {
            'business_license': UnfoldAdminFileFieldWidget(),
        }

@admin.register(WorkingDocumentation)
class WorkingDocumentationAdmin(ModelAdmin):
    form = WorkingDocumentationForm

**Comment by lukasvinclav** [comment]
Fixed in #543
