### ISSUE TITLE
Custom Admin Page Queries

### ISSUE THREAD

**Issue by kaustumbh7** [unfoldadmin/django-unfold#531]
Referencing https://github.com/unfoldadmin/django-unfold/issues/525 as it was closed without resolving all questions and no option to re-open.
Query- https://github.com/unfoldadmin/django-unfold/issues/525#issuecomment-2199192834

**Comment by kaustumbh7** [comment]
@lukasvinclav

**Comment by lukasvinclav** [comment]
Yes, I answered your question. You need to register a model. Please, do not open new duplicated issues without bringing at least some new information or maybe a PR with solution.

**Comment by xplsek03** [comment]
> Referencing #525 as it was closed without resolving all questions and no option to re-open. Query- [#525 (comment)](https://github.com/unfoldadmin/django-unfold/issues/525#issuecomment-2199192834)

After seeing everything I would have to override I gave up, created fake class + model and used actions, which are powerful. If its enough for your usecase and you dont mind one extra fake model, I advise you to do the same.
