### ISSUE TITLE
Password Label tailwind style loss on customizing change_form template

### ISSUE THREAD

**Issue by AckyZhang** [unfoldadmin/django-unfold#532]
As described, the password field label will lose it's class when customizing change_form of User object, because nor the widget neither the template start with unfold.
I've customized the password field by overidding the PasswordInput widget class into UnfoldPasswordInput class without doing anything but pass.
The same style loss happens FilteredSelectMultiple class.
So what is the purpose for the original design for this check:?
https://github.com/unfoldadmin/django-unfold/blob/0501bbf45f3db9159f011097b767a93ed5a36fe7/src/unfold/fields.py#L178-L181
        if not self.field.field.widget.__class__.__name__.startswith(
            "Unfold"
        ) and not self.field.field.widget.template_name.startswith("unfold"):
            return super().label_tag()

**Comment by lukasvinclav** [comment]
The reason for this condition is to ensure that proper styles are applied only when Unfold is used because you can have default admin running in parallel where we don't want to apply Unfold styles.

**Comment by AckyZhang** [comment]
Appriciate your answer! Is there any better way to sustain the styles other than rewrite the widget class with Unfold title?

**Comment by lukasvinclav** [comment]
Unfortunately, I was not able to find an elegant way how to do it. I guess it would be possible to achieve such a solution but when I was looking at it, I would be required to override tons of business logic which I'm trying to avoid as much as possible.
