### ISSUE TITLE
Multi Language support 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#534]
Can you consider adding multi Language support, there is a pull request that added this feature so you can check it #494

**Comment by lukasvinclav** [comment]
Is the language switch available in default Django admin?

**Comment by omargawdat** [comment]
Django itself supports multiple languages, but you have to write the code for displaying the drop-down menu and maybe change RTL or LTR based on the language (not that important in most cases), over all this feature is so important as we are using your wonderful package around the worlds so localization is important.

noting that there are some Django admin packages that support multi-languages like jazmmin 
https://django-jazzmin.readthedocs.io/configuration/#language-chooser

**Comment by lukasvinclav** [comment]
@omargawdat implemented in #854
