### ISSUE TITLE
The new changelist horizontal scrollbar position feature not working on google chrome

### ISSUE THREAD

**Issue by AckyZhang** [unfoldadmin/django-unfold#536]
I don't even know the reason, but the feature works on my firefox and MS edge browser. 
While on google chrome the scrollbar still on the bottom.
I 've tried uninstall and install unfold and make sure the version is the newest 0.30.0
My google chrome version is 126.0.6478.127.
It's not that important but hoping I can get some fresh ideas/inspirations why this happens?

**Comment by lukasvinclav** [comment]
I just tested `list_horizontal_scrollbar_top` flag on ModelAdmin and it works without any issues on Chrome. Please create a minimal repo where it is possible to reproduce the issue.

**Comment by AckyZhang** [comment]
I cannot reproduce the issue with minimal repo. I guess maybe some mixin class make my project strange. Thank you again for answering.
