### ISSUE TITLE
List filters are not working, glitched

### ISSUE THREAD

**Issue by san425** [unfoldadmin/django-unfold#55]
Hi! I have registered a model with this code.

```
class ClickAdmin(ModelAdmin):
    search_fields = ['front', 'back',]
    list_filter = ('set__subject', 'set__grade')
```
    
However when in the Django admin, it shows like this:

<img width="456" alt="Screenshot 2023-04-05 at 6 43 09 PM" src="https://user-images.githubusercontent.com/74281095/230251482-707f3114-1d39-41e5-9110-ee22f5a7626d.png">

Maybe I'm missing something, maybe I'm not, but does anyone know why this is happening and how to fix?

**Comment by lukasvinclav** [comment]
Would you mind to show your imports? Are you sure that ModelAdmin is imported from unfold?
