### ISSUE TITLE
Changelist search field and filters issues

### ISSUE THREAD

**Issue by konkab** [unfoldadmin/django-unfold#556]
While playing around with the demo, I noticed a few bugs related to search / filters functionality:
1. If you first apply filters and then apply search filter, it will reset applied filters
2. The filters submit button resets search filter

**Comment by lukasvinclav** [comment]
I just tested filters and it seems to be okay. Which URL exactly you were testing and what are the steps to reproduce?

**Comment by konkab** [comment]
I'm comparing to the default Django admin.

Steps to reproduce bug #1:
1. Apply a filter: https://demo.unfoldadmin.com/admin/formula/driver/?status__exact=ACTIVE
2. Apply the search field filter and the url is gonna be: https://demo.unfoldadmin.com/admin/formula/driver/?q=Paul. The url should keep original query params, but it doesn't.

Steps to reproduce bug #2:
1. Apply the search field filter: https://demo.unfoldadmin.com/admin/formula/driver/?q=Paul
2. Apply a filter, hit submit button and the urls is gonna be: https://demo.unfoldadmin.com/admin/formula/driver/?status__exact=ACTIVE. Same here.

**Comment by lukasvinclav** [comment]
Fixed #566

**Comment by AckyZhang** [comment]
I just pulled the newest update to my local env and it seems not working?
By checking on the js code, it seems just check the existing q parameter and change its value to searchString. Which works for repeatly searching for different keywords, but back to the default changelist when there's no q param in queryparam it won't add q param to the queryparams causing the website just keeps refreshing itself.

(By the way the ordering parameter ?o= may also need to be preserved somehow? (Though I'm not that sure if it's needed?
