### ISSUE TITLE
Unreleased Inline tabs feature: Fieldset tabs display bug

### ISSUE THREAD

**Issue by konkab** [unfoldadmin/django-unfold#563]
If you have fieldset tabs in General tab, they will show up when you switch to any inline tab, but they shouldn't.
<img width="401" alt="Screenshot 2024-07-10 at 22 58 07" src="https://github.com/unfoldadmin/django-unfold/assets/1832821/84acfe6f-9a69-422f-8ec0-3cfcde54186a">

**Comment by lukasvinclav** [comment]
Fixed #564
