### ISSUE TITLE
Flexible Inline tabs: custom titles, mixing with other fieldsets

### ISSUE THREAD

**Issue by konkab** [unfoldadmin/django-unfold#565]
I'm currently using this package to implement inline tabs: https://github.com/omji/django-tabbed-admin?tab=readme-ov-file#configure-admin-tabs.

It looks very flexible to me and allows to mix multiple inlines and fieldsets under one tab with an extra model:
``` python
@admin.register(Band)
class BandAdmin(TabbedModelAdmin):
    model = Band

    tab_overview = (
        (None, {
            'fields': ('name', 'bio', 'style')
        }),
        MusicianInline,
        ('Contact', {
            'fields': ('agent', 'phone', 'email')
        })
    )
    tab_album = (
        AlbumInline,
    )
    tabs = [
        ('Overview', tab_overview),
        ('Albums', tab_album)
    ]
```

What do you think about implementing something similar?

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/
