### ISSUE TITLE
bug report:  row-action not render on last row

### ISSUE THREAD

**Issue by Ehco1996** [unfoldadmin/django-unfold#567]
hi thanks for your great work but i found one issue that `row-action` not render on last row

see more in

* first record is ok
<img width="1261" alt="Screenshot 2024-07-11 at 15 18 36" src="https://github.com/unfoldadmin/django-unfold/assets/24697284/7279d112-3216-443b-861e-d60fc27537af">

* last record is wrong
<img width="1315" alt="Screenshot 2024-07-11 at 15 18 42" src="https://github.com/unfoldadmin/django-unfold/assets/24697284/06565208-5721-4f31-a240-ef10fd5c0a1e">

**Comment by lukasvinclav** [comment]
Already fixed in main branch.

**Comment by Ehco1996** [comment]
@lukasvinclav  Oh, thank you. I am curious about when your release will occur.
