### ISSUE TITLE
FCM-Django Integration 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#569]
I can't see a way to run actions of the package FCM-Django [https://github.com/xtrinch/fcm-django](url)
<img width="1081" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/4bdc67bc-a5ac-48d4-b9b9-5770ca93ad99">
<img width="1079" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/589a8935-e305-4fa5-a43e-53d95659b6fb">

when i tried to reregister it using unfold Modeladmin the available actions disappeared 
<img width="1120" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/53629777/1f29ffee-dc67-4ee2-be68-d52ac45c4299">

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/
