### ISSUE TITLE
Remember/show current active TAB (anchor tag link)

### ISSUE THREAD

**Issue by frobert** [unfoldadmin/django-unfold#570]
Hi there, when working wuth admin, I've noticed active TAB is not remembered in admin. 

It would be nice to have working link anchor tags, so when going to for example http://localhost:8000/contacts/company/1/change/#TabName the view would open the specified TAB called "TabName" directly.

Thanks, best regards

**Comment by lukasvinclav** [comment]
@frobert would you mind to create a PR with this improvement? I will be happy to accept it.

**Comment by frobert** [comment]
Quite bussy these days, but if somone else will not manage to add this feature soon, I'll try as soon as i have some spare time. Thanks.

**Comment by lukasvinclav** [comment]
@frobert any update?

**Comment by lukasvinclav** [comment]
@frobert I checked the pull requests sections and I didn't noticed any PR addressing your improvement. Can I consider that everything is all right and I can close the issue?
