### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Alvanerle** [unfoldadmin/django-unfold#571]
The problem:
When I want to connect related objects the search does not work (it redirects to another non related page)
<img width="1512" alt="Screenshot 2024-07-12 at 16 25 41" src="https://github.com/user-attachments/assets/b9fd630d-e86e-476f-ab8d-e8723a0823d4">
<img width="1512" alt="Screenshot 2024-07-12 at 16 25 47" src="https://github.com/user-attachments/assets/dac93867-04a9-4898-adf7-a7455a555048">
<img width="1512" alt="Screenshot 2024-07-12 at 16 25 51" src="https://github.com/user-attachments/assets/8f6d5c67-9f7f-4e42-b6aa-3b4817daea35">

**Comment by AliYmn** [comment]
@Alvanerle yes you are right, filter and search doesn't work same time. If you select something in filter, this search text be empty when refresh page. FYI @lukasvinclav

**Comment by lukasvinclav** [comment]
This issue is already fixed in main branch.

**Comment by dacodekid** [comment]
@lukasvinclav , I am on `main` branch, and for me the query parameter changes from `?q=XXXXX` to `?e=1` on every model and displays the entire query set in response / and clears the search bar.

<img width="219" alt="image" src="https://github.com/user-attachments/assets/8f600299-1ec4-4e04-a5fc-b553c340b545">

If manually change the `?e=` to `?q=` at the address bar, hit enter - and search this time and it works until the address bar url value changes.

<img width="202" alt="image" src="https://github.com/user-attachments/assets/ba82a53f-77bb-4ee5-b9cd-fe0185f6923f">


<img width="300" alt="image" src="https://github.com/user-attachments/assets/7737cc40-8bbe-48bb-aaa1-566f6cfb0884">
