### ISSUE TITLE
download file button still not displaying 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#574]
after trying to download the file after the fix I still can't see the download button #543 
<img width="754" alt="image" src="https://github.com/user-attachments/assets/37c448cf-1c6d-48f2-ad24-fd431f8e8da0">

**Comment by lukasvinclav** [comment]
Because the fix was no released yet.

**Comment by omargawdat** [comment]
When I reported the issue, it was based on the last commit, not the release. However, even after the latest release, version 0.31, the file remains undownloadable

Change list: 
<img width="860" alt="image" src="https://github.com/user-attachments/assets/d097085c-c412-441a-923d-f273e2692234">

Code: 
```
class WorkingDocumentation(BaseModel):
    commercial_register = models.FileField(
        upload_to="documents/commercial_register/",
        null=True,
        help_text=_("A document registering the company with the specialized government authorities."),
    )
    tax_card = models.FileField(
        upload_to="documents/tax_card/",
        null=True,
        blank=True,
        help_text=_("A document proving the company's registration in the tax system."),
    )
    articles_of_association = models.FileField(
        upload_to="documents/articles_of_association/",
        null=True,
        blank=True,
        help_text=_("If the company is new, the company's articles of association must be submitted."),
    )
```
