### ISSUE TITLE
How to enable Charts in Dashboard and also change colors

### ISSUE THREAD

**Issue by Nneji123** [unfoldadmin/django-unfold#578]
Hello, I recently discovered this admin template through a youtube channel and was deeply impressed with it. What a lovely clean design. I've setup most of the functionality using the repo examples you provided in the readme but I've ran into some sort of issue.

I'm trying to modify the base colour for the UI to blue and then display charts in the dashboard but I don't know how to go about it.

**Comment by lukasvinclav** [comment]
I recommend starting with the documentation:

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#available-settingspy-options
https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#admin-dashboard
