### ISSUE TITLE
Doubled attribute `id` for file field

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#581]
Hi, HTML for file field contains two "id" attributes, as one comes from django and one is hardcoded in template:

```html
    <div class="flex flex-none items-center leading-none self-stretch">
        <input id="image" type="file" name="image" class="hidden"  accept="image/*" id="id_image" />

        <label for="image" class="cursor-pointer text-gray-400 px-3 hover:text-gray-700 dark:text-gray-500 dark:hover:text-gray-200">
            <span class="material-symbols-outlined">file_upload</span>
        </label>
    </div>

```

See: https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/templates/unfold/widgets/clearable_file_input.html#L26-L40

**Comment by lukasvinclav** [comment]
What kind of problems was this causing?

**Comment by PavelPancocha** [comment]
It breaks the HTML validity of the page. We use automatic checks for these types of errors, as it is mostly caused by some other problem.
