### ISSUE TITLE
Filter modal styling

### ISSUE THREAD

**Issue by Rey092** [unfoldadmin/django-unfold#587]
templates/unfold/change_list_filter.py

Current:
bg-white flex **_mr-4_** my-4 overflow-hidden rounded shadow-sm w-96 dark:bg-gray-800
![image](https://github.com/user-attachments/assets/33268ddc-8654-483f-893c-e381820b9fe1)
Proposition:
bg-white flex **_mx-4_** my-4 overflow-hidden rounded shadow-sm w-96 dark:bg-gray-800
![image](https://github.com/user-attachments/assets/aa2f2121-0a87-47c2-9d83-772d0c8d7722)

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #688.
