### ISSUE TITLE
Question: Global background style change

### ISSUE THREAD

**Issue by dominikbullo** [unfoldadmin/django-unfold#589]
#### Description
I am interested in changing the style of the background for both light and dark modes.

#### Questions
1. Is it easily achievable to customize the background style globally for both light and dark modes?
2. What would be the best approach to implement these changes in the current codebase?

#### Reasons
1. The current background style may not align with the design requirements or aesthetic preferences of some users. Customizing the background for both light and dark modes can enhance the visual appeal and user experience.
2. We would like to have different colored backgrounds for different environments (e.g., development, staging, production) to easily distinguish between them.

Thank you for considering this inquiry and for the fantastic job with this project! Looking forward to your feedback and guidance on how to proceed.

**Comment by lukasvinclav** [comment]
Hey Dominik, 

for (2) you can check the environment label which can display the current environment name in top right corner. This is implemented directly in Unfold.

Regarding different themes, this is going to be more complex. Right now, we have only one dynamic color "bg-primary-*" & "text-primary-*" which is for changing default color (purple). But with your requirement, we need to completely refactor all backgrounds, borders, shadows and group them under "color schema" settings. I'm expecting weeks of work to get it done properly.

**Comment by dominikbullo** [comment]
Hello Lukas,

thank you for the answer :) 

I know about that label and we're already using it. I've also customized the sidebar, but it seems that's still not enough 😅. Therefore, I'm searching for more radical options.

I'm also aware of completely changing the color scheme for each environment, though I'm not really sold on that idea. However, acknowledging your suggestion, maybe that’s the best way forward at this moment.

Do you think this will be on your roadmap in the future? If we're keen on the original idea, would the answer for when it might be possible be "never" or "in X time"? I'm asking mainly because if it's not planned, I might need to do it on my own.

**Comment by lukasvinclav** [comment]
Unless somebody is willing to financially support the development, this is not in the roadmap. The complexity of this task is very high.

There are two other options to distinguish between environments:

1. implement prefix for title in browser tab which will look like [LOCAL] Admin, [STAG] Admin, [PROD] Admin

**Comment by dominikbullo** [comment]
I will give it a try! Thank you so much once again for quick help :) Since my question was answered, I am closing this issue for now.
