### ISSUE TITLE
Forgot/reset password template missing

### ISSUE THREAD

**Issue by frobert** [unfoldadmin/django-unfold#590]
I've enabled the forgot password option on login page, on logi the styling is ok

<img width="544" alt="Screenshot 2024-07-17 at 11 02 04 1" src="https://github.com/user-attachments/assets/20885eda-2aef-4ed3-a2a8-d5c1a1392f92">

but when open the reset password link, the template styling is not working.

<img width="1684" alt="Screenshot 2024-07-17 at 11 02 23" src="https://github.com/user-attachments/assets/ab3832d4-9aa6-4db8-8568-0c8564d86eda">

Am I missing something or the template is curently not yet developed in unfold admin templates?

Thanks, best regards

**Comment by lukasvinclav** [comment]
Duplicate #384

**Comment by Mte90** [comment]
@lukasvinclav just a ping
