### ISSUE TITLE
Clickable elements styling

### ISSUE THREAD

**Issue by khaled5321** [unfoldadmin/django-unfold#595]
I think it would be better to change the clickable elements' color, so we know they are clickable, like the user email here
![Screenshot 2024-07-18 212052](https://github.com/user-attachments/assets/b23c110e-e307-4f5e-8de2-b9dd0725f5f9)

or the users' IDs here
![Screenshot 2024-07-18 212121](https://github.com/user-attachments/assets/efa2d54a-72f7-4e74-b125-3437b9462920)

**Comment by lukasvinclav** [comment]
Would you mind showing me the code responsible for rendering email address?

**Comment by khaled5321** [comment]
Here is the code for models.py and admin.py.

models.py
```python
from django.contrib.auth.models import AbstractBaseUser

class User(AbstractBaseUser):
    email = models.EmailField()

    # other fields here...
    
    USERNAME_FIELD = 'email'
    
    def __str__(self):
        return self.email
```

admin.py
```python
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from .models import User

@admin.register(User)
class CustomUserAdmin(ModelAdmin, UserAdmin):
    list_display = ['id', 'first_name', 'last_name', 'email', 'phone', ...]
    list_filter = ['is_active', 'is_staff']
    search_fields = ('email', 'first_name', 'last_name')
```

**Comment by lukasvinclav** [comment]
email here is just regular column here without any additional HTML formatting. I guess, when you inspect the element it is not wrapped in <a> tag at all. There is nothing what can be formatted here. I recommend you, to override the field display in admin and adding your own formatting.
