### ISSUE TITLE
Django-unfold messages not detected by makemessages

### ISSUE THREAD

**Issue by raayu83** [unfoldadmin/django-unfold#596]
Hi,

just started using django-unfold and love it so far!

One of the few things that I can't get to work right now is translating the messages.

I've set up translation for my project a while ago and it generally works well.
But for some reason, when I run `manage.py compilemessages -l de` the messages from django-unfold aren't added to my po file.

Are there some additional steps needed to enable translation of django-unfold?

**Comment by lukasvinclav** [comment]
In case a new string will be added into codebase, who is going to update po files?

**Comment by lukasvinclav** [comment]
This is something what I will consider in the future as this will be additional overhead.

**Comment by eitchtee** [comment]
Sorry for commenting on a closed thread, but @lukasvinclav can I kindly ask you to reconsider this decision?

Django's `makemessages` is surprisingly finicky for installed apps, requiring symlinks to even pickup the strings from Unfold (see https://stackoverflow.com/questions/17837149/makemessages-for-an-app-installed-in-virtualenv), which makes translations a PITA.

Unfold is already fully setup with i18n support, which at the moment is going to waste, adding translations built-in would be a great addition, with some small packaging changes required. A lot of packages include community made translations, including Django itself.

Your worry about unmaintained strings, while valid, is also a non-issue, as django will show the original english strings until somebody is bothered enough to update them, which while not ideal, displays the strength and worth of open source software, as there will always be somebody willing to do the work, as @raayu83 already did for German, and I'm willing to do for Portuguese.

Hope you can see the value in this and reconsider.

**Comment by lukasvinclav** [comment]
Thanks for the feedback. I haven't declined support for other languages in Unfold. What I said is that I don't have the time to maintain localization for multiple languages as I want to focus on shipping in my available time.

At the moment, Unfold is not just a chunk of Python code; it involves design, UX, a lot of CSS in Tailwind, Alpine.js, and other things which I may have forgotten to mention. I'm not exactly sure how to better manage my time to fit another task into this workload.

I don't think that adding localization support is just about accepting perfect PRs without any issues. Someone has to review them, test, release, handle communication, and probably other tasks..

If you want to help, you can provide a PR with instructions on how to translate Unfold per project. The link you provided already contains the correct answer, which takes literally minutes to implement. I will be happy to accept it.

PS: There is an interesting ticket, #443, regarding i18n. This is something I'm really interested in. So if someone is willing to support my time, I will be glad to improve Unfold in the matter of i18n.

**Comment by lukasvinclav** [comment]
@eitchtee do you have any other questions? Is it okay for you if I close the issue now?

**Comment by eitchtee** [comment]
All understood.

Thank you for your time.
