### ISSUE TITLE
Adding header block to 'admin/base.html'

### ISSUE THREAD

**Issue by khaled5321** [unfoldadmin/django-unfold#609]
**Do you have any examples?**

N/A

**Is it a third party application feature request?**

No

**In case of third party application, when it was updated last time?**

N/A

**Describe your feature request**

In `unfold/helpers/header.html` we have the following code:
```jinja2
{% if not is_popup %}
    {% block header %}
        <div class="border-b border-gray-200 mb-6 px-4 lg:px-12 dark:border-gray-800">
            <div class="{% if not cl.model_admin.list_fullwidth %}container{% endif %} flex items-center h-16 mx-auto py-4">
                <div id="header-inner" class="flex items-center w-full">
                    <div class="flex items-center w-full">
                        {% block usertools %}
                            {% if has_permission %}
                                {% block welcome-msg %}
                                    {% include 'unfold/helpers/welcomemsg.html' %}
                                {% endblock %}

                                {% block userlinks %}
                                    {% include 'unfold/helpers/userlinks.html' %}
                                {% endblock %}
                            {% endif %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% endif %}
```
The problem here is that we can't override the header block when extending from `admin/base_site.html` or `admin/base.html`, because `unfold/helpers/header.html` is included in `admin/base.html` using `{% include 'unfold/helpers/header.html' %}`. We would have to override the whole base block in order to customize the header.

I think it would be better to move the header block to `admin/base.html` for easier customization.

**Comment by lukasvinclav** [comment]
Why you don't just override `unfold/helpers/header.html`?

**Comment by khaled5321** [comment]
I have multiple custom admin pages, and each page has its custom header. I could make it work by overriding `unfold/helpers/header.html`, but I think this is unnecessary complex.

**Comment by lukasvinclav** [comment]
But this will just move the whole complexity on Unfold side. This template is already included on multitple places.
