### ISSUE TITLE
White loading screen when changing the tabs 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#611]
Bug video: 
https://github.com/user-attachments/assets/8d8afe32-5b2d-48d2-8e72-afcc5f43d797

Request: 
remove the white screen on loading as when the data gets bigger it takes more time to load.

**Comment by lukasvinclav** [comment]
Would you mind to replicate the issue on https://demo.unfoldadmin.com/admin/

**Comment by omargawdat** [comment]
the issue was in the old project using unfold 0.30.0 and Django 4.2, 
after I updated the unfold to 0.33.0 the problem was solved, thanks.
