### ISSUE TITLE
Custom HTML attributes for forms and fields (form-row)

### ISSUE THREAD

**Issue by juanfcocontreras** [unfoldadmin/django-unfold#612]
It would be interesting to have the ability to add custom attributes at both form and field level (including their title, i.e. form-row). This would allow, in a very simple way and without having to overwrite templates (which have the inconvenience of having to revise after updates), to add Alpine.js capabilities such as showing or hiding fields depending on the values you have in other fields (x-show).

I think you could use an approximation similar to that of:

https://github.com/unfoldadmin/django-unfold/pull/11/files

Do you think it would be useful and could be implemented?

**Comment by lukasvinclav** [comment]
Closed for not folowing issue creation instructions.

**Comment by juanfcocontreras** [comment]
I am very sorry for opening the issue without fulfilling the requirements @lukasvinclav .

I opened it as a feature request, hopefully following the guidelines:

https://github.com/unfoldadmin/django-unfold/issues/613
