### ISSUE TITLE
 Custom HTML attributes for forms and fields (form-row) 

### ISSUE THREAD

**Issue by juanfcocontreras** [unfoldadmin/django-unfold#613]
**Do you have any examples?**

https://alpinejs.dev/essentials/templating#toggling-elements

**Is it a third party application feature request?**

For example: No

**In case of third party application, when it was updated last time?**

Not applicable

**Describe your feature request**

It would be interesting to have the ability to add custom attributes at both form and field level (including their title, i.e. form-row). This would allow, in a very simple way and without having to overwrite templates (which have the inconvenience of having to revise after updates), to add Alpine.js capabilities such as showing or hiding fields depending on the values you have in other fields (x-show).

I think you could use an approximation similar to that of:

https://github.com/unfoldadmin/django-unfold/pull/11/files

Do you think it would be useful and could be implemented?

**Comment by galetahub** [comment]
A simple example, how to add custom attributes to form fields:
```python
from django import forms

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # checkbox
        self.fields["public_author"].widget.attrs.update({
            'x-ref': 'public_author_checkbox',
            'x-on:change': '$refs.author_name_input.disabled = !$refs.public_author_checkbox.checked'
        })
        # input
        self.fields["author_name"].widget.attrs.update({
            'x-ref': 'author_name_input',
            'x-bind:disabled': '!$refs.public_author_checkbox.checked'
        })
```

Finally connect form with admin model:
```python
from django.contrib import admin
from unfold.admin import ModelAdmin

@admin.register(Post)
class PostAdmin(ModelAdmin):
    list_display = ('id', "title", "author_name")
    form = PostForm
```

**Comment by juanfcocontreras** [comment]
But this would not include the labels, only the fields, or am I wrong?

> A simple example, how to add custom attributes to form fields:
> 
> ```python
> from django import forms
> 
> class PostForm(forms.ModelForm):
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         # checkbox
>         self.fields["public_author"].widget.attrs.update({
>             'x-ref': 'public_author_checkbox',
>             'x-on:change': '$refs.author_name_input.disabled = !$refs.public_author_checkbox.checked'
>         })
>         # input
>         self.fields["author_name"].widget.attrs.update({
>             'x-ref': 'author_name_input',
>             'x-bind:disabled': '!$refs.public_author_checkbox.checked'
>         })
> ```
> 
> Finally connect form with admin model:
> 
> ```python
> from django.contrib import admin
> from unfold.admin import ModelAdmin
> 
> @admin.register(Post)
> class PostAdmin(ModelAdmin):
>     list_display = ('id', "title", "author_name")
>     form = PostForm
> ```

**Comment by lukasvinclav** [comment]
@juanfcocontreras first of all thanks for recreating the issue. In your original issue you didn't mention alpine link. Now is everythin more clear.

The solution which @galetahub recommended is okay and I'm using it as well but I'm not sure what you mean by label. Probably you want to hide the whole row and just not make the input readonly/disabled, right? For that scenario, there is no builtin functionality and you have manually override the template or write custom JavaScript in separate file.

**Comment by juanfcocontreras** [comment]
@lukasvinclav first apologies for not following the guidelines the first time i posted the issue. I think they are new, and I had the issue filled before (without submitted).

> Probably you want to hide the whole row and just not make the input readonly/disabled, right?

That's exactly it, I was talking about the possibility of adding html attributes not only at field level, but also at row and form level.

It would be very useful not to have to modify the templates, because every time the package is updated, you have to check that everything still works.

For example, in [django-crispy-forms](https://django-crispy-forms.readthedocs.io) you can add any attribute to any element and it is passed to the html:

https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#layout-objects-attributes

I think this would open up a lot of possibilities from the python side without having to rely on templates.

In this pull request something very similar is done, but the truth is that without some indication, I am not able to implement it by myself:

https://github.com/unfoldadmin/django-unfold/pull/11/files

For the actions (from the pull request) there is a dictionary where you can add elements without problems, and it is very easy to connect it for the template.

But there is nothing similar for forms and fields, is there?

**Comment by lukasvinclav** [comment]
I'm fully aware of django-crispy-forms and the possibilities which it brings. This is not a small task and just from top of my head there are two major problems to solve:

1. creation of custom template pack in Unfold styles
2. isolating the crispy forms styles & settings in Unfold from the config for regular FE located outside of Unfold

There are going to be definitely tons of other problems which we are not aware of. I'm expecting several weeks of development here.

**Comment by juanfcocontreras** [comment]
I don't think I have explained myself well (English is not my mother tongue, so I apologise in advance), because in no case do I mean to replicate the functionality of crispy-forms.

Besides, the idea is to try to implement the functionality myself and be able to contribute to django-unfold, so this can't be a hard task for you, because then it would be impossible for me.

In the case of the [pull request](https://github.com/unfoldadmin/django-unfold/pull/11/files) I mention, the change involves a couple of lines. Adding in python in a dictionary the attributes, and mentioning them in the template. I don't know if this is possible at the form and row level, or in a wrapper of them.

I would like to know if there is an approach that would allow this in a relatively simple way. I don't have a lot of experience with Django and django-unfold, and I don't know if what I'm saying is complicated or not.

**Comment by lukasvinclav** [comment]
The PR which you are pointing at, is having completely different rendering logic comparing to forms. My answer here is to use the suggestions from my previous comment

https://github.com/unfoldadmin/django-unfold/issues/613#issuecomment-2245768894

**Comment by juanfcocontreras** [comment]
@lukasvinclav I think I've come up with a simple way (or at least I have a working example) that does what I intended. Also, I think it would be easily integrated into django-unfold, but before making a pull request, I'd like to know if you think it's appropriate or not.

In principle and as it is, it would be enough to create a couple of blocks, one for the form (`x-data`) and another for a fieldset row. Right now all the code is in the templates, but for the pull request the idea would be to make a couple of blocks to extend if you don't want to mess up the current code. 

Passing with `extra_context` the values, these could reach the template and get what I want.

I attach a video of the working example (ISBN field is only shown when book type is fiction), the relevant code snippets, and a zip with all the minimal project that works.

Sorry to insist so much, but I think it's a functionality that may interest more people. This could open up many more possibilities. The idea is to add all this functionality without any knowledge of templates, just some basic knowledge of Alpine.js.

If not, sorry again for the inconvenience.

![CleanShot 2024-07-24 at 16 29 35](https://github.com/user-attachments/assets/3cb7ac70-bafe-4ee2-b1a4-dd23c83297da)

`admin.py`

```python
[...]
@admin.register(Book)
class BookAdmin(ModelAdmin):
    def get_extra_context(self, request, object_id=None):
        context = {}

        context["x_data"] = r"{genre: 'f'}"

        context["attrs"] = {}
        context["attrs"]["genre"] = {"x-model": "genre"}
        context["attrs"]["isbn"] = {"x-show": "genre == 'f'"}

        return context

    def change_view(self, request, object_id, form_url="", extra_context=None):
        extra_context = {
            **(extra_context or {}),
            **self.get_extra_context(request, object_id),
        }
        return super().change_view(
            request, object_id, form_url, extra_context=extra_context
        )

    def add_view(self, request, form_url="", extra_context=None):
        extra_context = {**(extra_context or {}), **self.get_extra_context(request)}
        return super().add_view(request, form_url, extra_context=extra_context)
```

`change_form.html`

```html
[...]
{% block content %}
    <div id="content-main">
        <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}{% if form_url %}action="{{ form_url }}" {% endif %}method="post" id="{{ opts.model_name }}_form" novalidate>
            {% csrf_token %}

            {% block form_top %}{% endblock %}

            MODIFIED
            <div {% if x_data %}x-data="{{ x_data }}" {% endif %}>
            END MODIFIED
                {% if is_popup %}
                    <input type="hidden" name="{{ is_popup_var }}" value="1">
                {% endif %}
[...]

`fieldset_row.html`

```html
<div class="form-row
            {% if adminform.model_admin.compressed_fields %} border-b border-gray-200 -mx-3 px-3 pt-3 first:pt-0 dark:border-gray-800 last:border-b-0{% endif %}
            {% if not line.fields|length == 1 %} flex flex-row flex-wrap gap-x-8{% endif %}
            {% if not line.has_visible_field %} hidden{% endif %}
            {% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}"
            MODIFIED
            {% for field in line %}
                {% if field.field.name %}
                    {% if attrs %}
                        {% for field_name, field_values in attrs.items %}
                            {% if field_name == field.field.name %}
                                {% for attr_name, attr_value in field_values.items %}
                                    {{ attr_name }}="{{ attr_value }}"
                                {% endfor %}            
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endif %}
            {% endfor %}
            >
            END MODIFIED
    {% for field in line %}
        <div class="flex group {% if adminform.model_admin.compressed_fields %} field-row{% endif %}{% if not line.fields|length == 1 and not adminform.model_admin.compressed_fields %} lg:max-w-xs flex-grow{% endif %}{% if field.errors %} errors {% endif %}{% if not forloop.parentloop.last %} {% if adminform.model_admin.compressed_fields %}mb-3{% else %}mb-6{% endif %}{% else %} pb-3{% endif %} {% if adminform.model_admin.compressed_fields %}flex-col lg:flex-row lg:gap-2 {% else %}flex-col{% endif %}">
```

Project file: [locallibrary.zip](https://github.com/user-attachments/files/16363706/locallibrary.zip)

**Comment by juanfcocontreras** [comment]
In the end, I have opened a pull issue with the changes I mentioned. I think the impact is minimal (3 lines in templates), and yet it opens new possibilities of use. I hope I did well:

https://github.com/unfoldadmin/django-unfold/pull/631
