### ISSUE TITLE
Download file button only appear for images fields not files

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#617]
Unfold: 0.32.0
Django: 5 
Browser: Chrome 

## Problem: 
The download file option only exits for images, not file fields. 
### Image field 
**code**
```
class BannerImage(BaseModel):
    image = models.ImageField(upload_to="banners/", verbose_name=_("Image"))
```
**image** 
<img width="714" alt="image" src="https://github.com/user-attachments/assets/7baf99c1-e536-4821-85c3-4c66e4d78366">

### file field doesn't have the download button
**code**
```
class WorkingDocumentation(BaseModel):
    commercial_register = models.FileField(
        upload_to="documents/commercial_register/",
        null=True,
        help_text=_("A document registering the company with the specialized government authorities."),
        verbose_name=_("Commercial Register"),
    )
```

**image**
<img width="733" alt="image" src="https://github.com/user-attachments/assets/3440977d-c06d-4b82-a611-8df70e9ab6f3">

**Comment by lukasvinclav** [comment]
Thanks for report. Fixed in #690
