### ISSUE TITLE
Problem with the components

### ISSUE THREAD

**Issue by avarajar** [unfoldadmin/django-unfold#626]
I'm trying to do this:
<img width="938" alt="Screenshot 2024-07-24 at 12 37 08 PM" src="https://github.com/user-attachments/assets/c90038ed-c5e5-4f09-aafa-2aff0f5aad3c">

But I'm getting this:
<img width="956" alt="Screenshot 2024-07-24 at 12 39 10 PM" src="https://github.com/user-attachments/assets/1d863cfc-55f7-4403-a079-61dcd8181ede">

What is the error there? I use the same example in the docs

**Comment by khaled5321** [comment]
You should load unfold tag: `{% load i18n unfold %}`

**Comment by avarajar** [comment]
@khaled5321 ohh nice, that worked..Thanks, I appreciated. 👏🏼
