### ISSUE TITLE
AdminPasswordChangeForm not working

### ISSUE THREAD

**Issue by avarajar** [unfoldadmin/django-unfold#629]
I have this code:

`@admin.register(User)`
`class UserAdmin(DjangoUserAdmin, ModelAdmin):`
    `"""`
    `Custom User admin panel that excludes username.`
    `"""`

    list_filter: tuple = (
        'organization_membership__organization',
        'is_staff',
        'is_active',
        'is_superuser',
    )
    list_display: tuple = ('email', 'first_name', 'last_name', 'organization', 'is_active', 'is_staff')
    search_fields: tuple = ('first_name', 'last_name', 'email')
    ordering: tuple = ('email',)
    readonly_fields: tuple = ('created', 'modified', 'organization', 'last_login')

    fieldsets: tuple = (
        ('Organization', {'fields': ('organization',)}),
        ('Personal info', {'fields': ('first_name', 'last_name', 'email', 'timezone', 'kinde_id')}),
        (
            'Permissions',
            {
                'fields': (
                    'is_active',
                    'is_staff',
                    'is_superuser',
                    'groups',
                    'user_permissions',
                ),
            },
        ),
        ('Important dates', {'fields': ('last_login', 'created', 'modified')}),
    )

    add_fieldsets: tuple = (
        (
            None,
            {
                'classes': ('wide',),
                'fields': ('password1', 'password2'),
            },
        ),
    )
    add_form: UserCreationForm = UserCreationForm
    form = UserChangeForm
    add_form = UserCreationForm
    change_password_form = AdminPasswordChangeForm

    def get_form(self, request, obj=None, **kwargs):
        """
        Return the appropriate form for the user creation and updates.
        Removes the organization membership inline formset if the object is not yet created.
        """
        form = super().get_form(request, obj, **kwargs)
        if not obj:
            self.inlines: list = []
        else:
            self.inlines: list = [UserOrganizationMembershipInline]
        return form`

But the change password section doesn't appear in the admin section.. Anyone knows why?

This is the admin section:
<img width="1584" alt="Screenshot 2024-07-25 at 5 54 09 PM" src="https://github.com/user-attachments/assets/aa1b4b82-6179-45b3-87cd-96f7a186870b">
<img width="1569" alt="Screenshot 2024-07-25 at 5 54 16 PM" src="https://github.com/user-attachments/assets/ab25a628-6c61-4fba-828f-4f32ceaa8fd5">
<img width="1597" alt="Screenshot 2024-07-25 at 5 54 22 PM" src="https://github.com/user-attachments/assets/45fdcdcb-93b1-4829-978c-4f8862e5b1c9">

**Comment by striveforbest** [comment]
Similar issue for me. Please advise.

**Comment by carl0shd** [comment]
👀 +1

**Comment by lukasvinclav** [comment]
@avarajar why you didn't filled all required information when you were creating new issue? The code which you posted is incomplete, you are missing imports section. Did you checked https://demo.unfoldadmin.com if the issue is there as well?

**Comment by avarajar** [comment]
hey @lukasvinclav thanks for the reply, but I just found out that I missed add the password field in my UserAdmin. Now it's working.. 
<img width="831" alt="Screenshot 2024-07-26 at 9 37 20 AM" src="https://github.com/user-attachments/assets/cd86133c-5bc3-4759-a889-f35137eea622">
