### ISSUE TITLE
Make app/model list collapsible in side menu

### ISSUE THREAD

**Issue by asfawayalk** [unfoldadmin/django-unfold#633]
**Do you have any examples?**
when clicking the app name, the model list should collapse and expand
![image](https://github.com/user-attachments/assets/5dbbddee-a9bc-4a93-9b64-475bbda8a65d)

**Is it a third party application feature request?**

For example: No

**Describe your feature request**
Workflow
1. At first, the side menu should only show list apps only (the list of models should be collapsed)
2. When clicking the app, the list of models should expand
3. If I click the app again, it should collapse

**Comment by pnost** [comment]
It seems this feature is already there, at least in the demo: https://demo.unfoldadmin.com/admin/
However, I don't know how to use it as https://github.com/unfoldadmin/formula has not been updated to the newer releases. Still on on 0.28.1

**Comment by lukasvinclav** [comment]
Formula project updated.
