### ISSUE TITLE
Side Menu does not appear / Side Menu toggle button does not appear in Desktop version for Chrome browsers

### ISSUE THREAD

**Issue by asfawayalk** [unfoldadmin/django-unfold#634]
**What version of Unfold are you using?**

0.33.0

**What version of Django are you using?**

5.0.7

**What browser are you using?**

Ubuntu 22
  Firefox 128.0.3
  Chrome 125.0.6422.141 
  Brave 1.61.109

Windows 11
  Chrome 127.0.6533.72

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Repository with reproduced bug**
https://github.com/asfawayalk/test-django-unfold

**Describe your issue**
The side menu (together with the toggle button (to collapse and expand the side menu)) does not work for desktop version of chrome browsers at least in Ubuntu/Windows

This is how it appears
![image](https://github.com/user-attachments/assets/d1b1e1ea-4004-4f01-8591-272d81d4b6ae)

But it works fine in Firefox and Brave

**Comment by lukasvinclav** [comment]
Can you replicate same behaviour on the demo site?

https://demo.unfoldadmin.com/admin/

**Comment by lukasvinclav** [comment]
Closing due the lack of information. Unfortunately I'm not able to replicate the issue.
