### ISSUE TITLE
White screen after installing django-unfold

### ISSUE THREAD

**Issue by yashasolutions** [unfoldadmin/django-unfold#64]
I followed the installation instructions, and it seems there is an error coming from alpine.js 

```js
105:1 Uncaught SyntaxError: Unexpected token 'a', "auto" is not valid JSON
    at JSON.parse (<anonymous>)
    at d (alpine.persist.js:1:364)
    at t.interceptor.r.as.n (alpine.persist.js:1:116)
    at Object.initialize (alpine.js:1:4137)
    at alpine.js:1:3965
    at Array.forEach (<anonymous>)
    at r (alpine.js:1:3816)
    at ye (alpine.js:1:4038)
    at alpine.js:5:30058
    at Function.<anonymous> (alpine.js:5:10674)
```

I looked online, only found one issue on [SO](https://stackoverflow.com/questions/75968304/white-screen-after-installing-django-unfold) but with no answer.

Is it a misconfiguration on my part, or something to do with django version maybe? 

Edit:
did some digging, first turns out the bug only happen on Chromium, in Firefox it is working, I still need to check in Chrome.

Breakpoint in alpine give the following issue on json parsing.

```js
 function d(t, e) {
        return JSON.parse(e.getItem(t, e))
    }
```
with value
`t = "theme", e = Storage {theme: 'auto', length: 1}`

**Comment by lahuindai** [comment]
Getting the same in Brave on linux

**Comment by guntribam** [comment]
Same here chrome on linux

**Comment by lukasvinclav** [comment]
Hey, I just tested the app Chromium v113 on Arch and it works. Would you mind to check the demo site at unfoldadmin.com, if you can replicate an issue there as well?

**Comment by lahuindai** [comment]
Demo site works @lukasvinclav, any chance on getting whatever you did there into a release ?

**Comment by lukasvinclav** [comment]
On demo site there is a latest version downloaded by pip without any customization. Do you have public URL where we can debug your issue?

**Comment by samucancld** [comment]
Same here:
-  `Uncaught SyntaxError: Unexpected token 'd', "dark" is not valid JSON`
-  Chrome on windows 11 v113.0.5672.126
- python:3.11.3-alpine
- Django>=4.2.0,<4.3.0
- django-unfold>=0.6.3,<0.7.0

**Comment by Macktireh** [comment]
Same here:

- Windows 11
- Chrome 113
- python (pyenv) = "^3.10"
- poetry = 1.4.2
- django = "^4.2.1"
- django-unfold = "^0.6.3"

```
Uncaught SyntaxError: Unexpected token 'l', "light" is not valid JSON
    at JSON.parse (<anonymous>)
    at g (alpine.persist.js:1:479)
    at t.interceptor.r.as.n (alpine.persist.js:1:116)
    at Object.initialize (alpine.js:1:4158)
    at alpine.js:1:3986
    at Array.forEach (<anonymous>)
    at r (alpine.js:1:3837)
    at ve (alpine.js:1:4059)
    at alpine.js:5:31296
    at Function.<anonymous> (alpine.js:5:10902)
```

**Comment by lukasvinclav** [comment]
New version has been released fixing this issue.
