### ISSUE TITLE
Complete Example for Custom admin pages

### ISSUE THREAD

**Issue by raayu83** [unfoldadmin/django-unfold#641]
**Do you have any examples?**

The Readme Section "Custom admin pages" seems incomplete.
- The model admin is not registered with any model in the examples
- in my experiments, even when the model admin registered with an existing model, the CBV is not added to the django unfold menu. There are probably some more steps necessary.

**Is it a third party application feature request?**

No

**Describe your feature request**

If possible, please complete the Readme Section for "Custom admin pages" (or if it isn't working because of a bug, a fix would be great)

**Comment by lukasvinclav** [comment]
Feel free to propose new PR improving the documentation. I will be happy to review it.
