### ISSUE TITLE
New feature: extra bottom line with column(s) totals

### ISSUE THREAD

**Issue by caiocarrara** [unfoldadmin/django-unfold#642]
I think it would be useful if we could, on the model listing, define specific columns to have totals (sum result with each of the row values for that column) in an extra bottom line. As I hope the example below can show.

These columns total (or sums) would be even more useful when showing filtered results.

I couldn't find any other app to do it and properly integrate with unfold. If anybody knows any way of doing it, I would appreciate as well. 

**Do you have any examples?**
![image](https://github.com/user-attachments/assets/92456bef-b857-431a-b072-0e985d8b2a91)

**Is it a third party application feature request?**
No.

Thanks for your amazing work 👏

**Comment by lukasvinclav** [comment]
Feature sounds great but there are no resources to implement such a functionality into Unfold yet. I'm closing this ticket but this can be a nice third party plugin.
