### ISSUE TITLE
django-tinymce HTMLField rendering as plain TextField

### ISSUE THREAD

**Issue by hmesfin** [unfoldadmin/django-unfold#647]
**What version of Unfold are you using?**

0.33.0

**What version of Django are you using?**

4.2.14

**What browser are you using?**

Same behavior on Chrome and Firefox

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Repository with reproduced bug**

https://github.com/hmesfin/django-unfold-tinymce

**Describe your issue**

django-tinymce HTMLField rendering as plain text field in DJango Admin using django-unfold
![Add-My-Model-Django-site-admin](https://github.com/user-attachments/assets/8cbeefbd-7f60-44d2-b1f7-2cdc8ddc9c89)

**Comment by sabbir2609** [comment]
Well, I've used form field override with the widget in admin.py. It works.

**Comment by hmesfin** [comment]
Yeah, didn't have to override in Django Admin, as the model's attributes are automatically inherited. Thanks for the pointer about overriding it, and yes it works.
