### ISSUE TITLE
Dialog for Tailwind CSS

### ISSUE THREAD

**Issue by Joangaes** [unfoldadmin/django-unfold#648]
**Do you have any examples?**

Implementing a Dialog component to be used with Tailwind and that can be extended with forms.

**Is it a third party application feature request?**

No

**Describe your feature request**

A component that allows you to use a dialog (modal) for usability in other parts of the application.

**Comment by lukasvinclav** [comment]
Yes, this is going to be pretty complex to implement correctly. This is not in the pipeline right now unless you are interested in custom work. If somebody from the community is able to create working demo which will be able to somehow address replacement of default Django window popups as well, I can help with the implementation.

**Comment by Joangaes** [comment]
@lukasvinclav I could help. Also on the pipeline, is there any specific way to contact you? I like this project very much and would love to contribute.
