### ISSUE TITLE
Fieldsets with tab class are not shown as tab

### ISSUE THREAD

**Issue by raayu83** [unfoldadmin/django-unfold#649]
**What version of Unfold are you using?**

For example: main (2024-08-02 11:00 Berlin Timezone)

**What version of Django are you using?**

For example: 4.2.14

**What browser are you using?**

For example: Chrome 127.0.6533.89 

**Did you checked changelog/commit history, if the bug is not already fixed?**

For example: Yes

**Did you searched other issues, if the bug is not already fixed?**

For example: Yes

**Repository with reproduced bug**

I integrated it into to the server example in the following branch:
https://github.com/raayu83/django-unfold/blob/tabs/tests/server/example/admin.py

**Describe your issue**

When adding the ` "classes": ["tab"]` option to fieldsets as shown in the docs, the fieldset is not shown in a tab but just as usual.

**Comment by lukasvinclav** [comment]
I checked the functionality in the demo project and it seems to work okay. Am I missing something? Can you provide screenshot?

https://demo.unfoldadmin.com/admin/formula/user/1/change/

**Comment by khaled5321** [comment]
Try changing
```python
    fieldsets = (
        (
            None,
            {
                "fields": [
                    "name",
                ]
            },
        ),
        (
            "Permissions",
            {
                "classes": ["tab"],
                "fields": [
                    "permissions",
                ]
            },
        )
    )
```
To:
```python
    fieldsets = (
        (
            "General",
            {
                "fields": ["name"],
                "classes": ["tab"],
            },
        ),
        (
            "Permissions",
            {
                "classes": ["tab"],
                "fields": [
                    "permissions",
                ]
            },
        )
    )
```

**Comment by lukasvinclav** [comment]
@raayu83 There is no support for grouping multiple fieldsets under one tab in Unfold.
