### ISSUE TITLE
[New Unfold Widget] CheckboxMulitple

### ISSUE THREAD

**Issue by VaZark** [unfoldadmin/django-unfold#651]
Django has a form widget to accept multiple values for the same name using `forms.CheckboxSelectMultiple` and `forms.MultipleChoiceField.` It would be great to have an unfold widget that replicates `CheckboxSelectMultiple` with unfold's switches that we can just import and plug into a `MultipleChoiceField` field

**How to replicate it**

The code for the form field

```python
class ModelAdminForm(forms.ModelForm):
    payment_options = forms.MultipleChoiceField( choices=ChoiceList.choices, widget=forms.CheckboxSelectMultiple)

@admin.register(ObjectModel)
class ObjectModelAdmin(ModelAdmin):
    form = ModelAdminForm
```

![image](https://github.com/user-attachments/assets/88abd120-a02f-494a-8a97-7897b43618fe)

For example: link or screenshot

**Is it a third party application feature request?**
No

**Comment by lukasvinclav** [comment]
Fixed in #721. New widget `unfold.widgets.UnfoldAdminCheckboxSelectMultiple`
