### ISSUE TITLE
[Feature Request] Replace Filter list with a select field

### ISSUE THREAD

**Issue by VaZark** [unfoldadmin/django-unfold#652]
**Is it a third-party application feature request?**
 No

Use select instead of hyperlink list for list filters. When the choices are long, it takes up a lot of space that can be used to list other filters in the sidebar

**Before**
![image](https://github.com/user-attachments/assets/2b9efc15-ceec-4636-a667-83ddbe3da90c)

**After**
![image](https://github.com/user-attachments/assets/b5213ce2-948b-4a69-888d-14eb429966a2)

Template to update : `admin/filter`

The code for the screenshot above
```html
{% load i18n %}
<script type="text/javascript">var go_from_select = function(opt) { window.location = window.location.pathname + opt };</script>
<div data-filter-title="{{ title }}">
    <h3>{% blocktranslate with filter_title=title %} By {{ filter_title }} {% endblocktranslate %}</h3>
    <ul>
        <li>
            <select style="width: 100%"
                    onchange="go_from_select(this.options[this.selectedIndex].value)">
                {% for choice in choices %}
                    <option {% if choice.selected %}selected="selected"{% endif %}
                            value="{{ choice.query_string|iriencode }}">{{ choice.display }}</option>
                {% endfor %}
            </select>
        </li>
    </ul>
</div>
```

**Comment by lukasvinclav** [comment]
Dropdown filtes are already implemented, please check documentation for more info:

https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#dropdown-filters
