### ISSUE TITLE
Action select texts not being translated

### ISSUE THREAD

**Issue by caiocarrara** [unfoldadmin/django-unfold#653]
**What version of Unfold are you using?**

0.34.0

**What version of Django are you using?**

For example: 5.0.7

**What browser are you using?**

For example: Firefox 128.0.3

**Did you checked changelog/commit history, if the bug is not already fixed?**

For example: Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes. It seems this is related to the following issue that was closed as "completed". But I'm still seeing the same issue with the version 0.34.0.

- https://github.com/unfoldadmin/django-unfold/issues/618

**Describe your issue**

Text not being properly translated on the action select component and the action button (_Run_). In the examples below, `pt-BR` is the option set on settings: `LANGUAGE_CODE = "pt-BR"`

![image](https://github.com/user-attachments/assets/6a4cfd66-21f1-49d9-b871-2b2608e1486a)

![image](https://github.com/user-attachments/assets/48725959-f17a-4413-a911-33b4250b0046)

**Comment by lukasvinclav** [comment]
I checked the codebase and it seems all strings mentioned in your comment are properly wrapped in translation function. Please check if you translated all strings.
