### ISSUE TITLE
Sidebar Items auto active multiple 

### ISSUE THREAD

**Issue by sabbir2609** [unfoldadmin/django-unfold#654]
```
Version Info: 
Unfold: 0.33.0
Django: 5.0.7
Chrome: 127.0.6533.84
```

- Checked changelog/commit: Yes
- Searched other issues: Yes
- Repository with reproduced bug : https://github.com/sabbir2609/plantx-be

# Issue: 

I made the sidebar with several models. When I select an item it automatically selecting/active multiple items.
It's happening for top 2/3 section of sidebar Items.

![Screenshot_20240804-045400.png](https://github.com/user-attachments/assets/26254659-e564-4a2f-b3e3-0f6a0513dd75)

This is a screenshot of my phone browser but it's also happening on my desktop chrome.

**Comment by lukasvinclav** [comment]
I think I will need a minimal Django project where it will be possible to reproduce the issue. Your project is big and you have a lot of dependencies so it will take quite some time for me to do a proper investigation.

**Comment by lukasvinclav** [comment]
Closing due to lack of information.

**Comment by andymathieson** [comment]
I too am having this issue.

If you look at the sidebar code below you will see I have an app with 4 different models. They are all settings pages. 


![Image](https://github.com/user-attachments/assets/2480d9a8-0fda-45dd-80d7-baba5d14c814)


When I click on 'Settings' in my navigation, Settings is correctly active.

![Image](https://github.com/user-attachments/assets/fb3c6225-875b-4cf3-a58b-c21daf3148e3)

When I click on 'API Keys & Plugins' both this and Settings are active.

![Image](https://github.com/user-attachments/assets/0f0805c7-edea-40dc-ba44-29009b1fad04)

When I click on 'Social Channels' this and the the previous two are active.

![Image](https://github.com/user-attachments/assets/820e1444-373e-4a41-8c75-50c474cae1fb)

When I click on 'Developer' All links are active.

![Image](https://github.com/user-attachments/assets/9e4c1b4a-2ed4-4ee9-92cc-9d78e847416e)

Using the 'active' keyword has no effect.

**Comment by andymathieson** [comment]
I think I have found the root of the issue.

When you also use the 'tab' system then the issue occurs.

![Image](https://github.com/user-attachments/assets/4233c62e-4e23-4db6-a92d-57772760be89)

If I comment out the tabs section in my config then the sidebar nav works properly.

![Image](https://github.com/user-attachments/assets/af293d19-ff2f-4729-bd8a-db1e9cd4875f)
