### ISSUE TITLE
Cannot use custom admin site "NoReverseMatch at /admin/"

### ISSUE THREAD

**Issue by bubblegumsoldier** [unfoldadmin/django-unfold#658]
**What version of Unfold are you using?**

0.34.0

**What version of Django are you using?**

5.0.7

**What browser are you using?**

Chrome 123

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Repository with reproduced bug**

https://github.com/bubblegumsoldier/django-unfold-custom-admin-example/tree/main

**Describe your issue**

I would like to be able to register my custom `AdminSite` like this:

```python
from django.contrib import admin
from django.contrib.auth.models import User
from unfold import admin as unfold_admin


class CustomAdminSite(admin.AdminSite):
    def get_urls(self):
        urls = super(CustomAdminSite, self).get_urls()
        custom_urls = []
        return custom_urls + urls


class UserAdmin(unfold_admin.ModelAdmin):
    model = User


custom_admin_site = CustomAdminSite(name="snh2_dj_admin")
custom_admin_site.register(User, UserAdmin)
```

I can then register it like this:

```python
from django.urls import path
from custom_admin.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),
]
```

That way I can specify what fields I would like to show in which django admin and can serve different types of admins under different routes very easily. It is a default functionality of django and I have been using it in multiple projects. That way if I have two user-groups I can build dedicated admins under different urls for each of them showing them different fields.

However, when I open the django app I get this issue:

```
NoReverseMatch at /admin/
Reverse for 'toggle_sidebar' not found. 'toggle_sidebar' is not a valid view function or pattern name.
```

Thanks 👍

**Comment by lukasvinclav** [comment]
Did you checked Formula repository? It implements custom admin site and it works.

**Comment by bubblegumsoldier** [comment]
Will check right away, thanks!

**Comment by bubblegumsoldier** [comment]
https://github.com/unfoldadmin/django-unfold/pull/659

Created PR
