### ISSUE TITLE
Datetime Picker support for forms

### ISSUE THREAD

**Issue by ramazantarakci** [unfoldadmin/django-unfold#660]
When you design a form with a datetime field using Django forms, the datetime field in that form will be presented to you as a textfield with the same design as in the default admin pages.

However, the datetimeshortcuts support provided by the django admin pages will not be available in the form you design.
for example:

```
../forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime

class SampleForm(forms.Form):
  name = forms.CharField(label="Name")
  start_at = forms.DateTimeField(label="Start At")
  end_at = forms.DateTimeField(label="End At", widget=AdminSplitDateTime)
```

![django-default-with-widget](https://github.com/user-attachments/assets/86ef27ae-1775-4c96-a2e4-855d99634cdb)

Similarly, when we use a datetime field based on UnfoldAdminSplitDateTimeWidget, datetimeshortcuts support is not provided.

```
../forms.py
from django import forms
from unfold.widgets import UnfoldAdminSplitDateTimeWidget, UnfoldAdminSplitDateTimeVerticalWidget
class SampleForm(forms.Form):
    start_date = forms.DateField(label='From Date', widget=UnfoldAdminSplitDateTimeWidget)
    end_date = forms.DateField(label='To Date', widget=UnfoldAdminSplitDateTimeVerticalWidget)

```

I can create a custom widget with including  datetimeshortcuts support (and i already made it.) but this is not best solution i thought. 
![unfold-not-working](https://github.com/user-attachments/assets/731eea80-8cea-4415-a610-df5b863b9a74)

I think unfold can support this feature as default approach.

for example when unfold support datetimeshortcuts will be image like this will appear.

![undold-working](https://github.com/user-attachments/assets/01a47ed5-18f3-4200-b16a-2256b8efa325)

Finally, I will add the link to the branch that adds this feature here.

**Comment by Joangaes** [comment]
I think this exactly is needed. Nice job @ramazantarakci

**Comment by lukasvinclav** [comment]
I'm closing this issue because of ignored issue templated. If you want, you can recreate the issue with all necessary information.
