### ISSUE TITLE
Autocomplete field in inline list shows default django buttons

### ISSUE THREAD

**Issue by bubblegumsoldier** [unfoldadmin/django-unfold#662]
**What version of Unfold are you using?**

0.34.0

**What version of Django are you using?**

For example: 5.0.8

**What browser are you using?**

Chrome 126

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes, I found [this](https://github.com/unfoldadmin/django-unfold/issues/604), not sure if its related, but I at least got a reproducible version

**Repository with reproduced bug**

I repurposed an old github repo so ignore the repo name pls:

https://github.com/bubblegumsoldier/django-unfold-custom-admin-example

**Describe your issue**

If I have autocomplete_fields in inlines, then the old buttons are still shown. It looks weird. I also checked formula and I didn't find a case where in an inline there was an autocomplete_field, so maybe that specific case was overlooked.

![image](https://github.com/user-attachments/assets/ccb31fb9-e02a-4eb4-adb4-636ea9e56b54)

**Comment by omargawdat** [comment]
I think the issue is due to using the default admin instead of unfold in TabularInline
### using default admin 
```
from unfold.admin import ModelAdmin

class CustomGroupToUserInline(admin.TabularInline):
    model = CustomGroupToUser
    autocomplete_fields = ['user', 'group']
    tab = True
```

### using unfold admin 
```
from unfold.admin import TabularInline

class CustomGroupToUserInline(TabularInline):
    model = CustomGroupToUser
    autocomplete_fields = ['user', 'group']
    tab = True
```
