### ISSUE TITLE
How do I cahnge admin user add form header? (without custom template)

### ISSUE THREAD

**Issue by sabbir2609** [unfoldadmin/django-unfold#665]
```
Version Info: 
Unfold: 0.33.0
Django: 5.0.7
Chrome: 127.0.6533.84
```

![user](https://github.com/user-attachments/assets/ca88aefa-91b8-437d-af74-cc558d43f58c)

I have a custom user model that takes email instead of username.

**Comment by eamigo86** [comment]
Hi @sabbir2609, This text comes from a Django template called [**add_form.html**](https://github.com/django/django/blob/f16a9a556fb4225f9094048614f4fcec3db7e067/django/contrib/admin/templates/admin/auth/user/add_form.html#L6). The good news is that it's marked for translation, so if you add internationalization to your project and translate this text with the text you want, it should be enough.

**Comment by lukasvinclav** [comment]
@eamigo86 is right. This is coming from original Django template. If you want you can create a new PR fixing this issue. I will be happy to review it.

**Comment by lukasvinclav** [comment]
If you are still interested in a fix, please create a PR.
