### ISSUE TITLE
Sidebar max width

### ISSUE THREAD

**Issue by sepehrsafa** [unfoldadmin/django-unfold#666]
Hi
Please add the option of sidebar max width, the current sidebar width takes a lot of space on mobile and smaller monitors when its open
It would be nice to have a max width option so the side bar would stay small and the text would wrap to the next line
Thanks

**Comment by lukasvinclav** [comment]
I'm closing this issue because of ignored issue templated. If you want, you can recreate the issue with all necessary information.
