### ISSUE TITLE
Broken styles when using Inlines

### ISSUE THREAD

**Issue by MarketingForPeople** [unfoldadmin/django-unfold#670]
Django - 5.0.7
Unfold - 0.34.0
Browser - Yandex Browser(Chromium)
Broken styles when using Inline. The elements on the right are stuck together. And unreadable text in the fields.
![2024-08-11_20-48-10](https://github.com/user-attachments/assets/aaa65114-b823-443c-a55b-67ab89865c21)

**Comment by hernansaa** [comment]
Hi @MarketingForPeople i am having similar problems. Did you get it fixed? thanks.

**Comment by waynehamadi** [comment]
for anyone having the same issue: make sure you use django unfold's admin for inlines
```
from unfold import admin 

class BookInline(admin.TabularInline):
    model = Book
    extra = 1
```
