### ISSUE TITLE
datetimeshortcuts support in forms

### ISSUE THREAD

**Issue by ramazantarakci** [unfoldadmin/django-unfold#672]
**Issue Description:**

When you design a form with a datetime field using Django forms, the datetime field in that form will be presented to you as a textfield with the same design as in the default admin pages.
However, the datetimeshortcuts support provided by the django admin pages will not be available in the form you design. 
(django-unfold also uses same approach.) 
UnfoldAdminSplitDateTimeWidget not supports datetimeshortcuts.

**Do you have any examples?**

For example:
```
from django import forms
from unfold.widgets import UnfoldAdminSplitDateTimeWidget, UnfoldAdminSplitDateTimeVerticalWidget
class SampleForm(forms.Form):
    from_date = forms.SplitDateTimeField(label='From Date', widget=UnfoldAdminSplitDateTimeWidget)
    to_date = forms.SplitDateTimeField(label='To Date', widget=UnfoldAdminSplitDateTimeVerticalWidget)
```
![unfold-not-working](https://github.com/user-attachments/assets/731eea80-8cea-4415-a610-df5b863b9a74)

I think unfold can support this feature as default approach.
for example when unfold support datetimeshortcuts will be image like this will appear.
![undold-working](https://github.com/user-attachments/assets/01a47ed5-18f3-4200-b16a-2256b8efa325)

**Is it a third party application feature request?**
No, it is not.

**In case of third party application, when it was updated last time?**
It is not a third-party application feature request.

**Describe your feature request**
This problem occurs because the js files in the Django administration pages are not included into html when creating the forms.
also UnfoldAdminSplitDateTimeVerticalWidget  styles is not compatible with DateTimeShortcuts.js

**Proposed Solution:**
i created a pull request already. please check.  #661 

**Additional Context:**
This issue, can prevent developers who want to speed up their work with Django forms from needing to use a separate package for datetime fields.

**Comment by lukasvinclav** [comment]
Hey, here is the full documentation how to implement these fields in custom form:

https://unfoldadmin.com/docs/actions/action-form-example/
