### ISSUE TITLE
Select2 is not working

### ISSUE THREAD

**Issue by SpirikStar** [unfoldadmin/django-unfold#676]
<!- Please provide all the information listed below. Without detailed information, it is difficult for us to help you, and your question will be closed. -->

**Which version of Unfold are you using?**

0.35.0

**Which version of Django are you using?**

5.0.8

**Which browser do you use?**

Firefox 129.0

**Have you checked the change/commit log if the error has not been fixed yet?**

Yes

**Have you looked for other problems if the bug has not been fixed yet?**

Yes

**Describe your problem**

The documentation does not provide information on how to use Select2. As I understand it, it should work by default. I'm checking on related ForeignKey models
<img width="846" alt="Снимок экрана 2024-08-13 в 13 19 06" src="https://github.com/user-attachments/assets/fe484d67-ea42-4b5f-a74b-f2a3b248e36d">

**Comment by marcpicaud** [comment]
Hi,

To enable Select2 you need to set ModelAdmin.autocomplete_fields. See [Django docs](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.autocomplete_fields)
