### ISSUE TITLE
Responsive problems

### ISSUE THREAD

**Issue by paulocoutinhox** [unfoldadmin/django-unfold#679]
**What version of Unfold are you using?**

0.35.0

**What version of Django are you using?**

For example: 5.0

**What browser are you using?**

For example: Chrome

**Did you checked changelog/commit history, if the bug is not already fixed?**

For example: Yes 

**Did you searched other issues, if the bug is not already fixed?**

For example: Yes

**Repository with reproduced bug**

Oficial demo

**Describe your issue**

When i run on mobile, i get responsive problems:

<img width="388" alt="image" src="https://github.com/user-attachments/assets/f3f32b40-d33f-4097-8fb0-cd762e473f93">

Demo:
https://demo.unfoldadmin.com/admin/formula/driver/56/change/

**Comment by lukasvinclav** [comment]
Hi, I just merge into main PR #690 fixing this issue. Feel free to test it and let me know.

**Comment by paulocoutinhox** [comment]
Hi,

It still with problems:

<img width="389" alt="image" src="https://github.com/user-attachments/assets/1308baf8-b66a-4388-a48f-9eaa3527fe9e">

**Comment by lukasvinclav** [comment]
It is just in main, not on demo site. You can test it locally by pulling most recent changes.

**Comment by paulocoutinhox** [comment]
<img width="387" alt="image" src="https://github.com/user-attachments/assets/f7a6221f-d703-4cab-b975-c6d31de11def">

Ref: https://demo.unfoldadmin.com/admin/formula/driver/55/change/

You need review all pages using chrome with mobile enabled.

**Comment by paulocoutinhox** [comment]
Hi,

New responsive problems.

Home of admin:
<img width="504" alt="Image" src="https://github.com/user-attachments/assets/bba2ed19-4e1a-4f23-897d-a54f1f61fec1" />

Formula race:

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/75225ec6-c6d2-4183-8a6d-010bfa672d19" />

On color change or site:

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/1562734e-d959-48d8-893b-193eb428176b" />
