### ISSUE TITLE
KeyError at /admin/auth/user/ 'actions_row'

### ISSUE THREAD

**Issue by justinqian42** [unfoldadmin/django-unfold#68]
Hi,

Maybe this is a silly question but I've tried my best before posting it.......

After a fresh install with python 3.11.3 and django 4.2.1, I managed to make unfold run by adding the app in settings.py.
All looks good until I click on "Users" or "Groups". A KeyError comes out on 'actions_row'.
 
<img width="1727" alt="Screenshot 2023-05-15 at 7 49 09 pm" src="https://github.com/unfoldadmin/django-unfold/assets/49712643/62a63cd0-951f-44e9-942f-09155e8a36d2">
<img width="1727" alt="Screenshot 2023-05-15 at 7 49 29 pm" src="https://github.com/unfoldadmin/django-unfold/assets/49712643/eab13cf5-2765-4043-a2b8-38a2bbe2b15b">

Looks like the default context doesn't include the actions_row key pair somehow. Is it an attribute brought by unfold?

Thank in advance!
Justin

**Comment by lukasvinclav** [comment]
Hi, which version of theme are you using? Can you create sample repo when we can replicate issue?

**Comment by justinqian42** [comment]
Thanks @lukasvinclav !
I've uploaded the codes to [https://github.com/justinqian42/testapp](https://github.com/justinqian42/testapp).
The unfold version is the latest 0.6.2

What I did is quite simple.
1. Create a virtual env.
2. Install django 4.2.1 and django-unfold 0.6.2 with pip.
3. Start a new django project.
4. Add unfold into settings.py
5. Make migrations and migrate with manage.py
6. Run server.
7. Open http://127.0.0.1:8000/admin
8. Click on Users or Groups. The KeyError pops out.

**Comment by justinqian42** [comment]
The username/password is unfold/unfold.
Computer is Macbook Pro 16 with M1 chips.
Also tested on a windows machine and got the same.

**Comment by lukasvinclav** [comment]
Is it possible to make your testing repo public?

**Comment by justinqian42** [comment]
> Is it possible to make your testing repo public?

Done.

**Comment by samucancld** [comment]
Same error here having:
- python:3.11.3-alpine
- Django>=4.2.0,<4.3.0
- django-unfold>=0.6.3,<0.7.0

**Comment by justinqian42** [comment]
> New version has been released fixing this issue.

Thank you so much!
