### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by JahongirHakimjonov** [unfoldadmin/django-unfold#681]
![photo_2024-08-15_13-22-00](https://github.com/user-attachments/assets/707aaca9-46ae-4b79-bb2b-396cc52bfc2e)

If possible, you should put a setting to change the language here, I couldn't find it in the current version.

**Comment by vasylkyselytsia** [comment]
https://github.com/unfoldadmin/django-unfold/issues/534

**Comment by lukasvinclav** [comment]
@JahongirHakimjonov implemented in #854
