### ISSUE TITLE
TabularInline: use one row per object (instead of two) to facilitate sorting

### ISSUE THREAD

**Issue by marcpicaud** [unfoldadmin/django-unfold#683]
**Is it a third party application feature request?**

No

**Describe your feature request**

Unfold's TabularInline template creates 2 rows per object (1 for the name, 1 for the fields) :

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/6a170dbb-b8c3-437e-90f1-eb7afac57ebb">

Django's TabularInline creates 1 row per object

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/f7ae29c2-1845-43f8-8fb2-0ab7ac39fe3d">

This is not really a bug _per se_, but all 3rd party plugins offering a sortable functionality are expecting 1 row per object, and thus they are not compatible with Unfold. Wouldn't it be better to stick with native Django's structure ?

**Possible solutions**
- Refactor Unfold TabularInline's template so that the object name is included in the same row as the fields
- Implement a sortable feature in Unfold ? 

Let me know what you think, I could draft a PR for either

**Comment by marcpicaud** [comment]
For example, this plugin: https://github.com/matthiask/django-admin-ordering

I just tried native Django and a very long title. The approach Django uses to handle this is:
* The title is placed inside a table cell (`<td>`).
* The cell's `width` is set to 0.
* The title itself is wrapped in a child paragraph (`<p>`), which is styled with `position: absolute`
* The rest of the row is displayed with a `padding-top` to offset the title's height.

<img width="2632" alt="Screenshot 2024-08-19 at 21 22 41" src="https://github.com/user-attachments/assets/d0884048-768b-410e-a970-1441927986db">

**Comment by lukasvinclav** [comment]
Yeah, I see it now. If you can draft a PR, I will be happy to review it. 

Regarding sorting functionality, I will try to take a look and prepare built-in MVP directly in Unfold without any third party dependencies.

**Comment by lukasvinclav** [comment]
@marcpicaud are you willing to take a look on it and draft a PR fixing multiple rows per one record?

**Comment by marcpicaud** [comment]
@lukasvinclav
Yes, sir ! Apologies for the delay, I've been quite busy lately. Will keep you posted by next week

**Comment by lukasvinclav** [comment]
Closed in favor of #785 which will introduce own inline sorting in Unfold
