### ISSUE TITLE
TabbedTranslationAdmin overflows if there are many languages available

### ISSUE THREAD

**Issue by magnuslo** [unfoldadmin/django-unfold#685]
**What version of Unfold are you using?**
0.35.0

**What version of Django are you using?**
5.0

**What browser are you using?**
Arc

**Did you checked changelog/commit history, if the bug is not already fixed?**
Yes

**Did you searched other issues, if the bug is not already fixed?**
Yes

**Describe your issue**
When the amount of languages included in django-modeladmin are many, the TabbedTranslationAdmin tab buttons expand into the abyss.
<img width="1180" alt="Screenshot 2024-08-16 at 16 19 19" src="https://github.com/user-attachments/assets/db959c05-f9bd-4bd3-9e8b-f8844c4fd6b9">

Adding `.max-w-4xl` and `.overflow-scroll` to the parent seems to be a nice solution:
![ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/560778a6-ed41-4499-a6ab-1180f3878d65)

**Comment by lukasvinclav** [comment]
@magnuslo How it is displayed in default admin?

**Comment by lukasvinclav** [comment]
I will be happy to review the PR in case you are interested.
