### ISSUE TITLE
URLField widget: display a clickable link when a value is set

### ISSUE THREAD

**Issue by marcpicaud** [unfoldadmin/django-unfold#694]
**Is it a third party application feature request?**
No

**Describe your feature request**

URLField widget could display an actual link

**Do you have any examples?**

Native Django admin : 
<img width="788" alt="image" src="https://github.com/user-attachments/assets/89ced4b7-bb75-47a5-b0c0-d3c5e1b6f93e">

**Comment by khaled5321** [comment]
Hi @lukasvinclav, I have created a draft PR for this issue #723. Can you review it?
