### ISSUE TITLE
Wrong url parameters with MultipleChoicesDropdownFilter

### ISSUE THREAD

**Issue by esolder** [unfoldadmin/django-unfold#695]
**What version of Unfold are you using?**

0.36.0 

**What version of Django are you using?**

4.2

**What browser are you using?**

Firefox 129.0.1

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Describe your issue**

I'm using MultipleChoicesDropdownFilter. 

Code example:

```python
@admin.register(Project)
class ProjectAdmin(ModelAdmin):
    list_filter_submit = True
    list_filter = [('service', MultipleChoicesDropdownFilter)]
```

![Изображение_21-08-2024_18-07-59](https://github.com/user-attachments/assets/53bdfee6-a070-4c07-a1b4-f193ff8ca18f)

After choosing multiple values and pressing "Apply filters", I'm getting the wrong query parameters.

![Изображение_21-08-2024_18-07-38](https://github.com/user-attachments/assets/439ce8a0-16fc-412d-875b-0a59a7d9a6e3)

After applying and opening the filters menu, I see the error "Enter a list of values"

![Изображение_21-08-2024_18-08-16](https://github.com/user-attachments/assets/1dc64699-d979-4422-bb46-162edd81cc1f)

If I understand correctly, the parameters in this situation should be:

```
?service__in=accounting,economic
```

**Comment by germanp** [comment]
I found this isn't fixed. It is working like the issue describes.
