### ISSUE TITLE
"Run" Button Missing in Action List After Adding SortableAdminMixin

### ISSUE THREAD

**Issue by DivyanshuJhamtani** [unfoldadmin/django-unfold#699]
**What version of Unfold are you using?**

0.34.0

**What version of Django are you using?**

4.2.6

**What browser are you using?**

Chrome 128.0.6613.84 

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes 

**Did you searched other issues, if the bug is not already fixed?**

Yes 

**Repository with reproduced bug**
. 

**Describe your issue**

I'm encountering an issue with Django admin when using the SortableAdminMixin. Specifically, after adding SortableAdminMixin to my Django admin configuration, the "Run" button for performing bulk actions, such as deleting multiple rows, is no longer visible.

Here's a brief overview of the problem:

Context: I am using SortableAdminMixin to enable sortable functionality in the Django admin interface. This mixin is designed to allow for drag-and-drop sorting of list items.

Problem: After incorporating SortableAdminMixin, the "Run" button, which is typically available for executing bulk actions (e.g., deleting selected rows), is no longer displayed in the action list dropdown menu.

Impact: This issue prevents users from performing batch actions on selected rows, which affects the usability and functionality of the admin interface for managing data efficiently.

Steps to Reproduce:

Add SortableAdminMixin to your admin class.
Observe the admin interface where the bulk action dropdown is displayed.
Notice that the "Run" button is missing from the action list.
Any guidance or solutions to resolve this issue would be greatly appreciated.

**Comment by thakryptex** [comment]
I have the same issue.
In the list view, when I select some rows and want to run some action, there is no "Run" button there.
If I disable unfold in the settings, it appears again (as it usually exists in the original django admin).

And it's not a duplicate of #683

**Comment by SAGAR-TAMANG** [comment]
facing same issue.

**Comment by lukasvinclav** [comment]
@SAGAR-TAMANG please create a new issue describing your problem. Regarding SortableAdminMixin, this third party app is not officially supported in Unfold.

**Comment by Aniruddhyagoswami** [comment]
run button missing in unfold?why?how to fixed it

**Comment by SAGAR-TAMANG** [comment]
@Aniruddhyagoswami You will need to actually set the Admin Mixin or something then it works. Like, currently you have done it half-way through, but you have not set everything. I forgot the exact code that fixed it, but yeah something is missing (i fixed it quite a long time ago).

**Comment by bkocii** [comment]
dont know if its the same issue, this helped for me:
importing the ModelAdmin from unfold and adding it to the class..

from unfold.admin import ModelAdmin
class CustomUserAdmin(UserAdmin, ModelAdmin):
