### ISSUE TITLE
Date widget opens to the right expanding viewport

### ISSUE THREAD

**Issue by guntribam** [unfoldadmin/django-unfold#70]
this is before opening the date widget

![image](https://github.com/unfoldadmin/django-unfold/assets/7470516/7f2ae769-f26d-4efb-8d56-c81d3e44a7e6)

this is after

![image](https://github.com/unfoldadmin/django-unfold/assets/7470516/33894b42-0c9d-4af8-b07c-f317c1b23fcd)

What do you think if this kind of widget opens to the left?

**Comment by lukasvinclav** [comment]
hey, thanks for report. You are right, in default admin calendar has "modal" experience on mobile resolution. I will try to take a look on it.

**Comment by lukasvinclav** [comment]
New release will contain new experience fixing this behavior. Thanks
