### ISSUE TITLE
unfold features

### ISSUE THREAD

**Issue by Ranjithkumar8489** [unfoldadmin/django-unfold#701]
unfold 0.36.0
latest chrome

I am having trouble with the unfold.import_export functionality. Specifically, I am encountering issues with how to use or implement this feature effectively. Could you provide guidance or examples on how to properly write and utilize unfold.import_export?

**Comment by YashitM** [comment]
You can refer to [https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#django-import-export](https://github.com/unfoldadmin/django-unfold?tab=readme-ov-file#django-import-export) for an example use case.

**Comment by lukasvinclav** [comment]
The documentation has been moved and it is available here:

https://unfoldadmin.com/docs/integrations/django-import-export/
