### ISSUE TITLE
Broken layout for adding/updating element screen

### ISSUE THREAD

**Issue by bolinocroustibat** [unfoldadmin/django-unfold#705]
- Django 5.1.0
- Django-unfold 0.37.0
- Chrome 127.0.6533.122 ((arm64)
Couldn't find the issue in the already exiting issue.

The add/edit element screen seemes to have its layout broken - whatever element it is:

<img width="1803" alt="Screenshot 2024-08-29 at 11 48 10" src="https://github.com/user-attachments/assets/b8786457-dfdb-414f-9a14-db0bd3c8b46f">

Is it because this feature is not yet implemented?

Thanks for the amazing work!

**Comment by hernansaa** [comment]
I had the same problem. Make sure in admin.py that you are inheriting from the unfold model admin. If you can send the code from admins.py I might be able to help if this is the case.

**Comment by bolinocroustibat** [comment]
Of course, stupid me. Thank you.
