### ISSUE TITLE
Custom tabs in object changeview 

### ISSUE THREAD

**Issue by jckw** [unfoldadmin/django-unfold#709]
**Describe your feature request**

Is it possible to include custom tabs (e.g. a personalised dashboard) in the object changeview? This would be a great to visualise data for a user, or a driver (in the case of the formula demo project).

**Do you have any examples?**

The tab would appear here and would be fully styleable like the dashboard is.

![CleanShot 2024-08-30 at 08 39 31@2x](https://github.com/user-attachments/assets/8fded6fe-be12-42b6-bb8c-4c211dc17079)

**Is it a third party application feature request?**

No

**Comment by ebertti** [comment]
Hi @jckw 

your suggestion is part of my suggestion too :) 

take a look https://github.com/unfoldadmin/django-unfold/issues/708

**Comment by jckw** [comment]
I actually found a way to do this with a dummy model:

```python
class GraphData(models.Model):
    user = models.ForeignKey(Users, models.DO_NOTHING)

    class Meta:
        managed = False  # Django won't create a database table for this model
        default_permissions = ()  # Django won't create default permissions
```

```python
class CustomInline(TabularInline):
    model = GraphData
    tab = True
    verbose_name = "Graph"
    verbose_name_plural = "Graphs"
    can_delete = False
    max_num = 0
    extra = 1

    template = "admin/graph_inline.html"

    def has_add_permission(self, request, obj):
        return False

    def get_queryset(self, request):
        # Return an empty queryset
        return self.model.objects.none()

    def get_graph_data(self, obj):
        # Override this method in subclasses to provide graph data
        return {
            "labels": ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
            "data": [12, 19, 3, 5, 2, 3],
        }

    def get_formset(self, request, obj=None, **kwargs):
        formset = super().get_formset(request, obj, **kwargs)
        if obj:
            formset.graph_data = self.get_graph_data(obj)
        return formset
```

And then you can create the `graph_inline.html` template.

Pretty neat actually!

**Comment by marty0678** [comment]
This actually used to work, I just upgraded from 29.1 and found that in 0.31 this broke and removed my change view tabs. Technically these weren't tabs specific to the change view, but the model itself.

**Comment by justinqian42** [comment]
> I actually found a way to do this with a dummy model:
> 
> ```python
> class GraphData(models.Model):
>     user = models.ForeignKey(Users, models.DO_NOTHING)
> 
>     class Meta:
>         managed = False  # Django won't create a database table for this model
>         default_permissions = ()  # Django won't create default permissions
> ```
> 
> ```python
> class CustomInline(TabularInline):
>     model = GraphData
>     tab = True
>     verbose_name = "Graph"
>     verbose_name_plural = "Graphs"
>     can_delete = False
>     max_num = 0
>     extra = 1
> 
>     template = "admin/graph_inline.html"
> 
>     def has_add_permission(self, request, obj):
>         return False
> 
>     def get_queryset(self, request):
>         # Return an empty queryset
>         return self.model.objects.none()
> 
>     def get_graph_data(self, obj):
>         # Override this method in subclasses to provide graph data
>         return {
>             "labels": ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
>             "data": [12, 19, 3, 5, 2, 3],
>         }
> 
>     def get_formset(self, request, obj=None, **kwargs):
>         formset = super().get_formset(request, obj, **kwargs)
>         if obj:
>             formset.graph_data = self.get_graph_data(obj)
>         return formset
> ```
> 
> And then you can create the `graph_inline.html` template.
> 
> ```
> {% load i18n admin_urls %}
> 
> <div
>   {% if inline_admin_formset.opts.tab %}
>     x-show="activeTab == '{{ inline_admin_formset.opts.verbose_name|slugify }}'"
>   {% else %}
>     x-show="activeTab == 'general'"
>   {% endif %}
> >
>  
> </div>
> 
> <script src="https://cdn.jsdelivr.net/npm/chart.js" />
> 
> 
> <script>
>  // whatever you like
> </script>
> ```
> 
> Pretty neat actually!

OMG, you are a fxxking genius!!!

**Comment by lukasvinclav** [comment]
I can confirm what @ebertti wrote. This ticket is already part of #708 which needs to be implemented first. This will allow us to load chunks of HTML code before and after the form. Once this is done we need to be able to mark this part of content as tab.

**Comment by lukasvinclav** [comment]
@jckw custom templates support has been added to the most recent version. Does it help you?

https://unfoldadmin.com/docs/configuration/modeladmin/
