### ISSUE TITLE
Can't login into unfold demo with user demo and password demo

### ISSUE THREAD

**Issue by sandrop8** [unfoldadmin/django-unfold#720]
I tried to login into the demo on chrome and safari at https://demo.unfoldadmin.com/admin/login/?next=/admin/ but it did not proceed to the demo. It did not show an error. 

However if I try with a different password or username it shows an error. 

Would be happy if you either add in the readme how to successfully log in to the demo or clarify what could be the issue.

Thanks a bunch.

**Comment by lukasvinclav** [comment]
Hey, thanks for report. I redeployed the project and now it seems it works. Let me know, if you have any other issues.

**Comment by sandrop8** [comment]
Thanks, works now.
