### ISSUE TITLE
Tailwind CSS Issues?

### ISSUE THREAD

**Issue by ZairMahmood** [unfoldadmin/django-unfold#728]
**What version of Unfold are you using?**

0.37.0

**What version of Django are you using?**

5.0

**What browser are you using?**

Chrome 127

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Describe your issue**

I'm seeing a CSS Issue for misalignment of the checkbox column
![image](https://github.com/user-attachments/assets/fdcbab6c-ba1a-407a-bb64-ecc76b5299db)

I see that in some checkbox columns a `w-10` css class coming from tailwind is added but after deleting all my staticfile cache and reinstalling unfold then looking at styles.css in the inspector, the .w-10 class is missing. For some other pages, the checkbox column is really out of whack. Is there any additional command I'm supposed to execute to pull and build the tailwind css? 

This is more obvious on model pages that may only have 1-2 columns displayed

**Comment by lukasvinclav** [comment]
How can I replicate the issue?

**Comment by lukasvinclav** [comment]
No enough information how to replicate the issue.
