### ISSUE TITLE
UI stops working when manually focusing on an dropdown filter search field

### ISSUE THREAD

**Issue by Mohirbeck** [unfoldadmin/django-unfold#729]
**What version of Unfold are you using?**

0.38.0

**What version of Django are you using?**

4.2.15

**What browser are you using?**

Firefox Developer Edition 131.0b3 (aarch64)

**Did you checked changelog/commit history, if the bug is not already fixed?**

No

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Repository with reproduced bug**

[demo website](https://demo.unfoldadmin.com/admin/formula/race/) It can be checked on the demo website.

**Describe your issue**

Open [demo website](https://demo.unfoldadmin.com/admin/formula/race/)

<img width="1679" alt="Screenshot 2024-09-10 at 5 40 18 PM" src="https://github.com/user-attachments/assets/a460a763-bfb7-4ff7-8b6d-762e5c13c61a">

Open filters panel

<img width="1680" alt="Screenshot 2024-09-10 at 5 31 34 PM" src="https://github.com/user-attachments/assets/0d0ea166-c565-438e-a147-d9cfc420ea19">

Click By winner filter field

<img width="1680" alt="Screenshot 2024-09-10 at 5 33 03 PM" src="https://github.com/user-attachments/assets/b02c2321-5ec6-40e5-9119-52c954155c93">

Click on the search input

<img width="1680" alt="Screenshot 2024-09-10 at 5 33 41 PM" src="https://github.com/user-attachments/assets/dd110cea-7737-4236-92d6-bf32fb931048">

Write something

<img width="1680" alt="Screenshot 2024-09-10 at 5 33 51 PM" src="https://github.com/user-attachments/assets/b9a4f12d-109c-4979-96e2-84f5a43c5ffe">

**Comment by lukasvinclav** [comment]
Thanks for report. Fixed in #801.
