### ISSUE TITLE
Version 0.38.0: Navigation Sidebar not working with Firefox anymore

### ISSUE THREAD

**Issue by raayu83** [unfoldadmin/django-unfold#732]
**What version of Unfold are you using?**

0.38.0

**What version of Django are you using?**

4.2

**What browser are you using?**

Firefox 115.14.0.ESR

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Repository with reproduced bug**

The Demo at https://demo.unfoldadmin.com/ also has the issue

**Describe your issue**

The Navigation Sidebar is not displayed:
<img width="1598" alt="image" src="https://github.com/user-attachments/assets/13e53b73-e3b2-4fc9-b778-ebfcfb1aa590">

**Comment by lukasvinclav** [comment]
Did you refreshed your CSS? On Mac press CMD - SHIFT - R

**Comment by lukasvinclav** [comment]
Your Firefox version does not support :has()

https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility

**Comment by lukasvinclav** [comment]
If a company has a problem running Unfold under specific requirements, they are free to reach me through the contact form on the website so we can discuss how to optimise the software for their project.
