### ISSUE TITLE
Bug in all panel dark mode

### ISSUE THREAD

**Issue by josueygp** [unfoldadmin/django-unfold#734]
**What version of Unfold are you using?**

0.38.0

**What version of Django are you using?**

Django==5.1.1

**What browser are you using?**

Chrome Versión 128.0.6613.137

**Did you checked changelog/commit history, if the bug is not already fixed?**

Si

**Did you searched other issues, if the bug is not already fixed?**

No

**Describe your issue**

When installing Django Unfold, it generated this problem that the dark mode is too dark, hard to read

![image](https://github.com/user-attachments/assets/84130da9-4c27-420f-bdb1-131755b7eba2)
![image](https://github.com/user-attachments/assets/a9e998e9-33bc-453e-a78b-8e1e9fb784b4)

The configuration I have in setting.py is minimal and I do not modify any color. 
![image](https://github.com/user-attachments/assets/82ce48dc-84f1-47b8-835b-b1fbf2cb99e6)

**Comment by lukasvinclav** [comment]
How can I replicate the issue?

**Comment by josueygp** [comment]
The problem started when I re-downloaded all my dependencies with the latest versions, in this situation, Django==5.1.1, what I could find, when I had this version of django, it gave me this dark mode bug, I went back to django version 5.0.4 and I did not get this bug.

**Comment by yswtrue** [comment]
same here
```
django==5.0.7
django-crispy-forms==2.3  # https://github.com/django-crispy-forms/django-crispy-forms
crispy-bootstrap5==2024.2  # https://github.com/django-crispy-forms/crispy-bootstrap5
django-colorfield==0.11.0
django-unfold==0.39.0
django-admin-sortable2==2.2.2
django-admin-confirm==1.0.0
django-import-export==4.1.1

```

**Comment by lukasvinclav** [comment]
I'm asking again same question but how can I replicate this bug? Plase try the Formula project locally to check if you are having the issue there. If you are not able to replicate bug in Formula then create a brand new repository with the minimal example which I will use for debugging.

**Comment by yswtrue** [comment]
after purge cdn cache work again

**Comment by lukasvinclav** [comment]
I recommend clearing CSS cache after each update.
