### ISSUE TITLE
Missing "Add another" button when extra is zero, and no rows exist yet

### ISSUE THREAD

**Issue by yardensachs** [unfoldadmin/django-unfold#735]
**What version of Unfold are you using?**
0.38.0

**What version of Django are you using?**
5.1.1

**What browser are you using?**
Chrome Version 128.0.6613.120 (Official Build) (arm64)

**Did you checked changelog/commit history, if the bug is not already fixed?**
Yes, not fixed with latest.

**Did you searched other issues, if the bug is not already fixed?**
Yes, not fixed with latest.

**Describe your issue**
When "extra" is zero and no rows exist yet in the stack inline, the "Add another [...]" button is missing. This issue occurs in the stack inline class only, not in the tabular. This issue was originally identified in PR #684.

1. Extra is "1" - button shows:
![SCR-20240912-hrhv](https://github.com/user-attachments/assets/dd139174-b8cd-42a5-b9df-c31dab46cacf)

2. Extra is "0" - button is GONE:
![SCR-20240912-hrfp](https://github.com/user-attachments/assets/b7c0608b-073d-4536-91b6-69b822766c64)

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #758
