### ISSUE TITLE
When upload the image it's not showing the file name.

### ISSUE THREAD

**Issue by sabbir2609** [unfoldadmin/django-unfold#736]
Unfold : 0.38.0
Django : 5.0.7
Chrome

In the image upload field, if I select an image, it should show the file name but it's not showing. 
I got this in the console.

`Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at HTMLInputElement.<anonymous> (app.js:128:19)`

**Comment by sabbir2609** [comment]
Well, #731  worked for a single input on a page.
But not working for tabular ( multiple ) inputs.

![image](https://github.com/user-attachments/assets/c1052af4-0c0a-4b17-ac3f-ab10a620269c)

**Comment by lukasvinclav** [comment]
Fixed in #740
