### ISSUE TITLE
how can i add adminsortable2 StackedInline drag and drop feature into Unfold as tab?

### ISSUE THREAD

**Issue by asthen-infotree** [unfoldadmin/django-unfold#737]
**What version of Unfold are you using?**

0.37

**What version of Django are you using?**

4.2

**What browser are you using?**

Google Chrome

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

Currently, the formsets fields are hidden in unfold admin.
![image](https://github.com/user-attachments/assets/4825f127-fcd9-487d-83cc-a704e3d16e35)

It could be due do adminsortable2 inheriting from admin.StackedInline.
![image](https://github.com/user-attachments/assets/aa4521f8-959e-4f27-8a0a-6985b61df57d)

Is there currently a workaround for this?

Thanks

**Comment by lukasvinclav** [comment]
Unfortunately Unfold does not have an official support for this plugin.
