### ISSUE TITLE
User add form returns error 500 localy and in the demo

### ISSUE THREAD

**Issue by Jascha57** [unfoldadmin/django-unfold#745]
**What version of Unfold are you using?**

0.38

**What version of Django are you using?**

5.1.1

**What browser are you using?**

Firefox 128.0

**Did you checked changelog/commit history, if the bug is not already fixed?**

No

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

https://demo.unfoldadmin.com/admin/formula/user/add/

**Repository with reproduced bug**

I cannot as the repo is private but bug is present on demo website.

**Describe your issue**

When setting the add_form = UserCreationForm from unfold.forms, any attempt to add a new user ends with error 500. The issue seems to be the usable_password field. 

FieldError at /admin/auth/user/add/

Unknown field(s) (usable_password) specified for User. Check fields/fieldsets/exclude attributes of class UserAdmin.

User model is the base model for Django, it has not been changed. Removing or commenting out the add_form in admin.py resolves the issue and allows the admin to add another user but without the unfold styling on some elements. Removing the:

if "usable_password" in self.fields:
            self.fields["usable_password"].widget = UnfoldAdminRadioSelectWidget(
                choices=self.fields["usable_password"].choices,
            )
in UserCreationForm did not fix the issue.

**Comment by lukasvinclav** [comment]
Thanks. Fixed in #746
