### ISSUE TITLE
django-nested-inline support

### ISSUE THREAD

**Issue by SaeedRz96** [unfoldadmin/django-unfold#75]
It seems there is only TabularInline and StackedInline in `unfold.admin`. and NestedStackedInline and NestedTabularInline not supported.

**Comment by lukasvinclav** [comment]
These NestedStackedInline and NestedTabularInline are coming from third party app right?

**Comment by SaeedRz96** [comment]
> These NestedStackedInline and NestedTabularInline are coming from third party app right?

Yes. [https://pypi.org/project/django-nested-inline/](Pypi)

**Comment by SaeedRz96** [comment]
> These NestedStackedInline and NestedTabularInline are coming from third party app right?

Yes. [django-nested-inline PyPi](https://pypi.org/project/django-nested-inline/)

**Comment by lukasvinclav** [comment]
Thanks for link. Lets see if there are going to be more support requests.
