### ISSUE TITLE
Upgrading from django-unfold==0.35.0 to latest breaks the sidebar

### ISSUE THREAD

**Issue by ccjcan** [unfoldadmin/django-unfold#755]
**What version of Unfold are you using?**
django-unfold==0.35.0

**What version of Django are you using?**
5.0

**What browser are you using?**
Chrome Version 128.0.6613.138 (Official Build) 

**Did you checked changelog/commit history, if the bug is not already fixed?**
No

**Did you searched other issues, if the bug is not already fixed?**
Yes

**Did you checked documentation?**
Yes, couldn't find any references.

**Are you able to replicate the bug in the demo site?**
Haven't tried

**Repository with reproduced bug**

Create minimal repository where it is possible to reproduce an error.

**Describe your issue**
The sidebar menu doesn't show when I upgrade to the latest version.

**Comment by justinqian42** [comment]
Clear your browser cache and try again.
This is related to #732 .

**Comment by lukasvinclav** [comment]
I would say that just CSS is not properly refreshed. Anyway, I will close the issue for now as it is missing important questions which are not answered. In this case:

**"Are you able to replicate the bug in the demo site?"**
Answering this question, will help me to find out if this is browser related issue.

**"Repository with reproduced bug"**
This will help me to to find out, if the issue has something with the Unfold configuration.

Thanks for understanding.
