### ISSUE TITLE
Fields related to the password in the user creation form are not using Tailwind CSS

### ISSUE THREAD

**Issue by yanesgreen** [unfoldadmin/django-unfold#756]
**What version of Unfold are you using?**

0.39

**What version of Django are you using?**

5.1.1

**What browser are you using?**

Google Chrome

**Describe your issue**

I followed the steps in the Unfold Admin documentation, including unregistering and registering the User admin. However, I noticed that the input fields related to the password in the user creation form are not using Tailwind CSS, while the update user and change password sections are working fine. Is this a bug, or did I miss something?
![unfoldadmin](https://github.com/user-attachments/assets/af142fc8-08b4-494d-97d6-f611e5fc0b3e)

**Comment by justinqian42** [comment]
No you didn’t. I noticed the same thing.

**Comment by lukasvinclav** [comment]
There is a demo site where you can check how the most recent version works and it seems that these functionality works as expected. I guess you didn't properly configured right form for the user. This is described in the documentation. 

Demo: https://demo.unfoldadmin.com/admin/formula/user/add/
Documentation: https://unfoldadmin.com/docs/installation/

**Comment by PierreMory** [comment]
I encountered the same problem. I think the documentation should be improved. Indeed, if we follow what is described in https://unfoldadmin.com/docs/installation/auth/, the default form is not compatible with Django Unfold and the problem described by @yanesgreen occurs.
To fix this issue, you need to explicitly specify the following attributes in the UserAdmin class, as it is done in the demo site: https://github.com/unfoldadmin/django-unfold/blob/main/tests/server/example/admin.py

This should probably be mentioned in the documentation.

```from django.contrib import admin
from django.contrib.auth.admin import GroupAdmin as BaseGroupAdmin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import Group

from unfold.admin import ModelAdmin
from unfold.forms import AdminPasswordChangeForm, UserChangeForm, UserCreationForm

from .models import User

admin.site.unregister(Group)


@admin.register(User)
class UserAdmin(BaseUserAdmin, ModelAdmin):
    form = UserChangeForm
    add_form = UserCreationForm
    change_password_form = AdminPasswordChangeForm


@admin.register(Group)
class GroupAdmin(BaseGroupAdmin, ModelAdmin):
    pass```
