### ISSUE TITLE
Add Autocomplete Search Fields and AJAX Filters to Django Jet for Enhanced Admin Usability

### ISSUE THREAD

**Issue by demoh2019** [unfoldadmin/django-unfold#757]
autocomplete_search_fields(): This is a static method used in Django Jet to allow admins to define which fields should be searchable through AJAX-based autocomplete fields. You can add this method to your ModelAdmin class, returning a tuple or list of fields that you want to be searchable.
@staticmethod
def autocomplete_search_fields():
    return ['name', 'email']
    
This will allow admin users to search by name or email when interacting with the related model fields in the admin interface.

CompactInline: This is a feature of Django Jet that provides a more compact way of rendering inline forms (similar to TabularInline in Django). It helps when there are many related objects, optimizing space and display. You would use this in the ModelAdmin class to manage related models with a compact layout.

from jet.admin import CompactInline

class MyInline(CompactInline):
    model = MyRelatedModel
    
RelatedFieldAjaxListFilter: This is a filter that adds AJAX-based search capabilities to the admin list filter. It's particularly useful when you have a large number of related objects, and you want to make it easier for users to filter through those related objects using a search.

from jet.filters import RelatedFieldAjaxListFilter

class MyModelAdmin(admin.ModelAdmin):
    list_filter = (
        ('related_field', RelatedFieldAjaxListFilter),
    )
    
This filter enhances the admin interface by adding a dynamic, AJAX-powered search for related fields, making it easier to find specific objects in large datasets.

Issue Description Example:
Do you have any examples?

Yes, the request is to enhance ModelAdmin classes by allowing fields to be searched using an AJAX-powered autocomplete search interface. This can be achieved by adding the autocomplete_search_fields method to allow specific fields to be searched.

Is it a third-party application feature request?

Yes, this is a feature request for the Django Jet admin interface.

In case of third-party application, when was it updated last time?

The last update for django-jet was on 2017

Describe your feature request

We request the following features be added to django-unfold:

autocomplete_search_fields(): Allow specifying which fields are searchable using AJAX in related model fields.
RelatedFieldAjaxListFilter: Add more robust support for filtering related fields using an AJAX-powered list filter, improving performance with large datasets.
CompactInline: Continue to support or enhance inline forms with compact views, especially when many related objects are displayed.
Implementing these features would improve the admin user experience, particularly when dealing with large datasets and many related fields.

**Comment by lukasvinclav** [comment]
I'm closing this issue because:

1. it probably contains 2 different feature requests
2. it is completely without any formatting

If you want, you can recreate tickets but please provide proper formatting, screenshots and in this case it would be nice if you create some initial pull requests to see what you are looking for.
