### ISSUE TITLE
About the setting of "Django Allauth" and "Django unfold"...

### ISSUE THREAD

**Issue by Huanghibo** [unfoldadmin/django-unfold#759]
Sorry, my regional visit to gitub is very unstable.Unable to view responses in a timely manner

https://docs.allauth.org/en/latest/common/admin.html

I've tried the following, a simple example, and I don't know if this method meets your requirements:
![3](https://github.com/user-attachments/assets/586bfa9d-4754-4821-9b81-3db7aed11aa1)
![4](https://github.com/user-attachments/assets/63a7b06b-504a-4910-95bf-08f1ee1f7685)

**Comment by Huanghibo** [comment]
1. Override the Django Admin login view:

from unfold.sites import UnfoldAdminSite
from django.conf import settings
from django.contrib import admin 
# from django.contrib.admin.sites import AdminSite
from allauth.account.views import login

admin.autodiscover()

class CustomUnfoldAdminSite(UnfoldAdminSite):
    def login(self, request, extra_context=None):
        # Use Allauth‘s login
        return login(request)

admin_site = CustomUnfoldAdminSite()

2 . Add to urls.py
.# usrls.py
from django.urls import path, include
from . import admin_site

urlpatterns = [
    path('admin/', admin_site.urls),
    path('accounts/', include('allauth.urls')),
    # ... other

3.Customize your Admin landing page (optional):

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # 5 minutes

# Customize your Admin landing templates page
ACCOUNT_ADAPTER = 'path.to.your.adapter.Adapter'

It's like this
![Uploading 5.png…]()

**Comment by Huanghibo** [comment]
But I'm sorry,  I can't configure Unfold in "Settings-Unfold". The "UNFOLD->Sidabar" item, which could not be set as required by my permission control, made me temporarily abandon it.

For the permission management of "AdminSite", only "Django Jazzmin" meets my needs at the moment. 
But "Django-Unfuld" uses "Tailwind css"， that's great,  and that's why I wanted to use it.

Thank you!

**Comment by justinqian42** [comment]
> 1. Override the Django Admin login view:
> 
> from unfold.sites import UnfoldAdminSite from django.conf import settings from django.contrib import admin from allauth.account.views import login
> 
> admin.autodiscover()
> 
> class CustomUnfoldAdminSite(UnfoldAdminSite): def login(self, request, extra_context=None): # Use Allauth‘s login return login(request)
> 
> admin_site = CustomUnfoldAdminSite()
> 
> 2 . Add to urls.py .# usrls.py from django.urls import path, include from . import admin_site
> 
> urlpatterns = [ path('admin/', admin_site.urls), path('accounts/', include('allauth.urls')), # ... other
> 
> 3.Customize your Admin landing page (optional):
> 
> ACCOUNT_AUTHENTICATION_METHOD = 'username_email' ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True ACCOUNT_LOGOUT_ON_GET = True ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5 ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300 # 5 minutes
> 
> # Customize your Admin landing templates page
> ACCOUNT_ADAPTER = 'path.to.your.adapter.Adapter'
> 
> It's like this ![5](https://private-user-images.githubusercontent.com/4192411/369666340-e2e63df5-2722-427c-a057-5b17fa6211d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDkwNzAsIm5iZiI6MTcyNzA0ODc3MCwicGF0aCI6Ii80MTkyNDExLzM2OTY2NjM0MC1lMmU2M2RmNS0yNzIyLTQyN2MtYTA1Ny01YjE3ZmE2MjExZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMjM0NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI2NDBiN2M2NmJhZmNkZWNkMTlmMWJiZGI2NzdmNWM2MTZjYmI3YzA5YTU0NTdmNDE4ZDQwMzkzODE2OGI5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TLY2N5J2hFo2H1j2gSRYqxZI5bVMHT-Ri8voScTO0EQ)

Thank you so much mate!!!
Great stuff.

So you didn't use the decorator from allauth but overrode the login method of UnfoldAdminSite class.

**Comment by justinqian42** [comment]
> But I'm sorry, I can't configure Unfold in "Settings-Unfold". The "UNFOLD->sidebar" item, which could not be set as required by my permission control, made me temporarily abandon it.
> 
> For the permission management of "AdminSite", only "Django Jazzmin" meets my needs at the moment. But "Django-Unfold" uses "Tailwind css"， that's great, and that's why I wanted to use it.
> 
> Thank you!

Alright, back to your reported case.
Taking the code snippet from the unfold doc -

`                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        "badge": "sample_app.badge_callback",
                        "permission": lambda request: request.user.is_superuser,
                    },
`

As you can see the permission is followed by a lambda function which revokes the actual django's request object. Luke gave an example that judges the user's identity.

So... actually we can definitely do something like

`"permission": lambda request: request.path.endswith("add/"),`

In your case, I'd try to do this
`"permission": lambda request: request.path.find("/custom/"),`

**Comment by lukasvinclav** [comment]
What exactly is the problem? Are you pointing at the missing styles on custom login page provided by django-allauth? 

When you are using `secure_admin_login` decorator, it redirects you to the login page coming from django-allauth and it ignores the default login page in Django admin. Then it is up to you to provide visual styles. Unfold does not provide any styling for django-allauth templates.
