### ISSUE TITLE
default django autocomplete problem

### ISSUE THREAD

**Issue by guntribam** [unfoldadmin/django-unfold#76]
this is how the default select2 for autocomplete fields is rendered

![image](https://github.com/unfoldadmin/django-unfold/assets/7470516/30bd1de7-a303-4b63-92dd-a56e0b5c8955)

**Comment by lukasvinclav** [comment]
It looks like that there is no enough space for this field in table row. You have there 5 columns with a lot of content and on top of that foreign key field is by default wide. Remove one of the columns or make "Conta" readonly and it should be good.
