### ISSUE TITLE
Wrong forms signature

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#760]
**What version of Unfold are you using?**

main

**What version of Django are you using?**

Any

**What browser are you using?**

Not relevant

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

Yes

**Repository with reproduced bug**

Not relevant

**Describe your issue**

The forms' signatures are not valid. Only one form is supposed to take `request`: 

https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/forms.py#L56-L68

Other forms:

https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/forms.py#L69-L124

**Do not take** request as first arg. They take "data".

**Why is it wrong:**
- Django uses the positional arguments when calling these forms, so the `request` is simply `data` - wrong, but it works
- But if you like to test everything and want to have readable tests, then anything like `UserForm(data={})` will cause a total breakdown, as the "data" will be supplied twice: First as `request` (`None`) & kwarg `data`. 

**How to fix**

Change typing/signature of the forms, see:  #752

**Comment by lukasvinclav** [comment]
Actually this is everything what you need, right?

#764

**Comment by PavelPancocha** [comment]
@lukasvinclav yes, but I think having some coverage is always nice

**Comment by lukasvinclav** [comment]
Please test my PR, it if works for you. If everything is okay, I will merge it to main.

**Comment by PavelPancocha** [comment]
All fine, next time re-using my PR would feel more appropriate. But fine.

**Comment by lukasvinclav** [comment]
Why it should be more appropriate? What is the difference for you whos PR was accepted if it improves the package?

For comparison here are pull requests:

- Yours: https://github.com/unfoldadmin/django-unfold/pull/752/files
- My: https://github.com/unfoldadmin/django-unfold/pull/764/files

**Comment by PavelPancocha** [comment]
I do not want to start any blame war. I think, my PR had more value. If you feel, the tests/other stuff is unnecessary/should be done in separate PR, I am fine with that. That was not addressed, I didn't get, where the need for different PR come from. Thats all. 

Thanks :)

**Comment by lukasvinclav** [comment]
The reasons for new PR come from:

- AbstractUser -> User
- format_html was supposed to be new PR
- unnecessary `_apply_widget_classes_to_fields` internal helper function buried somewhere in forms.py
- tests are written in completely different style (not wrong, but different)

At the end of the day, I decided to pick cherries from your PR, move them into one simple PR and ship it **today** so you can have updated main branch asap :-)

**Comment by PavelPancocha** [comment]
Ok, fine then. Just about typing - as you now wrote it, I got that `User` is much more specific, will not work for most of my projects as I use "Custom user" model: https://github.com/unfoldadmin/django-unfold/pull/764/files#r1771693202

**Comment by PavelPancocha** [comment]
About "personal preferences" - the best would be to have some sort of examples: How to write tests. I will do my best to match the style. I don't see any "specific" style in Unfold so far.
