### ISSUE TITLE
Update material symbols

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#761]
**Describe your feature request**

There are already new symbols/icons added to Material Symbols, eg. id_card which were not included in Unfold static file.

Also it is hard to check, which version is "Unfold" using.

**Proposed changes**

As we probably do not need the whole set (see MaterialIcons GitHub) I propose to get new fonts from the CSS directly:

1. https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined -> Here we can find:
2. https://fonts.gstatic.com/s/materialsymbolsoutlined/v207/kJF1BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzByHX9rA6RzaxHMPdY43zj-jCxv3fzvRNU22ZXGJpEpjC_1v-p_4MrImHCIJIZrDCvHOej.woff2  
3. Download that file and rename it to `Material-Symbols-Outlined.v207.woff2` or what you like

These steps match proposal here: https://github.com/unfoldadmin/django-unfold/pull/750

**Comment by PavelPancocha** [comment]
@lukasvinclav can you please give some ETA here? Thank you!

**Comment by lukasvinclav** [comment]
Unfortunately, I don't have any estimate when this task can be done.

**Comment by lukasvinclav** [comment]
Fixed in #794
