### ISSUE TITLE
How to override unfold's login page with django-allauth's.

### ISSUE THREAD

**Issue by justinqian42** [unfoldadmin/django-unfold#763]
@justinqian42 please create a separate ticket related to django-allauth and I will take a look.

_Originally posted by @lukasvinclav in https://github.com/unfoldadmin/django-unfold/issues/754#issuecomment-2363364867_
            

This isn't an issue, but trying to give those who have the same requirement a hint.

What:
Integration between django-unfold and django-allauth. Overriding the unfold's login page with allauth's, so that users will be redirected to it.

How:
Allauth actually provides a handy decorator. Ref: https://docs.allauth.org/en/latest/common/admin.html

The only thing you need to do is --
add
```
admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)
```
before

```
urlpatterns = [ ... ]
```

The reason why I'm not decorating an UnfoldAdminSite instance is that the allauth decorator is designed for the original one. The allauth decorator and templates don't honour the unfold's "image" or "redirect_after" parameters anyway, so it makes no difference.

Through this way, we could benefit from allauth's features, like rate-limiting and third party login methods.

However, the default allauth login page lacks the unfold's styling.

**Comment by lukasvinclav** [comment]
Okay, so I checked the docs and read your comment multiple times. Where exactly is the problem and what is your error message?

**Comment by justinqian42** [comment]
No this isn’t an issue.
Just wanted to share another way of applying django-allauth apart from the method in #759 .

It can be closed.
