### ISSUE TITLE
In admin panel display aggregate values below change list table of models.

### ISSUE THREAD

**Issue by yogesh-sirsat** [unfoldadmin/django-unfold#767]
**Do you have any examples?**

![image](https://github.com/user-attachments/assets/ae7bcf5c-b5af-499c-9ddb-b2aeed50786a)

**Is it a third party application feature request?**

No

**Describe your feature request**

I can't seem to find a way to display aggregate values like in Order model there'll be amount field, and I want to display total amount sum of all the orders just below the change list table of Order model, and it should update total amount sum if data filtered.

I tried to edit ModelAdmin.changelist_view but its not working I don't know what's wrong, I've followed the folder structure as mentioned in docs, also shuffled `INSTALLED_APPS`  up down no luck.

I'm not considering pagination should reflect on total sum amount, I just want to include case when I'll be filtering data based on date or search fields.

**Comment by lukasvinclav** [comment]
What I was considering to do is to add an option to load custom templates above and below this table where you can add your own html code. Adding an option to render <tfoot> with custom business logc (calculate the total value of column) is not in the plan.

**Comment by lukasvinclav** [comment]
Implented in #776
