### ISSUE TITLE
feat: adjustable badge background color in sidebar

### ISSUE THREAD

**Issue by pnost** [unfoldadmin/django-unfold#769]
**Do you have any examples?**

<img width="272" alt="image" src="https://github.com/user-attachments/assets/fb5fa4e6-963d-4364-823d-37bb2e368493">

**Is it a third party application feature request?**

No

**Describe your feature request**
It would be great to adjust the badge color for nav items in settings.py. Either using some hex color code or theme colors like primary-xxx  etc.
`"badge": ("bade_callback", #hexcolor),`

 I know that the badge color is set in app_list.html as:
`{% if item.badge %}
    <span class="bg-red-600 font-semibold ml-2 px-1 rounded-sm text-xs text-white">`. But I am unsure about the best way to implement it, regarding theme colors like bg-red-600, primary-color-xxx, how to keep backward compatibility and default values.

**Comment by lukasvinclav** [comment]
Here I recommend doing that through the custom styles. In documentation you can find a chapter how to load custom stylesheet where you can override the color.

**Comment by pnost** [comment]
Thank you for your lightning fast response. I am aware of the chapter and use custom colors already. However, I want to use different badge colors simultaneously and not change the color of all badges. Sorry for beeing unclear.

**Comment by lukasvinclav** [comment]
What is the use case for different badge colors? These badges were meant to show how many important things are required to address under each link so the red color was more or less a standard way how to communicate this to user.

**Comment by pnost** [comment]
Thanks for asking. Exactly, I use colors to address importance similar to the different colors of messages: error, warning, info etc.
In our usecase we use the badges to have a quick glance on how many items are in certain process status, especially on a mobille device the badges work perfectly. But I start to have to many of them ;)
Using colors my users are guided even better if there are items they need to take care of immediately or if something is less severe. If you don't "share" the usecase, that is totally fine. Then I'll hack something on my own, but it will definetly won't have the quality and beauty of your code.

**Comment by lukasvinclav** [comment]
To be honest this is really specific requirement and at the moment I'm not having spare time to develop such a feature. But if there will be more people looking for this or maybe somebody willing to support the development, I can reconsider my opinion.

At the moment, the only way for you to get this working in your project is to rewrite navigation template and adjust the badge based on your requirement. If you want, you can submit a PR which I can try to review but I don't promise, I will merge it.

**Comment by lukasvinclav** [comment]
Okay, I think I have workaround. In the most recent version from main you can do this:

```python
def badge_callback(request):
    return mark_safe(
        f"<span class='absolute bottom-0 left-0 right-0 top-0 bg-green-100'></span><span class='relative text-green-700 z-10'>+{random.randint(1, 99)}</span>"
    )
```

Of course, not all tailwind colors are compiled into css classes so you can apply them manually by using `styles` attribute.
