### ISSUE TITLE
Field widget for `ArrayFieldChoices`

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#773]
I want a nice way to input data for "ArrayField", mainly when "choices" are available. Of course, it could be great to have a widget also "without choices" (eg. tags)

**Do you have any examples?**

![obrazek](https://github.com/user-attachments/assets/83947827-35c3-4312-a5b3-be3ae97dbdb5)

**Is it a third party application feature request?**

Could be - Select2 used in example

**Describe your feature request**

Main question is if there is/is planned/is definitely not planned something like this for Unfold

**Comment by lukasvinclav** [comment]
Widget `django.contrib.postgres.fields.ArrayField` is already implemented in Unfold.

- Usage example: https://unfoldadmin.com/docs/configuration/modeladmin/

**Comment by PavelPancocha** [comment]
@lukasvinclav How did I miss that? Thank you!
