### ISSUE TITLE
GeoModelAdmin map widgets not showing

### ISSUE THREAD

**Issue by filippotp** [unfoldadmin/django-unfold#779]
**What version of Unfold are you using?**

0.39.0

**What version of Django are you using?**

5.1.1

**What browser are you using?**

Firefox 130.0.1, Chrome 129.0

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

No, it does not use geographic data.

**Describe your issue**

My Django project uses the `django.contrib.gis` module, since it handles Models with geographic features. Unfortunately, ModelAdmins corresponding to these Models do not display the OSM widget (`django.contrib.gis.forms.widgets:OSMWidget`):
![immagine](https://github.com/user-attachments/assets/8cd0ae06-8830-4eee-a085-fd25567458e5)

The map should appear between the "Location" label and the "Delete all features" link. The reason for this is its HTML container having 0 width and height, as stated by the console log message:

![immagine](https://github.com/user-attachments/assets/65764cc1-ead4-4f41-96ea-fb1fa9f6febb)

By manually adjusting CSS, the map is shown:
![immagine](https://github.com/user-attachments/assets/ca0bbcab-8bfc-41eb-9d88-654dae1f6743)

**Comment by lukasvinclav** [comment]
Thanks for report. As I don't have a lot of experience with this widget, would you mind to draft a PR?

**Comment by d-handy** [comment]
A simple and effective solution is to inherit the LeafletGeoAdmin class from django-leaflet alongside the custom unfold model admin class:

```
from leaflet.admin import LeafletGeoAdmin
from unfold.admin import ModelAdmin

class GeoDataAdmin(ModelAdmin, LeafletGeoAdmin):
    pass
```

https://django-leaflet.readthedocs.io/en/latest/

**Comment by TBxy** [comment]
This css works as well:

```css
.dj_map_wrapper {
    display: flex;
    flex-direction: column;
    width: 100%;
}
.dj_map {
    height: 300px;
}
```

It is possible to add it to the unfold settings:

```python
from django.templatetags.static import stati
UNFOLD["STYLES"] = [lambda request: static("/css/dj_map.css")]
```
@lukasvinclav could this just be added to the `unfold/styles.css` file (as a good default) or is there a better location/way?
