### ISSUE TITLE
Breadcrumbs wrapping on small screen/long names wraps only last item

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#788]
**What version of Unfold are you using?**

Main

**What version of Django are you using?**

5.0

**What browser are you using?**

Chromium: 129.0.6668.89

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

https://demo.unfoldadmin.com/admin/formula/circuit/56/change/

**Describe your issue**

For small screen/very long breadcrumb names the breadcrumb is not "wrapped" properly:
![image](https://github.com/user-attachments/assets/316b4ea4-aed4-4fb8-8e5e-ea93270ad2da)

Current: Last word is wrapped
Expected: Whole line is wrapped

**Comment by lukasvinclav** [comment]
Thanks. Fixed #830
