### ISSUE TITLE
Fix django-guardian permission display

### ISSUE THREAD

**Issue by gmargaritis** [unfoldadmin/django-unfold#791]
The `django-guardian` permissions are rendered in reverse.

![Screenshot 2024-10-07 at 4 01 38 PM](https://github.com/user-attachments/assets/78a8d9a4-b918-48f7-acd3-67a3774879e4)
![Screenshot 2024-10-07 at 4 02 08 PM](https://github.com/user-attachments/assets/f4d9910a-6e8f-415b-89e9-9596759b80ea)
![Screenshot 2024-10-07 at 4 02 00 PM](https://github.com/user-attachments/assets/7c38d646-78bb-49ef-801d-07a756419666)

Without unfold
![Screenshot 2024-10-07 at 4 05 35 PM](https://github.com/user-attachments/assets/2e6a4d90-cd4e-480e-8125-cf098e782912)

**Comment by lukasvinclav** [comment]
Hey, thanks for report and the PR, it helped me a lot to debug the issue. In PR #793 I addressed your problem and additionaly I found one more issue with the template which is fixed there.

For the sake of shipping this fix as soon as possible, I merged my PR.

**Comment by lukasvinclav** [comment]
@gmargaritis I already made a release. You can update the version.

**Comment by gmargaritis** [comment]
Thanks a lot for the quick response and release ✌️

**Comment by lukasvinclav** [comment]
Yeah, no problem. If you find something else let me know.
