### ISSUE TITLE
Double select block on Inline with autocomplete fields

### ISSUE THREAD

**Issue by soltanoff** [unfoldadmin/django-unfold#796]
**What version of Unfold are you using?**

`0.39.0`

**What version of Django are you using?**

`5.1.1`

**What browser are you using?**

Google Chrome `Version 129.0.6668.90 (Official Build) (arm64)`

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes, this bug appeared since `0.33.0`

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

There is no page to reproduce.

**Repository with reproduced bug**

Create minimal repository where it is possible to reproduce an error.

**Describe your issue**

When using `StackedInline` and `TabularInline` with autocomplete mode, the select block is duplicated. However, if you remove the line and create it again, there will be no duplication.

Code: 

```python

# ...

class MatchTranslationInline(unfold_admin.StackedInline):
    model = models.MatchTranslation
    extra = 0
    fields = ("language", "name")
    autocomplete_fields = ("language",)
    can_delete = True

class MatchTeamInline(unfold_admin.TabularInline):
    model = models.MatchTeam
    extra = 0
    autocomplete_fields = ("team",)
    ordering = ("-home_team",)
    can_delete = True

# ...

@admin.register(models.Match)
class MatchAdmin(unfold_admin.ModelAdmin, BackgroundTaskPermissionMixin):
    # ...
    inlines = [MatchTeamInline, MatchTranslationInline]

```

![image](https://github.com/user-attachments/assets/15f0c52e-a1b9-4f1e-910c-69b54c053168)

![image](https://github.com/user-attachments/assets/c042adfd-54d4-48c1-9473-6fa8c84d41f4)

![image](https://github.com/user-attachments/assets/dc390b78-2bc9-47fb-95b6-cb5c778e4f4b)

**Comment by soltanoff** [comment]
After remove and add: 

![image](https://github.com/user-attachments/assets/4eb1a1b9-5d5e-42b1-8a75-88f8cf3386e6)

**Comment by Disaxy** [comment]
same problem

**Comment by soltanoff** [comment]
I did some research. It was broken by [these changes](https://github.com/unfoldadmin/django-unfold/pull/619/files#diff-36107a91f6d8e6dd581b76650baddb89ae6adcc33b404a4cc34a4b3d0662d3a9). I have lack of experience in CSS but I guess the problem is in the CSS file.

**Comment by soltanoff** [comment]
I tried to replace `src/unfold/templates/admin/edit_inline/stacked.html` and `src/unfold/templates/admin/edit_inline/tabular.html` from version `0.32.0` to `0.40.0` but nothing has changed

On version`0.32.0`: everything is okay 
![image](https://github.com/user-attachments/assets/5903aa81-8e86-4d7c-a738-2d3e3bb0535f)

**Comment by lukasvinclav** [comment]
Thanks for report. PR #800 is fixing this issue.
