### ISSUE TITLE
Some CSS styles don't work properly.

### ISSUE THREAD

**Issue by gilbertoolimpio** [unfoldadmin/django-unfold#798]
**What version of Unfold are you using?**

0.40.0

**What version of Django are you using?**

5.1

**What browser are you using?**

Arc V1.63.0

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

No

**Repository with reproduced bug**
N/A

**Describe your issue**

After updating my version to Django 5.1, some inconsistencies appeared in the page’s style. For example, the sidebar has no scroll (screenshot attached), the table header also lost its formatting, as well as the checkbox. The dark mode style also doesn’t seem to be responding to the stylesheet.

## No Scroll
![No Scroll](https://github.com/user-attachments/assets/a5661dba-6afd-4fc6-be1c-33a9f0ec63b8)

## Table Header
![Table Header](https://github.com/user-attachments/assets/46856354-5733-4a52-86b4-2cf3df7c5147)

## Checkbox Active
![Checkbox active](https://github.com/user-attachments/assets/f06663eb-f3e9-4917-a319-14005c2fea71)

## Checkbox Deactivated
![Checkbox deactivated](https://github.com/user-attachments/assets/e77fe9e0-56d1-4021-9625-19bbe25e889a)

## Dark Mode
![Darkmode](https://github.com/user-attachments/assets/ea5bcc87-4128-4220-9792-1e9297a411ab)

**Comment by gilbertoolimpio** [comment]
I proceeded with downgrade to version 0.22.0 and now, works fine.

**Comment by lukasvinclav** [comment]
Did you checked if the styles are properly refreshed? If this is a production, did you ran again collectstatic?
