### ISSUE TITLE
Pretty JSON Format for Custom Read-Only Field

### ISSUE THREAD

**Issue by khaled5321** [unfoldadmin/django-unfold#799]
**Do you have any examples?**

For example: 
![Screenshot 2024-10-12 133810](https://github.com/user-attachments/assets/864c1d98-31a8-463c-a9d4-a74cd084a1a0)

**Is it a third party application feature request?**

For example: No

**In case of third party application, when it was updated last time?**

For example: N\A

**Describe your feature request**

Read-only fields for JSON database fields are formatted by default like the screenshot above. Is there an option to do the same for custom read-only fields?

For example, the following code does not produce the same formatted output as shown above:
```python
def custom_json_read_only_field(self, obj):
    import json
    return json.dumps(obj.some_field, indent=4, sort_keys=True)
```
![Screenshot 2024-10-12 134901](https://github.com/user-attachments/assets/6af85bb4-5410-498c-b84f-8db45560a639)

**Comment by lukasvinclav** [comment]
Here is the helper function:

https://github.com/unfoldadmin/django-unfold/blob/main/src/unfold/utils.py#L126-L148

**Comment by khaled5321** [comment]
@lukasvinclav Thank you!
