### ISSUE TITLE
Automatic color scheme detection not working

### ISSUE THREAD

**Issue by TheVaan** [unfoldadmin/django-unfold#81]
Hello,

I noticed that automatic color scheme selection based on system preferences is not working (at least in my environment).
Switching to dark manually works fine, switching back to "System" switches back to light mode. Other websites are detecting my preference correctly (e.g. tailwindcss.com).
Enabling "prefers-color-scheme: dark" in Chrome Developer Tool doesn't switch the scheme, enabling "Automatic dark mode" switches the theme. Maybe system preference detection has a bug?

OS: macOS 13.4
Browser: Chrome 114.0.5735.106 / Safari 16.5

**Comment by lukasvinclav** [comment]
Fixed.
