### ISSUE TITLE
Top-level language switch for django-modeltranslations

### ISSUE THREAD

**Issue by GaspardMerten** [unfoldadmin/django-unfold#812]
![image](https://github.com/user-attachments/assets/feb89f17-05e5-4eb6-85d1-90965e6464fc)

Hello!

Thanks for this amazing library. I customized your lib to have one tab to change the language for all fields instead of many. Would it be interesting to merge it into the lib?

For now, I did it by inserting custom javascript, but there are cleaner ways.

**Comment by lukasvinclav** [comment]
If you created a solution which is Alpine.js based without any additional JS, please submit a PR and I will take a look.
