### ISSUE TITLE
Add title to "theme" switch

### ISSUE THREAD

**Issue by PavelPancocha** [unfoldadmin/django-unfold#813]
**Do you have any examples?**

I would like to add "Theme" title to "theme switch
Example: 
![image](https://github.com/user-attachments/assets/268bd70d-91fd-4a76-93ce-c1fdebce6034)

If this is not implemented on purpose, It would be great to add option to set the title without need of overriding the whole template fragment.

**Is it a third party application feature request?**

 No

**Comment by lukasvinclav** [comment]
The best solution here is just to override the template.
