### ISSUE TITLE
Integret SSO for login

### ISSUE THREAD

**Issue by cloudyaaron** [unfoldadmin/django-unfold#819]
**Do you have any examples?**

For example:
Something like [django-authlib](https://github.com/matthiask/django-authlib), So user can login through SSO.

**Is it a third party application feature request?**

For example: Yes

**In case of third party application, when it was updated last time?**

For example: last month

**Describe your feature request**
Be able to use SSO in login template into Django admin site through Django-unfold(amazing Theme)

**Comment by lukasvinclav** [comment]
At the moment Unfold contains blocks on login page which can be extended by third party plugins. I'm going to close this feature request as not planned for now but if you want, feel free to submit PR wich some example implementation so I can see in detail what you want to achieve.
