### ISSUE TITLE
Import-Export Library: Unfold Feature Doesn't Reveal Error Details.

### ISSUE THREAD

**Issue by J0-Y0** [unfoldadmin/django-unfold#820]
What version of Unfold are you using?
0.40.0

What version of Django are you using?
5.0.6

What browser are you using?
Chrome Version 129.0.6668.103 (Official Build) (64-bit)
Microsoft Edge Version 130.0.2849.46 (Official build) (64-bit)

Did you check changelog/commit history, if the bug is not already fixed?
Yes

Did you search other issues, if the bug is not already fixed?
Yes

Did you check documentation?
Yes. Docs are here: https://unfoldadmin.com/docs/

Are you able to replicate the bug in the demo site?
It's a private project

Repository with reproduced bug
It's a private project, so I cannot share the code.

Describe your issue
I am encountering an issue with the import-export library. When importing data without unfolding, detailed error counts and descriptions are displayed correctly. However, when I use the unfold feature, it only shows the error count, and hovering does not reveal any error descriptions.

I am attaching screenshots of both scenarios for clarity:

Without Unfold:
![Without ](https://github.com/user-attachments/assets/75daf31f-5cf7-4b91-b13b-b8dec6c592d4)

With Unfold:
![Capture](https://github.com/user-attachments/assets/29e148fa-8bfb-4d76-8c9f-672dedb33ae1)

**Comment by lukasvinclav** [comment]
Fixed in #897 

<img width="759" alt="Screenshot 2024-12-07 at 13 52 29" src="https://github.com/user-attachments/assets/e0b0c6c5-cf14-4122-b4ea-60fedcb21b02">
