### ISSUE TITLE
New setting to show `DEBUG` badge

### ISSUE THREAD

**Issue by Zerotask** [unfoldadmin/django-unfold#821]
![image](https://github.com/user-attachments/assets/ea9c7a2c-3af0-4c89-80f6-ee0685c6756f)

**Is it a third party application feature request?**

No

**Describe your feature request**

New setting to display a `DEBUG` badge. Example:
```python
"SHOW_DEBUG": False, # show/hide "Debug" badge, default: False
```

Alternatively it could be a callback function or instead of a boolean, it could be: `None | "info" | "danger" | "warning" | "success"`
and by default it's None (or empty string), so the current behavior won't change:
```python
"SHOW_DEBUG": None, # show/hide "Debug" badge, default: None. Can be info, danger, warning, success
```

**Comment by lukasvinclav** [comment]
You can display this information inside the original badge for example like: STAGING/DEBUG. Another badge will take more space in already small area which will make it harder to optimise for mobile devices. Thanks for understanding.
