### ISSUE TITLE
New setting to make all menu apps collapsable

### ISSUE THREAD

**Issue by Zerotask** [unfoldadmin/django-unfold#822]
![image](https://github.com/user-attachments/assets/89264d7b-94cb-4700-b971-f0d2a8c437de)

**Is it a third party application feature request?**

No

**Describe your feature request**

We have many apps and models which makes our sidebar huge. Therefore we simply want to make all apps collapsable and collapsed by default, but we don't want to define every single app and model in the setting. 
Therefore we'd like to have a new setting added to unfold:
```python
"SIDEBAR": {
        "collapsible_menu": False,  # Make all applications collapsible. Default: False
}
```

Perhaps there could be a 2nd setting to define if it's collapsed or not be default

**Comment by lukasvinclav** [comment]
You can make a function which will update a list of dicts by new attribute to make all items closed. The reason behind not planning this is that I want to keep configuration options as small as possible due to maintenance overhead.
