### ISSUE TITLE
New setting to define extra navigation links

### ISSUE THREAD

**Issue by Zerotask** [unfoldadmin/django-unfold#823]
![image](https://github.com/user-attachments/assets/47c8e4c6-720d-4b3c-9c26-0f7718c757ef)

**Is it a third party application feature request?**

No

**Describe your feature request**

We'd like to show all applications and models  (`SIDEBAR.show_all_applications`) and define some extra navigation links before those (dashboard, show website, some external links, some custom sites etc).
If you define those links in `SIDEBAR.navigation`, then it shows only those links but not `show_all_applications`.
Therefore we suggest to add a new setting `SIDEBAR.extend_navigation`, to easily add new navigation links without the need to define every single app and model in the settings and just show them all.

**Comment by lukasvinclav** [comment]
Do you have any examples how you want to specify additional links? How you want to declare the position of these links in the whole navigation?

**Comment by Zerotask** [comment]
I'd like to define it kinda similar to `SIDEBAR.navigation`. It could be `extra_navigation`, `extend_navigation` or you split it like `navigation_top` and `navigation_bottom`.
The order would then be:
- (optional) navigation top
- regular navigation
- (optional) navigation bottom

In case you don't split it, then there must be a field `position`.

Example:
```python
UNFOLD = {
    "SIDEBAR": {
        "navigation_top": [
            {
                "title": _("Navigation"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Website"),
                        "icon": "home",
                        "link": reverse_lazy("index"),
                    },
                ],
            },
        ],
    },
}
```
