### ISSUE TITLE
Styling adjustments when more than 1 field is displayed in a line

### ISSUE THREAD

**Issue by Zerotask** [unfoldadmin/django-unfold#828]
**Do you have any examples?**

When using Django's [ModelAdmin.fields](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fields) or ModelAdmin.fieldsets, you can pass a tuple instead of a string, to display more than one field in a line.
Example:
![image](https://github.com/user-attachments/assets/472ca3e9-ff9b-44b8-9b6f-5c160eda3c96)
![image](https://github.com/user-attachments/assets/6572e88c-5845-4e4f-b194-aec14fa36e68)

```python
class FlatPageAdmin(admin.ModelAdmin):
    fields = [("url", "title"), "content"]
```

The gap between the first `<input>` and the second label are rather small compared to the gap between label and `<input>`.

This is not limited to 2 fields, it can also be more than that:
![image](https://github.com/user-attachments/assets/dfdf548e-07a9-4f36-b62c-ce767cd6c5da)

**Is it a third party application feature request?**

No

**Describe your feature request**

I suggest to make it more clear, that those are 2 different fields. This could be achieved with:
- increase gap between fields
- add a vertical line
- place label above the field (even if you use the compact mode)
- ...

**Comment by lukasvinclav** [comment]
Fixed in #899

<img width="1196" alt="Screenshot 2024-12-07 at 19 08 37" src="https://github.com/user-attachments/assets/fc707bf7-76fc-42f7-8a71-632e573146a4">
