### ISSUE TITLE
Admin form input has no styles

### ISSUE THREAD

**Issue by cruzlutor** [unfoldadmin/django-unfold#833]
https://github.com/user-attachments/assets/8bc669c4-be31-4bca-b62d-21e6ea3528d6

**What version of Unfold are you using?**
0.40.0

**What version of Django are you using?**
5.1.2

**What browser are you using?**
Chrome

**Did you checked changelog/commit history, if the bug is not already fixed?**
Yes, it is, but the solution didn't fix the bug in my end

**Did you searched other issues, if the bug is not already fixed?**
Yes

**Did you checked documentation?**
Yes

**Are you able to replicate the bug in the demo site?**
No

**Describe your issue**
Styles for admin input are not there, I have the following.

### src/projectname/admin.py
```
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.admin import GroupAdmin as BaseGroupAdmin
from django.contrib.auth.models import User, Group

from unfold.admin import ModelAdmin


admin.site.unregister(User)
admin.site.unregister(Group)


@admin.register(User)
class UserAdmin(BaseUserAdmin, ModelAdmin):
    pass


@admin.register(Group)
class GroupAdmin(BaseGroupAdmin, ModelAdmin):
    pass
```

### src/projectname/settings
```
INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "django.contrib.admin",  # required
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```

### src/requirements.txt
```
asgiref==3.8.1
Django==5.1.2
django-unfold==0.40.0
gunicorn==23.0.0
packaging==24.1
sqlparse==0.5.1
typing_extensions==4.12.2
```

Any help is appreciated

**Comment by cruzlutor** [comment]
I forgot to add `projectname` to `INSTALLED_APPS` in settings, it is working now

**Comment by fortunetony** [comment]
how was this solved, and what do you mean by forgetting to add projectname to installed_apps

**Comment by dhairyaajwani** [comment]
Hello @cruzlutor 
I am also facing the same issue. Can you please share the steps how did you solved this issue in detail.
