### ISSUE TITLE
Capturenode doesn't define child_nodelist

### ISSUE THREAD

**Issue by Mte90** [unfoldadmin/django-unfold#839]
So if you use django-fastdev with django-unfold the admin dashboard is not accessible.

I reported the issue on https://github.com/boxed/django-fastdev/issues/51 also with a patch but the package author says that the `Capturenode` doens't define child_nodelist.

Ref: https://github.com/unfoldadmin/django-unfold/blob/541a1577ec93630a9c99ec623d395a26c7098b65/src/unfold/templatetags/unfold.py#L79

**Comment by lukasvinclav** [comment]
Please submit a PR because I have no experience with mentioned third party app.
