### ISSUE TITLE
Download Button disappear when putting two fields in the same row 

### ISSUE THREAD

**Issue by omargawdat** [unfoldadmin/django-unfold#840]
unfold: 0.40 
django: 5.1 
chrome: latest 

Bug: Download Button in the file field has disappeared by putting two fields in the same row 
<img width="758" alt="image" src="https://github.com/user-attachments/assets/904c95c9-7bc0-4390-bd83-2ae3c648e0e5">

CODE:
`
                (_("Commercial Register"), {
                    "fields": (("commercial_register_expiry", "commercial_register"),)
                }),
`

**Comment by lukasvinclav** [comment]
Fixed in #898
