### ISSUE TITLE
RangeDateFilter won't show calendar widget if the Admin model doesn't have any actions.

### ISSUE THREAD

**Issue by FabrizioDiPrinzio** [unfoldadmin/django-unfold#85]
The `RangeDateFilter ` and `RangeDateTimeFilter ` filter classes will only display the calendar select if the admin they're being used on defines admin actions. If that class doesn't define any actions, only the text field will be rendered.

`RangeDateFilter ` on admin with actions:
![Captura de pantalla 2023-06-15 160009](https://github.com/unfoldadmin/django-unfold/assets/67496905/d97cf4dd-e717-4e4f-a52b-bf1336b0f532)

`RangeDateFilter ` on admin without actions:
![Captura de pantalla 2023-06-15 155738](https://github.com/unfoldadmin/django-unfold/assets/67496905/3a139884-f9c3-4ab4-8995-5199fae3c09d)

**Comment by lukasvinclav** [comment]
Hi, I just checked this report and I'm not able to replicate it. Are you sure you are using ModelAdmin coming from Unfold?

**Comment by FabrizioDiPrinzio** [comment]
> Hi, I just checked this report and I'm not able to replicate it. Are you sure you are using ModelAdmin coming from Unfold?


@lukasvinclav Yes, I am. I have globally disabled the delete action by doing `admin.site.disable_action('delete_selected')`, so most of my admins do not have any actions at all. If I add a custom action to the model or reenable the delete action, the full `DateRangeFilter` widget renders, but if I have an admin with 0 actions, only the text input renders.

**Comment by lukasvinclav** [comment]
Now I see it. I just pushed a fix. Thanks @Daspy11 @FabrizioDiPrinzio
