### ISSUE TITLE
integration for django-axes

### ISSUE THREAD

**Issue by Zerotask** [unfoldadmin/django-unfold#850]
**Do you have any examples?**

https://github.com/jazzband/django-axes

> Axes is a Django plugin for keeping track of suspicious login attempts for your Django based website and implementing simple brute-force attack blocking.

**Is it a third party application feature request?**

Yes

**In case of third party application, when it was updated last time?**

2 weeks ago

**Describe your feature request**

Ideally it could be as simple as the integration for [django-guardian](https://unfoldadmin.com/docs/integrations/django-guardian/), that you just have to add `unfold.contrib.axes` to `INSTALLED_APPS` or like the integration for django-celery-beat.

django-axes consists of 3 ModelAdmin classes: `AccessAttempt`, `AccessFailureLog` and `AccessLog`

**Comment by lukasvinclav** [comment]
For third party application integration you can contact us here https://unfoldadmin.com/
