### ISSUE TITLE
The help_text inline button does not work

### ISSUE THREAD

**Issue by danielmazurkin** [unfoldadmin/django-unfold#852]
Unfold: 0.40.0 or main
Django: 5.1.2
Browser: Google Chrome, version: 127.0.6533.72

[button_help_text.webm](https://github.com/user-attachments/assets/a4086802-d1ee-4fc5-a85a-652b8fc4939e)

**Comment by lukasvinclav** [comment]
I just tested this functionality and it works. To see the actual help text, you have to hover over the icon.
