### ISSUE TITLE
Action row not show all elements

### ISSUE THREAD

**Issue by muhammadfarizarya** [unfoldadmin/django-unfold#862]
**What version of Unfold are you using?**

0.41.0 or main

**What version of Django are you using?**

5.1.1

**What browser are you using?**

Chrome 130.0.6723.119 

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

No

**Repository with reproduced bug**

Create minimal repository where it is possible to reproduce an error.

**Describe your issue**

on action rows section all actions is shown but not all shown, its like sliced like this

<img width="712" alt="image" src="https://github.com/user-attachments/assets/a8a4d52d-f4ba-462a-adc9-6a25f522f591">

its not fully shown elements, thank you

**Comment by lukasvinclav** [comment]
How did you rotated that dropdown and added these icons? Both things are not supported by default. Did you override the template?

**Comment by muhammadfarizarya** [comment]
i copied from changelist html dropdown, and using <span class="material-symbols-outlined md-18 mr-3 w-4.5">how_to_reg</span> for icon to make dashboard that has dropdown for additional actions. From dashboard_callback wrap it using mark_safe. like this code

`for acara in hariini:
        result_hariini.append([
            f"{hari[acara.tanggal.weekday()]}, " + acara.tanggal.strftime("%d %B %Y"), 
            f"{acara.golongan.nama}", 
            acara.babak.nama, 
            f"{acara.waktu_mulai.strftime('%H.%M')} - {acara.waktu_akhir.strftime('%H.%M')}", 
            mark_safe("""<div class="group leading-none relative" x-data="{ openActionsId: false }"><span x-ref="rowDropdown1" class="cursor-pointer flex h-7 material-symbols-outlined md-18 -my-1 !leading-7 rounded text-center text-gray-400 w-7 group-hover:bg-gray-100 group-hover:text-gray-700 dark:text-font-default-dark group-hover:dark:bg-gray-800 group-hover:dark:text-white" @click="openActionsId = !openActionsId">more_horiz</span><nav x-anchor.offset.4="$refs.rowDropdown1" class="bg-white border flex flex-col leading-none py-1 rounded-md shadow-lg text-sm top-7 z-50 w-48 dark:bg-gray-800 dark:border-gray-700" x-show="openActionsId" @click.outside="openActionsId = false" style="left: 1062.5px; top: 333.5px; position: absolute; display: none;"><a onclick="if (confirm('Apakah Anda yakin melakukan Download Absensi ?')) { return true } else { return false }" href="/backoffice/daftartampil/""" + str(acara.id) + """/download-file-absen" class="mx-1 px-3 py-2 rounded-md truncate hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-200" target="_blank" title="Download Absensi"><span class="material-symbols-outlined md-18 mr-3 w-4.5">co_present</span></a></nav></div><br/><br/><br/><br/>"""),
        ])`

this the page

**Comment by lukasvinclav** [comment]
I believe this issue was fixed in the most recent update. But you have update your overridden template.
