### ISSUE TITLE
New option `list_filter_sheet` does not seem to work

### ISSUE THREAD

**Issue by subham1099** [unfoldadmin/django-unfold#866]
**What version of Unfold are you using?**

v0.41.0

**What version of Django are you using?**

5.1.2

**What browser are you using?**

Firefox latest

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes. The new option `list_filter_sheet` is not documented.

**Are you able to replicate the bug in the demo site?**

The demo site shows the new filter UI, but when I cloned the demo site repo, old filter UI is shown. Does the repo contain the latest deployed code of the demo site?

**Repository with reproduced bug**

Simply clone the demo site repo and follow the instructions. visit the "drivers" change list page and see the filter UI and compare with the demo site.

[Screenshot](https://github.com/user-attachments/assets/cd5be52b-2978-40b8-9375-756c2e98235f)

**Describe your issue**

Hi there, I am trying to make the new filter UI work, but I am unable to. The demo site shows the new filter UI, but on my local (formula repo clone) the default filter UI is shown (see the drivers admin changelist for example). The default setting of `list_filter_sheet=True` doesn't seem to work either. 

[Screenshot](https://github.com/user-attachments/assets/cd5be52b-2978-40b8-9375-756c2e98235f)

Am I missing something?

sample code:
```py
from unfold.admin import ModelAdmin
from unfold.contrib.filters.admin import RelatedDropdownFilter

class LocationAdmin(ModelAdmin):
    list_display = (
        "country",
        "name",
        "subdivision",
    )
    list_filter = (
        ("country", RelatedDropdownFilter),
    )
    ordering = ("-created_at",)
    list_fullwidth = True
    list_filter_submit = True
    list_filter_sheet = True
```

**Comment by lukasvinclav** [comment]
Yes, it was missing in the docs which I already updated. You are supposed to set `list_filter_sheet` to `False` to enable "sidebar" version.

**Comment by Autopilot9369** [comment]
@lukasvinclav  Thanks for the clarification. I should have tried setting it to `False`, lol.
