### ISSUE TITLE
Default on Weights should be incrementing

### ISSUE THREAD

**Issue by dickermoshe** [unfoldadmin/django-unfold#877]
**Do you have any examples?**

<img width="560" alt="image" src="https://github.com/user-attachments/assets/57945cfb-1128-4805-8a70-9b6f57d99508">

New items automatedly have the next weight assigned

**Is it a third party application feature request?**

No

**In case of third party application, when it was updated last time?**

N/A

**Describe your feature request**

It's quite common that you would want to enforce that every model a a unique weight. 
I've marked my weight column as unique, but new items are not assigned the next weight class, they just default to zero.
I would be awesome if something like the above autofiled the weights (under the hood too, if `hide_ordering_field = True`) and would add it to the end.

**Comment by dickermoshe** [comment]
In a personal project I've done the following in my save method, but it would be cool if this was supported out of the box:
```python
def save(self, *args, **kwargs) -> None:
        highest_weight = (
            TargetSku.objects.filter(target_sku=self.target_sku)
            .order_by("-weight")
            .first()
        )
        if highest_weight:
            self.weight = highest_weight.weight + 1
        else:
            self.weight = 0
        return super().save(*args, **kwargs)
```

**Comment by lukasvinclav** [comment]
The logic for how weights will be stored in the database must be handled by your application. You can listen on `IntegrityError` and then based on your use case, change the weight number.
