### ISSUE TITLE
Collapse menu button position is a problem now

### ISSUE THREAD

**Issue by yardensachs** [unfoldadmin/django-unfold#882]
Unfold 0.42.0
![SCR-20241126-pdis](https://github.com/user-attachments/assets/3b53ef00-7a30-4641-88e7-3d3635c443e6)

Collapsed:
![SCR-20241126-pcls](https://github.com/user-attachments/assets/cca9ab53-2a65-4e6a-8499-514dfff862ab)

Expanded:

![SCR-20241126-pckr](https://github.com/user-attachments/assets/3a4b2f40-a964-4007-bb28-cd210837dbbc)

**Comment by lukasvinclav** [comment]
Yes, you are right. This component is supposed to be redesigned so it will be fixed with the new design.

**Comment by yardensachs** [comment]
It would be great if the collapsed sidebar could remain visible with just the icons, but without the labels.
For example:


https://github.com/user-attachments/assets/a872627d-b24f-40ac-bd51-5fe631b24490

**Comment by lukasvinclav** [comment]
Fixed in #883. Regarding the sidebar navigation, this functionality is not currently in the pipeline. If you want, you can support its development here:

https://unfoldadmin.com/consulting/

**Comment by yardensachs** [comment]
Thanks!x
