### ISSUE TITLE
Change row action appearance (to buttons)

### ISSUE THREAD

**Issue by MaartenUreel** [unfoldadmin/django-unfold#884]
**Is it a third party application feature request?**
No

**Describe your feature request**

There is an existing feature for row actions which works very well:
https://unfoldadmin.com/docs/actions/changelist-row/

Currently this is implemented as a dropdown per row:
![image](https://github.com/user-attachments/assets/d631c2a7-3bfc-431d-a1b5-fc84bac9a317)

The downside is that new users do not notice these dropdowns and are not aware of the functionality there.

For views where I have limited columns and limited number of actions I would prefer to be able to show this as buttons:
![image](https://github.com/user-attachments/assets/a07a9745-5b16-47e9-9f55-ee9dde0c7720)

I know I can do this manually by defining a custom display property on the admin and putting the button HTML in there, but it would be nice to be able to do this with less lines and boilerplate.

**Comment by lukasvinclav** [comment]
The dropdown was implemented on purpose to save horizontal space because these rows tends to display a lot of columns. Now, I can only suggest you to override the template to display them as buttons.
