### ISSUE TITLE
Broken Apply Filters Button

### ISSUE THREAD

**Issue by arischaristes** [unfoldadmin/django-unfold#885]
**What version of Unfold are you using?**

0.41.0

**What version of Django are you using?**

5.1.1

**What browser are you using?**

Chrome, Firefox

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes

**Did you searched other issues, if the bug is not already fixed?**

Yes

**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

No, because there isn't a similar example in the demo site.

**Repository with reproduced bug**

Can do that, if required.

**Describe your issue**

After updating django-unfold to version 0.41.0 the apply filters button is broken.
![Screenshot from 2024-11-28 10-21-27](https://github.com/user-attachments/assets/e6fbff72-d6dd-435d-97e1-0ce1749bb483)
Before the update
![image](https://github.com/user-attachments/assets/23b82008-c28d-4733-9625-347e60ff3fb1)

**Comment by lukasvinclav** [comment]
Did you cleared cache? I checked the demo site and I was not able to replicate the issue. Why you ignored issue template?

**Comment by arischaristes** [comment]
Yes cache isn't the issue. In the demo site i did not find a similar case, with a lot of list filters and the list_filter_submit = True
My bad about the issue template, i edited the original post.

**Comment by lukasvinclav** [comment]
Thansk for report. Fixed in  #893
