### ISSUE TITLE
It's time for v1!!

### ISSUE THREAD

**Issue by thclark** [unfoldadmin/django-unfold#889]
Hi Lukas,

I'm still a big fan of unfold but something that's getting quite frustrating is the versioning system. We've had 20 releases in the last 6 months, all of which are potentially breaking changes :(.

I think most of them aren't, but the commit logs and release notes don't highlight breaking changes, so it's either a case of combing through the code with a fine toothcomb, or crossing fingers.

Please could we move to v1, so you can add new features to your hearts content, but allow us to see if updating would break our backward compatibility?

Thanks!

**Comment by soltanoff** [comment]
Hm, I agree with @thclark. It's really useful idea/enhancement.

**Comment by lukasvinclav** [comment]
Hey @thclark,

thanks for this question. Actually, I was already thinking about it several times in the past. There are few reasons why I decided NOT to release 1.0:

- I want to focus on active development adding more and more features based on user feedback.  In general, I'm trying to add new stuff without breaking existing implementation. By not breaking, I mean changes will not raise 500.

- Before commiting to version 1.0, I want to make sure theme contains broader set of features which I'm personaly considering as mandatory. 

- 1.0 release would imply that breaking changes will be minimized in the future but first I have to ensure theme is robust enough to ensure this.

- I don't feel there is urgent need for 1.0. If you are implementing Unfold in your projects and your are not sure about breaking the project after next update, just pin to the specific version.
