### ISSUE TITLE
django-extra-settings Support

### ISSUE THREAD

**Issue by jonnyhoff** [unfoldadmin/django-unfold#901]
**Do you have any examples?**

https://github.com/fabiocaccamo/django-extra-settings

Default Admin:
![image](https://github.com/user-attachments/assets/3fa2819d-6c7d-428c-b5a8-08b8f7014c61)

Unfold Admin (Not displaying correctly):
![image](https://github.com/user-attachments/assets/b731ea44-2d3c-48f0-a40e-82e9fcbd8f1d)

**Is it a third party application feature request?**

Yes

**In case of third party application, when it was updated last time?**

2 months ago

**Describe your feature request**

Describe the feature in detail. Feel free to link existing pull request, implemeting a new feature.

Add support for django-extra-settings package.

The settings admin is not displayed correctly. See examples.

**Comment by lukasvinclav** [comment]
I think you have to just deregister default admin model and register it again with proper `ModelAdmin`. Example: 

https://unfoldadmin.com/docs/installation/auth/

**Comment by jonnyhoff** [comment]
> I think you have to just deregister default admin model and register it again with proper `ModelAdmin`. Example:
> 
> https://unfoldadmin.com/docs/installation/auth/

Doing as you suggested still doesn't work. Some styling is fixed but the layout is not.

![image](https://github.com/user-attachments/assets/6dad9bc1-d93b-4b31-9807-358567b1112c)

```python
from extra_settings.models import Setting
from extra_settings.admin import SettingAdmin as ExtraSettingAdmin

admin.site.unregister(Setting)

@admin.register(Setting)
class SettingAdmin(ExtraSettingAdmin,ModelAdmin):
    pass
```

**Comment by lukasvinclav** [comment]
What will happen if you try not to display all avaiable fields in this table?

**Comment by lukasvinclav** [comment]
I'm closing this issue for now. I believe the layout looks okay, if it is not displaying large set of fields. In case you will find something specific what does not work, please open new issue.

**Comment by LuisHPorras** [comment]
Hi, same thing happens to our project. The main problem is that there should only be one "Value" column with the current value but seems like unfold its not only messing with the rendering but I'm also unable to edit any records of the db. ¿Is there a chance you would reconsider this issue?

Anyway, thanks a lot for the project!
