### ISSUE TITLE
Users section and few other have non-styled fields

### ISSUE THREAD

**Issue by edin-kesetovic** [unfoldadmin/django-unfold#908]
**What version of Unfold are you using?**

latest

**What version of Django are you using?**

latest

**What browser are you using?**

Chrome

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes, and it's mentioned in one, but I don't still understand how to fix it.

**Did you searched other issues, if the bug is not already fixed?**

Yes
**Did you checked documentation?**

Yes

**Are you able to replicate the bug in the demo site?**

No

**Repository with reproduced bug**

Actually can't share my code 

**Describe your issue**

So when I go to my Users section some fields are not styled to match Unfold, like CSS is broken. After adding a codeblock to unregister and register User it fixed only one field, while other still broken.

Here's an example:
![image](https://github.com/user-attachments/assets/da7fad62-b73b-40f0-b983-7b1fdccb1e1b)

**Comment by edin-kesetovic** [comment]
Actually bug on my end, fixed.

**Comment by randykleinman** [comment]
> Actually bug on my end, fixed.

What was the solution @edin-kesetovic ? I am seeing this in my admin as well.
