### ISSUE TITLE
Changelist actions in mobile

### ISSUE THREAD

**Issue by arischaristes** [unfoldadmin/django-unfold#909]
**What version of Unfold are you using?**

Latest from github

**What version of Django are you using?**

5.1

**What browser are you using?**

Chrome, Firefox

**Did you checked changelog/commit history, if the bug is not already fixed?**

Yes, it is not fixed.

**Did you searched other issues, if the bug is not already fixed?**

Yes, there isn't any related issue.

**Did you checked documentation?**

Yes.

**Are you able to replicate the bug in the demo site?**

Yes you can replicate the bug in the demo.

**Describe your issue**

The actions menu appears slightly broken in mobile, as you can see below.

![image](https://github.com/user-attachments/assets/09ae0754-3d9b-4283-bdf8-6f80178d2c86)

**Comment by lukasvinclav** [comment]
Thanks for report. Fixed in #912
