### ISSUE TITLE
Can't open user center to change password

### ISSUE THREAD

**Issue by xdbytes** [unfoldadmin/django-unfold#91]
When i click user icon in the picture 1,i get one error in picture 2
![image](https://github.com/unfoldadmin/django-unfold/assets/77269893/fb80ed8a-bac8-49a6-9e5e-d0013a4b4cbd)
![image](https://github.com/unfoldadmin/django-unfold/assets/77269893/510c7a16-8836-4516-8e2e-ed31c235a63e)

**Comment by lukasvinclav** [comment]
I think this was fixed two days ago. Make sure you are using most recent version 0.6.7

**Comment by justinqian42** [comment]
I noticed the same actually. Will try to use the most recent version and try again. Thanks.

**Comment by xdbytes** [comment]
> I think this was fixed two days ago. Make sure you are using most recent version 0.6.7

Yes, it's has been fixed in 0.6.7

**Comment by xdbytes** [comment]
> I think this was fixed two days ago. Make sure you are using most recent version 0.6.7

Yes,It has been fixed in 0.6.7.

**Comment by xdbytes** [comment]
It has been fixed in 0.6.7.
