### ISSUE TITLE
When using header=True, text alignment on mobile is poor

### ISSUE THREAD

**Issue by Daspy11** [unfoldadmin/django-unfold#92]
This can be fixed by adding `text-right lg:text-left` to the styles for the parent element like so.

**Before**
```
<div class="flex items-center">
    <div class="block flex flex-col align-end">
        <h3>
            asd asd
        </h3>
        <p class="text-gray-500 text-xs">
            asd@asd.asd
        </p>
    </div>
</div>
```
<img width="609" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/c4868b3a-9ad5-4a8a-9189-93b338cb7936">

**After**
```
<div class="flex items-center text-right lg:text-left">
    <div class="block flex flex-col align-end">
        <h3>
            asd asd
        </h3>

        <p class="text-gray-500 text-xs">
            asd@asd.asd
        </p>
    </div>
</div>
```
<img width="609" alt="image" src="https://github.com/unfoldadmin/django-unfold/assets/24847059/146b96f1-98f9-47a0-bf56-b93ef78e3f82">

**Comment by Daspy11** [comment]
Happy to start opening PRs if it's welcome. This is a really awesome project, sorely needed by the Django community

**Comment by lukasvinclav** [comment]
Hey, thanks for report but I'm not able to identify where exactly the error is occurring from the screenshot. Would you mind to send bigger screenshot? Also I tried to search for align-end in the code to locate filename but it seems that the class is not used at all in Unfold.

**Comment by lukasvinclav** [comment]
Found it. Fixed. Thanks!
