### ISSUE TITLE
RangeDateFilter results in a 500 error if we send a date in an invalid format

### ISSUE THREAD

**Issue by FabrizioDiPrinzio** [unfoldadmin/django-unfold#94]
If we write a date in the `DateRangeFilter`'s text widget and we use an incorrect format, the page returns a 500 error with the following message: `['“06-01-2023” value has an invalid date format. It must be in YYYY-MM-DD format.']`

![date](https://github.com/unfoldadmin/django-unfold/assets/67496905/a24dc459-0cf9-4aea-a114-c936ec8538e2)
The input that results in a 500 error

Could it be possible to catch this error and display this as an error message on the input field instead of crashing the page? Similarly to how the error is handled in Django's change form

![caught error](https://github.com/unfoldadmin/django-unfold/assets/67496905/ea79cc69-cd91-4a64-9063-b1c485eadbb6)
Error being handled in Django's change form.

**Comment by lukasvinclav** [comment]
Hey, I already tried several times to replicate the issue but I was not able to find a way how to do it. Could you provide some minimal example how I can reproduce the issue? Thanks

**Comment by Daspy11** [comment]
Hey @lukasvinclav, we ended up writing a custom class to inherit from the Unfold implementation to catch the error.

To cause the original bug, define a model admin with the following filters:

```
list_filter = (
        ("date_field", RangeDateFilter),
    )
```

When done, put in any text except the valid format and hit save. The validation error is uncaught and triggers a 500.

Here's our solution which should give you an idea of what needs doing:

```
class CustomRangeDateFilter(RangeDateFilter):
    def queryset(self, request: HttpRequest, queryset: QuerySet) -> QuerySet:
        """
        Override the queryset method to catch validation errors and display them as messages instead of raising
        exceptions.
        """
        try:
            return super().queryset(request, queryset)
        except ValidationError as e:
            # Remove the hour/minute/second/microsecond/TZ part of the error message from DateTimeFields for
            # readability.
            reformatted_messages = [message.replace("HH:MM[:ss[.uuuuuu]][TZ]", "") for message in e.messages]
            messages.error(request, "\n".join(reformatted_messages))
            return queryset
```

**Comment by lukasvinclav** [comment]
Thanks for explanation. Now everything is clear with the fix already in main branch.
